include_guard(GLOBAL)

# Records a target and the dependencies it may use, for dag_check. A target given SOURCES is
# checked on those files only, which no other target in its directory is then checked on.
function(_reboot_record_target target kind)
  cmake_parse_arguments(PARSE_ARGV 2 arg "" "" "DEPS;SOURCES")
  set(sources "")
  foreach(source IN LISTS arg_SOURCES)
    cmake_path(ABSOLUTE_PATH source BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" NORMALIZE OUTPUT_VARIABLE source)
    list(APPEND sources "${source}")
  endforeach()
  set_property(GLOBAL APPEND PROPERTY REBOOT_TARGETS ${target})
  set_property(GLOBAL PROPERTY REBOOT_KIND_${target} ${kind})
  set_property(GLOBAL PROPERTY REBOOT_DIR_${target} "${CMAKE_CURRENT_SOURCE_DIR}")
  set_property(GLOBAL PROPERTY REBOOT_DEPS_${target} "${arg_DEPS}")
  set_property(GLOBAL PROPERTY REBOOT_SOURCES_${target} "${sources}")
endfunction()

function(_reboot_os_matches os out)
  if(os STREQUAL "")
    set(matches TRUE)
  elseif(os STREQUAL "WINDOWS")
    set(matches ${WIN32})
  elseif(os STREQUAL "APPLE")
    set(matches ${APPLE})
  elseif(os STREQUAL "LINUX")
    string(COMPARE EQUAL "${CMAKE_SYSTEM_NAME}" "Linux" matches)
  elseif(os STREQUAL "POSIX")
    set(matches ${UNIX})
  else()
    message(FATAL_ERROR "OS must be WINDOWS, APPLE, LINUX or POSIX, not '${os}'")
  endif()
  if(matches)
    set(${out} TRUE PARENT_SCOPE)
  else()
    set(${out} FALSE PARENT_SCOPE)
  endif()
endfunction()

# reboot_add_package(<area> SOURCES ... [DEPS ...] [PUBLIC_DEPS ...] [OS WINDOWS|APPLE|LINUX|POSIX] [NO_TESTS])
# <area> is the include area: "backend", or "os_linux/ipc" for an OS package.
function(reboot_add_package area)
  cmake_parse_arguments(PARSE_ARGV 1 arg "NO_TESTS" "OS" "SOURCES;DEPS;PUBLIC_DEPS")
  if(arg_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "reboot_add_package(${area}): unexpected arguments ${arg_UNPARSED_ARGUMENTS}")
  endif()
  _reboot_os_matches("${arg_OS}" os_matches)
  if(NOT os_matches)
    return()
  endif()
  if(NOT arg_SOURCES)
    message(FATAL_ERROR "reboot_add_package(${area}): SOURCES is empty")
  endif()

  string(REPLACE "/" "_" name "${area}")
  set(target reboot_${name})
  add_library(${target} STATIC ${arg_SOURCES})
  add_library(reboot::${name} ALIAS ${target})
  target_include_directories(${target}
    PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include"
    PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
  target_link_libraries(${target}
    PUBLIC reboot::foundation reboot::ports reboot::contracts ${arg_PUBLIC_DEPS}
    PRIVATE ${arg_DEPS} reboot_warnings)
  _reboot_record_target(${target} package DEPS ${arg_DEPS} ${arg_PUBLIC_DEPS})

  if(NOT REBOOT_BUILD_TESTS OR arg_NO_TESTS)
    return()
  endif()
  file(GLOB test_sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/tests/*.cpp")
  if(NOT test_sources)
    return()
  endif()
  add_executable(${target}_tests ${test_sources})
  target_include_directories(${target}_tests PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/src")
  target_link_libraries(${target}_tests PRIVATE ${target} ${arg_DEPS} Catch2::Catch2WithMain reboot_warnings)
  if(NOT target STREQUAL "reboot_testing")
    target_link_libraries(${target}_tests PRIVATE $<TARGET_NAME_IF_EXISTS:reboot_testing>)
  endif()
  if(NOT COMMAND catch_discover_tests)
    include(Catch)
  endif()
  catch_discover_tests(${target}_tests)
endfunction()

# reboot_add_executable(<name> SOURCES ... [DEPS ...] [OS WINDOWS|APPLE|LINUX|POSIX])
function(reboot_add_executable name)
  cmake_parse_arguments(PARSE_ARGV 1 arg "" "OS" "SOURCES;DEPS")
  if(arg_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "reboot_add_executable(${name}): unexpected arguments ${arg_UNPARSED_ARGUMENTS}")
  endif()
  _reboot_os_matches("${arg_OS}" os_matches)
  if(NOT os_matches)
    return()
  endif()
  add_executable(${name} ${arg_SOURCES})
  target_link_libraries(${name} PRIVATE ${arg_DEPS} reboot_warnings)
  _reboot_record_target(${name} executable DEPS ${arg_DEPS} SOURCES ${arg_SOURCES})
endfunction()
