use std::collections::{BTreeMap, BTreeSet, HashMap};

use prost_types::field_descriptor_proto::Type;

use crate::model::{Enum, Field, File, Message, Method, Service, OPTIONS_FILE, PACKAGE};

const EVENT_KIND_ENUM: &str = "EventKind";
const EVENT_PAYLOAD: &str = "EventPayload";
const INCLUDE_PREFIX: &str = "reboot/api/v1";
// Output paths are relative to launcher/core; the C++ goes to the api package.
pub const API_DIR: &str = "api";
// Owned by the generator: a header in it that a run does not produce is stale.
pub const HEADER_DIR: &str = "include/reboot/api/v1";
// The method ids of the public C ABI, in the client package, which never includes api headers.
const C_METHODS_HEADER: &str = "client/include/reboot/client_methods.h";
const NAMESPACE: &str = "reboot::api";
const MAX_LINE: usize = 120;

const CPP_KEYWORDS: &[&str] = &[
    "alignas", "alignof", "and", "and_eq", "asm", "auto", "bitand", "bitor", "bool", "break", "case", "catch",
    "char", "char8_t", "char16_t", "char32_t", "class", "compl", "concept", "const", "consteval", "constexpr",
    "constinit", "const_cast", "continue", "co_await", "co_return", "co_yield", "decltype", "default", "delete",
    "do", "double", "dynamic_cast", "else", "enum", "explicit", "export", "extern", "false", "float", "for",
    "friend", "goto", "if", "inline", "int", "long", "mutable", "namespace", "new", "noexcept", "not", "not_eq",
    "nullptr", "operator", "or", "or_eq", "private", "protected", "public", "register", "reinterpret_cast",
    "requires", "return", "short", "signed", "sizeof", "static", "static_assert", "static_cast", "struct",
    "switch", "template", "this", "thread_local", "throw", "true", "try", "typedef", "typeid", "typename",
    "union", "unsigned", "using", "virtual", "void", "volatile", "wchar_t", "while", "xor", "xor_eq", "final",
    "override", "import", "module",
];

fn is_keyword(name: &str) -> bool {
    CPP_KEYWORDS.contains(&name)
}

fn scalar(ty: Type) -> Option<&'static str> {
    match ty {
        Type::Bool => Some("bool"),
        Type::Uint32 => Some("u32"),
        Type::Uint64 => Some("u64"),
        Type::Sint32 => Some("i32"),
        Type::Sint64 => Some("i64"),
        _ => None,
    }
}

pub fn snake(name: &str) -> String {
    let mut out = String::new();
    let mut previous: Option<char> = None;
    for c in name.chars() {
        if c.is_ascii_uppercase() && previous.is_some_and(|p| p.is_ascii_lowercase() || p.is_ascii_digit()) {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
        previous = Some(c);
    }
    out
}

pub fn pascal(upper_snake: &str) -> String {
    upper_snake.split('_').map(|part| {
        let mut chars = part.chars();
        match chars.next() {
            Some(first) => first.to_ascii_uppercase().to_string() + &chars.as_str().to_ascii_lowercase(),
            None => String::new(),
        }
    }).collect()
}

fn enum_prefix(enum_name: &str) -> String {
    snake(enum_name).to_ascii_uppercase() + "_"
}

fn is_cpp_enumerator(name: &str) -> bool {
    let mut chars = name.chars();
    chars.next().is_some_and(|c| c.is_ascii_uppercase()) && chars.all(|c| c.is_ascii_alphanumeric())
}

fn short_name(full_name: &str) -> &str {
    full_name.strip_prefix(&format!(".{PACKAGE}.")).unwrap_or(full_name)
}

fn banner(source: Option<&str>) -> String {
    match source {
        Some(name) => format!("// Generated by protoc-gen-reboot-cpp from {name}. Do not edit."),
        None => "// Generated by protoc-gen-reboot-cpp. Do not edit.".to_owned(),
    }
}

fn include_block(std: &[&str], local: &[&str]) -> Vec<String> {
    let mut lines: Vec<String> = std.iter().map(|h| format!("#include <{h}>")).collect();
    if !std.is_empty() && !local.is_empty() {
        lines.push(String::new());
    }
    lines.extend(local.iter().map(|h| format!("#include \"{h}\"")));
    lines
}

fn join(lines: Vec<String>) -> String {
    lines.join("\n")
}

// MethodKind, ProgressUnit and Disconnect from options.proto: value number -> C++ enumerator.
struct OptionEnums {
    kind: BTreeMap<i32, String>,
    progress: BTreeMap<i32, String>,
    disconnect: BTreeMap<i32, String>,
}

impl OptionEnums {
    fn read(options: &File) -> Result<Self, String> {
        let names = |enum_name: &str| -> Result<BTreeMap<i32, String>, String> {
            let e = options.enums.iter().find(|e| e.name == enum_name)
                .ok_or_else(|| format!("{OPTIONS_FILE} does not declare {enum_name}"))?;
            let prefix = enum_prefix(enum_name);
            Ok(e.values.iter()
                .map(|v| (v.number, pascal(v.name.strip_prefix(&prefix).unwrap_or(&v.name))))
                .collect())
        };
        Ok(Self { kind: names("MethodKind")?, progress: names("ProgressUnit")?, disconnect: names("Disconnect")? })
    }
}

fn is_call(method: &Method) -> bool {
    method.info.as_ref().is_none_or(|info| info.kind == 0)
}

pub struct Generator<'a> {
    files: Vec<&'a File>,
    messages: HashMap<&'a str, &'a Message>,
    enums: HashMap<&'a str, &'a Enum>,
    options: OptionEnums,
    // Whether a message, or one it holds, has a oneof; such messages get check_cases.
    checked: HashMap<String, bool>,
    errors: Vec<String>,
}

impl<'a> Generator<'a> {
    pub fn new(all: &'a [File], to_generate: &[String]) -> Result<Self, String> {
        let options_file = all.iter().find(|f| f.name == OPTIONS_FILE)
            .ok_or_else(|| format!("{OPTIONS_FILE} is missing"))?;
        let mut files = Vec::new();
        for name in to_generate.iter().filter(|name| name.as_str() != OPTIONS_FILE) {
            files.push(all.iter().find(|f| &f.name == name).ok_or_else(|| format!("{name} was not supplied"))?);
        }
        // protoc and buf list the files in different orders; the output must not depend on it.
        files.sort_by(|a, b| a.name.cmp(&b.name));
        let mut messages = HashMap::new();
        let mut enums = HashMap::new();
        for f in all.iter().filter(|f| f.package == PACKAGE && f.name != OPTIONS_FILE) {
            messages.extend(f.messages.iter().map(|m| (m.name.as_str(), m)));
            enums.extend(f.enums.iter().map(|e| (e.name.as_str(), e)));
        }
        Ok(Self { files, messages, enums, options: OptionEnums::read(options_file)?, checked: HashMap::new(), errors: Vec::new() })
    }

    fn error(&mut self, location: impl AsRef<str>, message: impl AsRef<str>) {
        self.errors.push(format!("{}: {}", location.as_ref(), message.as_ref()));
    }

    fn check(&mut self) -> Result<(), String> {
        let mut service_ids = HashMap::new();
        let mut method_ids = HashMap::new();
        for f in self.files.clone() {
            if f.syntax != "proto3" {
                self.error(&f.name, "must use proto3");
            }
            if f.package != PACKAGE {
                self.error(&f.name, format!("must be in package {PACKAGE}"));
            }
            for e in &f.enums {
                self.check_enum(f, e);
            }
            for m in &f.messages {
                self.check_message(f, m);
            }
            for s in &f.services {
                self.check_service(f, s, &mut service_ids, &mut method_ids);
            }
        }
        self.check_events();
        if !self.errors.is_empty() {
            return Err(self.errors.join("\n"));
        }
        let names: Vec<&str> = self.messages.keys().copied().collect();
        for name in names {
            self.compute_checked(name, &mut Vec::new())?;
        }
        Ok(())
    }

    fn check_enum(&mut self, f: &File, e: &Enum) {
        let prefix = enum_prefix(&e.name);
        if e.values.first().is_none_or(|v| v.number != 0) {
            self.error(format!("{} {}", f.name, e.name), "the first value must be 0");
        }
        for v in &e.values {
            let location = format!("{} {}.{}", f.name, e.name, v.name);
            match v.name.strip_prefix(&prefix) {
                None => self.error(&location, format!("must start with {prefix}")),
                Some(rest) if !is_cpp_enumerator(&pascal(rest)) => self.error(&location, "does not map to a C++ enumerator"),
                Some(_) => {}
            }
            if v.number < 0 {
                self.error(&location, "negative values are not allowed");
            }
        }
    }

    fn check_message(&mut self, f: &File, m: &Message) {
        let location = format!("{} {}", f.name, m.name);
        if m.has_nested {
            self.error(&location, "nested messages, enums and maps are not allowed; declare types at file level");
        }
        for (index, field) in m.fields.iter().enumerate() {
            let at = format!("{location}.{}", field.name);
            if field.number != index as i32 + 1 {
                self.error(&at, format!("is field {} but must be {}: numbers are contiguous and in order",
                                        field.number, index + 1));
            }
            if is_keyword(&field.name) {
                self.error(&at, "is a C++ keyword");
            }
            let carried = scalar(field.ty).is_some() || matches!(field.ty, Type::String | Type::Bytes | Type::Enum | Type::Message);
            if !carried {
                self.error(&at, "has a type the sb codec cannot carry (use bool, uint32/64, sint32/64, string, bytes, enum or message)");
            }
            let name = short_name(&field.type_name);
            if field.ty == Type::Message && !self.messages.contains_key(name) {
                self.error(&at, format!("refers to unknown message {name}"));
            }
            if field.ty == Type::Enum && !self.enums.contains_key(name) {
                self.error(&at, format!("refers to unknown enum {name}"));
            }
            if field.fixed_size != 0 && field.ty != Type::Bytes {
                self.error(&at, "fixed_size applies to bytes fields only");
            }
            if field.fixed_size != 0 && field.repeated {
                self.error(&at, "fixed_size cannot be repeated");
            }
        }
        for group in m.oneof_groups() {
            let first = m.fields.iter().position(|field| std::ptr::eq(field, group[0])).unwrap_or_default();
            let consecutive = group.iter().enumerate().all(|(i, field)| std::ptr::eq(*field, &m.fields[first + i]));
            if !consecutive {
                let oneof = &m.oneofs[group[0].oneof_index.unwrap_or_default() as usize];
                self.error(&location, format!("oneof {oneof} members must be declared consecutively"));
            }
        }
    }

    fn check_service(&mut self, f: &File, s: &Service, service_ids: &mut HashMap<u32, String>,
                     method_ids: &mut HashMap<u32, String>) {
        let location = format!("{} {}", f.name, s.name);
        if !(1..=0xFFFF).contains(&s.id) {
            self.error(&location, "needs option (service_info) = {id: 1..65535}");
        } else if let Some(other) = service_ids.get(&s.id) {
            self.error(&location, format!("reuses service id {} of {other}", s.id));
        }
        service_ids.insert(s.id, s.name.clone());
        let mut local_ids = BTreeSet::new();
        for m in &s.methods {
            let at = format!("{location}.{}", m.name);
            let Some(info) = m.info.as_ref().filter(|info| (1..=0xFFFF).contains(&info.id)) else {
                self.error(&at, "needs option (method_info) = {id: 1..65535}");
                continue;
            };
            if !local_ids.insert(info.id) {
                self.error(&at, format!("reuses method id {}", info.id));
            }
            let full_id = s.id << 16 | info.id;
            if let Some(other) = method_ids.get(&full_id).filter(|other| **other != at) {
                self.error(&at, format!("method_id {full_id:#010x} collides with {other}"));
            }
            method_ids.insert(full_id, at.clone());
            if m.streaming {
                self.error(&at, "streaming is not supported");
            }
            if !self.options.kind.contains_key(&info.kind) || !self.options.progress.contains_key(&info.progress)
                || !self.options.disconnect.contains_key(&info.disconnect) {
                self.error(&at, "has an unknown method_info enum value");
            }
            if info.kind == 0 && (info.progress != 0 || info.disconnect != 0) {
                self.error(&at, "a CALL has no progress and no disconnect policy");
            }
            for type_name in [&m.input_type, &m.output_type] {
                if !self.messages.contains_key(short_name(type_name)) {
                    self.error(&at, format!("uses unknown message {type_name}"));
                }
            }
            if is_keyword(&handler_method_name(m)) {
                self.error(&at, "maps to a C++ keyword");
            }
        }
    }

    fn check_events(&mut self) {
        let (Some(payload), Some(kinds)) = (self.messages.get(EVENT_PAYLOAD).copied(), self.enums.get(EVENT_KIND_ENUM).copied())
        else {
            return;
        };
        let groups = payload.oneof_groups();
        if groups.len() != 1 || groups[0].len() != payload.fields.len() {
            self.error(EVENT_PAYLOAD, "must be a single oneof");
        }
        let prefix = enum_prefix(EVENT_KIND_ENUM);
        let kind_names: BTreeSet<String> = kinds.values.iter()
            .map(|v| v.name.strip_prefix(&prefix).unwrap_or(&v.name).to_ascii_lowercase())
            .collect();
        for field in &payload.fields {
            if !kind_names.contains(&field.name) {
                self.error(format!("{EVENT_PAYLOAD}.{}", field.name), format!("has no {EVENT_KIND_ENUM} value of the same name"));
            }
        }
    }

    fn compute_checked(&mut self, name: &str, visiting: &mut Vec<String>) -> Result<bool, String> {
        if let Some(&known) = self.checked.get(name) {
            return Ok(known);
        }
        if visiting.iter().any(|v| v == name) {
            return Err(format!("{name} contains itself; recursive messages are not allowed"));
        }
        let message = self.messages[name];
        let mut result = !message.oneof_groups().is_empty();
        visiting.push(name.to_owned());
        for field in message.fields.iter().filter(|field| field.ty == Type::Message) {
            result |= self.compute_checked(short_name(&field.type_name), visiting)?;
        }
        visiting.pop();
        self.checked.insert(name.to_owned(), result);
        Ok(result)
    }

    fn is_checked(&self, type_name: &str) -> bool {
        self.checked.get(short_name(type_name)).copied().unwrap_or_default()
    }

    fn base_type(&self, field: &Field) -> String {
        if let Some(name) = scalar(field.ty) {
            return name.to_owned();
        }
        match field.ty {
            Type::String => "std::string".to_owned(),
            Type::Bytes if field.fixed_size == 16 => "Uuid".to_owned(),
            Type::Bytes if field.fixed_size != 0 => format!("std::array<u8, {}>", field.fixed_size),
            Type::Bytes => "Bytes".to_owned(),
            _ => short_name(&field.type_name).to_owned(),
        }
    }

    fn member(&self, field: &Field) -> (String, &'static str) {
        let base = self.base_type(field);
        if field.repeated {
            return (format!("std::vector<{base}>"), "");
        }
        if field.optional() {
            return (format!("std::optional<{base}>"), "");
        }
        let init = match field.ty {
            Type::Bool => " = false",
            _ if scalar(field.ty).is_some() => " = 0",
            Type::Enum => "{}",
            Type::Bytes if field.fixed_size != 0 && field.fixed_size != 16 => "{}",
            _ => "",
        };
        (base, init)
    }

    fn comment(f: &File, path: &[i32], indent: &str) -> Vec<String> {
        let Some(body) = f.comments.get(path) else {
            return Vec::new();
        };
        body.trim_matches('\n').split('\n')
            .map(|line| format!("{indent}// {}", line.trim()).trim_end().to_owned())
            .collect()
    }

    fn includes_for(&self, f: &File) -> (Vec<&'static str>, Vec<String>) {
        let mut std = BTreeSet::new();
        let mut local: BTreeSet<String> = BTreeSet::new();
        let mut uses_types = !f.enums.is_empty();
        for m in &f.messages {
            if self.checked[m.name.as_str()] {
                std.insert("optional");
                local.insert("reboot/api/codec.hpp".to_owned());
            }
            for field in &m.fields {
                if field.repeated {
                    std.insert("vector");
                } else if field.optional() {
                    std.insert("optional");
                }
                match field.ty {
                    Type::String => {
                        std.insert("string");
                    }
                    Type::Bytes if field.fixed_size == 0 => {
                        local.insert("reboot/api/codec.hpp".to_owned());
                    }
                    Type::Bytes => {
                        uses_types = true;
                        if field.fixed_size != 16 {
                            std.insert("array");
                        }
                    }
                    Type::Bool | Type::Message | Type::Enum => {}
                    _ => uses_types = true,
                }
            }
        }
        if uses_types {
            local.insert("reboot/foundation/types.hpp".to_owned());
        }
        if !f.services.is_empty() {
            local.insert("reboot/api/call_context.hpp".to_owned());
            local.insert("reboot/foundation/result_fwd.hpp".to_owned());
            if f.services.iter().flat_map(|s| &s.methods).any(|m| !is_call(m)) {
                local.insert("reboot/foundation/operation.hpp".to_owned());
            }
        }
        for dep in &f.dependencies {
            if dep.starts_with(&format!("{INCLUDE_PREFIX}/")) && dep != OPTIONS_FILE {
                let stem = dep.rsplit('/').next().unwrap_or(dep).trim_end_matches(".proto");
                local.insert(format!("{INCLUDE_PREFIX}/{stem}.hpp"));
            }
        }
        (std.into_iter().collect(), local.into_iter().collect())
    }

    // Declaration order, except that a message follows every same-file message it holds.
    fn ordered_messages(f: &'a File) -> Vec<&'a Message> {
        fn visit<'m>(message: &'m Message, local: &HashMap<&str, &'m Message>, done: &mut BTreeSet<String>,
                     order: &mut Vec<&'m Message>) {
            if !done.insert(message.name.clone()) {
                return;
            }
            for field in message.fields.iter().filter(|field| field.ty == Type::Message) {
                if let Some(dep) = local.get(short_name(&field.type_name)) {
                    visit(dep, local, done, order);
                }
            }
            order.push(message);
        }
        let local: HashMap<&str, &Message> = f.messages.iter().map(|m| (m.name.as_str(), m)).collect();
        let mut done = BTreeSet::new();
        let mut order = Vec::new();
        for message in &f.messages {
            visit(message, &local, &mut done, &mut order);
        }
        order
    }

    fn file_header(&self, f: &'a File) -> String {
        let (std, local) = self.includes_for(f);
        let local: Vec<&str> = local.iter().map(String::as_str).collect();
        let mut out = vec![banner(Some(&f.name)), "#pragma once".to_owned(), String::new()];
        out.extend(include_block(&std, &local));
        out.extend([String::new(), format!("namespace {NAMESPACE} {{"), String::new()]);
        for e in &f.enums {
            out.extend(Self::enum_text(f, e));
        }
        for m in Self::ordered_messages(f) {
            out.extend(self.message_text(f, m));
        }
        if f.messages.iter().any(|m| m.name == EVENT_PAYLOAD) {
            out.extend(self.event_kind_text());
        }
        for s in &f.services {
            out.extend(Self::handler_text(f, s));
        }
        out.extend([format!("}}  // namespace {NAMESPACE}"), String::new()]);
        join(out)
    }

    fn enum_text(f: &File, e: &Enum) -> Vec<String> {
        let prefix = enum_prefix(&e.name);
        let mut out = Self::comment(f, &e.path, "");
        out.push(format!("enum class {} : u32 {{", e.name));
        for v in &e.values {
            out.extend(Self::comment(f, &v.path, "    "));
            out.push(format!("    {} = {},", pascal(v.name.strip_prefix(&prefix).unwrap_or(&v.name)), v.number));
        }
        out.extend(["};".to_owned(), String::new()]);
        out
    }

    fn message_text(&self, f: &File, m: &Message) -> Vec<String> {
        let mut out = Self::comment(f, &m.path, "");
        out.push(format!("struct {} {{", m.name));
        let first_members: BTreeSet<&str> = m.oneof_groups().iter().map(|group| group[0].name.as_str()).collect();
        for field in &m.fields {
            if first_members.contains(field.name.as_str()) {
                out.push("    // Exactly one of the following is set; none set is a case this build does not know.".to_owned());
            }
            out.extend(Self::comment(f, &field.path, "    "));
            if field.deprecated {
                out.push("    // Deprecated.".to_owned());
            }
            let (member_type, init) = self.member(field);
            out.push(format!("    {member_type} {}{init};", field.name));
        }
        if !m.fields.is_empty() {
            out.push(String::new());
        }
        out.extend([format!("    bool operator==(const {}&) const = default;", m.name), "};".to_owned(), String::new()]);
        if self.checked[m.name.as_str()] {
            out.extend(self.check_cases_text(m));
        }
        out
    }

    fn check_cases_text(&self, m: &Message) -> Vec<String> {
        let mut out = vec![format!("[[nodiscard]] inline std::optional<DecodeError> check_cases(const {}& m) noexcept {{", m.name)];
        for group in m.oneof_groups() {
            let members: Vec<String> = group.iter().map(|field| format!("m.{}.has_value()", field.name)).collect();
            let line = format!("    if (auto error = one_case({{{}}})) return error;", members.join(", "));
            if line.len() <= MAX_LINE {
                out.push(line);
                continue;
            }
            let indent = " ".repeat("    if (auto error = one_case({".len());
            out.push(format!("    if (auto error = one_case({{{}}}))", members.join(&format!(",\n{indent}"))));
            out.push("        return error;".to_owned());
        }
        for field in m.fields.iter().filter(|field| field.ty == Type::Message && self.is_checked(&field.type_name)) {
            let name = &field.name;
            out.push(if field.repeated {
                format!("    if (auto error = check_all_cases(m.{name})) return error;")
            } else if field.optional() {
                format!("    if (auto error = m.{name} ? check_cases(*m.{name}) : std::nullopt) return error;")
            } else {
                format!("    if (auto error = check_cases(m.{name})) return error;")
            });
        }
        out.extend(["    return std::nullopt;".to_owned(), "}".to_owned(), String::new()]);
        out
    }

    fn event_kind_text(&self) -> Vec<String> {
        let payload = self.messages[EVENT_PAYLOAD];
        let mut out = vec![
            "// Unspecified only for a payload that failed check_cases.".to_owned(),
            format!("[[nodiscard]] inline {EVENT_KIND_ENUM} event_kind(const {EVENT_PAYLOAD}& payload) noexcept {{"),
        ];
        for field in &payload.fields {
            out.push(format!("    if (payload.{}) return {EVENT_KIND_ENUM}::{};", field.name, pascal(&field.name)));
        }
        out.extend([format!("    return {EVENT_KIND_ENUM}::Unspecified;"), "}".to_owned(), String::new()]);
        out.extend([
            "// Whether Event.payload holds an EventPayload. False for a kind this build does not know;".to_owned(),
            "// consumers skip such events, and those whose payload fails to decode.".to_owned(),
            format!("[[nodiscard]] constexpr bool has_payload({EVENT_KIND_ENUM} kind) noexcept {{"),
            "    switch (kind) {".to_owned(),
        ]);
        for field in &payload.fields {
            out.push(format!("        case {EVENT_KIND_ENUM}::{}:", pascal(&field.name)));
        }
        out.extend([
            "            return true;".to_owned(),
            "        default:".to_owned(),
            "            return false;".to_owned(),
            "    }".to_owned(),
            "}".to_owned(),
            String::new(),
        ]);
        out
    }

    fn handler_text(f: &File, s: &Service) -> Vec<String> {
        let mut out = Self::comment(f, &s.path, "");
        out.extend([format!("class I{}Handler {{", s.name), "public:".to_owned(),
                    format!("    virtual ~I{}Handler() = default;", s.name), String::new()]);
        for m in &s.methods {
            let request = short_name(&m.input_type);
            let response = short_name(&m.output_type);
            out.extend(Self::comment(f, &m.path, "    "));
            if is_call(m) {
                out.push(format!("    virtual ::reboot::Result<{response}> {}(const CallContext& context, const {request}& request) = 0;",
                                 handler_method_name(m)));
            } else {
                out.push(format!("    // Completes with {response}."));
                out.push(format!("    virtual ::reboot::Result<::reboot::OpHandle> {}(const CallContext& context, const {request}& request, \
                                  ::reboot::DisconnectPolicy disconnect) = 0;", handler_method_name(m)));
            }
        }
        out.extend(["};".to_owned(), String::new()]);
        out
    }

    fn all_methods(&self) -> Vec<(u32, &'a Service, &'a Method)> {
        let mut rows: Vec<(u32, &Service, &Method)> = self.files.iter()
            .flat_map(|f| &f.services)
            .flat_map(|s| s.methods.iter().map(move |m| (s.id << 16 | m.info.as_ref().map_or(0, |info| info.id), s, m)))
            .collect();
        rows.sort_by_key(|row| row.0);
        rows
    }

    // FNV-1a 64 over what payloads and the method table depend on: names, field numbers, types,
    // presence, enum values and method options. Comments leave it unchanged.
    fn fingerprint(&self) -> String {
        let mut text = String::new();
        for f in &self.files {
            for e in &f.enums {
                text.push_str(&format!("enum {}
", e.name));
                for v in &e.values {
                    text.push_str(&format!(" {}={}
", v.name, v.number));
                }
            }
            for m in &f.messages {
                text.push_str(&format!("message {}
", m.name));
                for field in &m.fields {
                    text.push_str(&format!(" {} {} {} {} {} {} {}
", field.name, field.number, field.ty as i32,
                                           field.type_name, field.repeated, field.optional(), field.fixed_size));
                }
            }
            for s in &f.services {
                text.push_str(&format!("service {} {}
", s.name, s.id));
                for m in &s.methods {
                    let info = m.info.as_ref().map_or((0, 0, 0, 0), |info| (info.id, info.kind, info.progress, info.disconnect));
                    text.push_str(&format!(" {} {} {} {:?}
", m.name, m.input_type, m.output_type, info));
                }
            }
        }
        let hash = text.bytes().fold(0xcbf2_9ce4_8422_2325_u64, |hash, byte| {
            (hash ^ u64::from(byte)).wrapping_mul(0x0000_0100_0000_01b3)
        });
        format!("{hash:016x}")
    }

    fn method_table(&self) -> String {
        let rows = self.all_methods();
        let mut out = vec![banner(None), "#pragma once".to_owned(), String::new()];
        out.extend(include_block(&["array", "cstddef", "span", "string_view"],
                                 &["reboot/api/method_spec.hpp", "reboot/foundation/operation.hpp", "reboot/foundation/types.hpp"]));
        out.extend([String::new(), format!("namespace {NAMESPACE} {{"), String::new()]);
        out.extend([
            "// Changes with every change to the schema's payloads or methods; Engine.info reports the engine's.".to_owned(),
            format!("inline constexpr std::string_view kSchemaFingerprint = \"{}\";", self.fingerprint()),
            String::new(),
        ]);
        for (id, s, m) in &rows {
            out.push(format!("inline constexpr u32 {} = {id:#010x};", constant(s, m)));
        }
        out.extend([String::new(), "// Sorted by id.".to_owned(),
                    format!("inline constexpr std::array<MethodSpec, {}> kMethods{{{{", rows.len())]);
        for (_, s, m) in &rows {
            let info = m.info.as_ref().map_or((0, 0, 0), |info| (info.kind, info.progress, info.disconnect));
            out.extend([
                "    MethodSpec{".to_owned(),
                format!("        .id = {},", constant(s, m)),
                format!("        .service = \"{PACKAGE}.{}\",", s.name),
                format!("        .name = \"{}.{}\",", snake(&s.name), snake(&m.name)),
                format!("        .kind = MethodKind::{},", self.options.kind[&info.0]),
                format!("        .default_disconnect = ::reboot::DisconnectPolicy::{},", self.options.disconnect[&info.2]),
                format!("        .progress = ProgressUnit::{},", self.options.progress[&info.1]),
                format!("        .request_type = \"{}\",", &m.input_type[1..]),
                format!("        .response_type = \"{}\",", &m.output_type[1..]),
                "    },".to_owned(),
            ]);
        }
        out.extend([
            "}};", "",
            "class MethodTable {",
            "public:",
            "    [[nodiscard]] static constexpr std::span<const MethodSpec> all() noexcept { return kMethods; }",
            "",
            "    [[nodiscard]] static constexpr const MethodSpec* find(u32 id) noexcept {",
            "        std::size_t low = 0;",
            "        std::size_t high = kMethods.size();",
            "        while (low < high) {",
            "            const std::size_t mid = low + (high - low) / 2;",
            "            if (kMethods[mid].id < id) low = mid + 1;",
            "            else high = mid;",
            "        }",
            "        return low < kMethods.size() && kMethods[low].id == id ? &kMethods[low] : nullptr;",
            "    }",
            "};", "",
        ].map(str::to_owned));
        out.extend([format!("}}  // namespace {NAMESPACE}"), String::new()]);
        join(out)
    }

    fn services(&self) -> Vec<&'a Service> {
        self.files.iter().flat_map(|f| &f.services).collect()
    }

    fn dispatch_header(&self) -> String {
        let mut out = vec![banner(None), "#pragma once".to_owned(), String::new()];
        out.extend(include_block(&["any", "optional", "span"],
                                 &["reboot/api/call_context.hpp", "reboot/api/codec.hpp", "reboot/foundation/operation.hpp",
                                   "reboot/foundation/result_fwd.hpp", "reboot/foundation/types.hpp"]));
        out.extend([String::new(), format!("namespace {NAMESPACE} {{"), String::new()]);
        for s in self.services() {
            out.push(format!("class I{}Handler;", s.name));
        }
        out.extend([String::new(), "struct Handlers {".to_owned()]);
        for s in self.services() {
            out.push(format!("    I{}Handler& {};", s.name, snake(&s.name)));
        }
        out.extend([
            "};", "",
            "// Decodes the request, runs the CALL method and encodes its response.",
            "[[nodiscard]] ::reboot::Result<Bytes> dispatch_call(const Handlers& handlers, const CallContext& context, \
             u32 method_id, std::span<const u8> request);",
            "",
            "// Decodes the request and starts the OPERATION; no `disconnect` means the method's default.",
            "[[nodiscard]] ::reboot::Result<::reboot::OpHandle> dispatch_start(const Handlers& handlers, \
             const CallContext& context, u32 method_id, std::span<const u8> request, \
             std::optional<::reboot::DisconnectPolicy> disconnect);",
            "",
            "// Encodes the value an operation completed with: the method's response message, or an empty",
            "// any (Operation<void>) when that message has no fields. Anything else is the engine's bug.",
            "[[nodiscard]] ::reboot::Result<Bytes> encode_op_result(u32 method_id, const std::any& value);",
            "",
        ].map(str::to_owned));
        out.extend([format!("}}  // namespace {NAMESPACE}"), String::new()]);
        join(out)
    }

    fn dispatch_source(&self) -> String {
        let rows = self.all_methods();
        let mut local: Vec<String> = vec![
            "messages.hpp".to_owned(),
            "reboot/api/codec.hpp".to_owned(),
            "reboot/api/decode_error.hpp".to_owned(),
            "reboot/foundation/diag.hpp".to_owned(),
            format!("{INCLUDE_PREFIX}/method_table.hpp"),
        ];
        local.extend(self.files.iter().filter(|f| !f.services.is_empty()).map(|f| format!("{INCLUDE_PREFIX}/{}.hpp", f.stem())));
        local.sort();
        let local: Vec<&str> = local.iter().map(String::as_str).collect();
        let mut out = vec![banner(None), format!("#include \"{INCLUDE_PREFIX}/dispatch.hpp\""), String::new()];
        out.extend(include_block(&["any", "optional", "span", "type_traits", "utility"], &local));
        out.extend([String::new(), format!("namespace {NAMESPACE} {{"), "namespace {".to_owned(), String::new()]);
        out.extend([
            "::reboot::Diagnostic method_error(::reboot::MessageId message, u32 method_id) {",
            "    return ::reboot::make_diag(::reboot::ErrorDomain::Api, message)",
            "        .arg(\"method\", method_id)",
            "        .kind(::reboot::ErrorKind::InvalidInput);",
            "}", "",
            "template <class Handler, class Request, class Response>",
            "::reboot::Result<Bytes> call(Handler& handler,",
            "                             ::reboot::Result<Response> (Handler::*method)(const CallContext&, const Request&),",
            "                             const CallContext& context, u32 method_id, std::span<const u8> bytes) {",
            "    auto request = decode<Request>(bytes);",
            "    if (!request) return std::unexpected(to_diagnostic(request.error(), method_id));",
            "    ::reboot::Result<Response> response = (handler.*method)(context, *request);",
            "    if (!response) return std::unexpected(std::move(response.error()));",
            "    return encode(*response);",
            "}", "",
            "template <class Handler, class Request>",
            "::reboot::Result<::reboot::OpHandle> start(",
            "    Handler& handler,",
            "    ::reboot::Result<::reboot::OpHandle> (Handler::*method)(const CallContext&, const Request&,",
            "                                                          ::reboot::DisconnectPolicy),",
            "    const CallContext& context, u32 method_id, std::span<const u8> bytes, ::reboot::DisconnectPolicy disconnect) {",
            "    auto request = decode<Request>(bytes);",
            "    if (!request) return std::unexpected(to_diagnostic(request.error(), method_id));",
            "    return (handler.*method)(context, *request, disconnect);",
            "}", "",
            "template <class Response>",
            "::reboot::Result<Bytes> encode_result(const std::any& value) {",
            "    if (const auto* response = std::any_cast<Response>(&value)) return encode(*response);",
            "    if constexpr (std::is_empty_v<Response>) {",
            "        if (!value.has_value()) return encode(Response{});",
            "    }",
            "    return std::unexpected(::reboot::internal_bug(\"api.encode_op_result\"));",
            "}", "",
            "}  // namespace", "",
            "::reboot::Result<Bytes> dispatch_call(const Handlers& handlers, const CallContext& context, u32 method_id,",
            "                                      std::span<const u8> request) {",
            "    switch (method_id) {",
        ].map(str::to_owned));
        for (_, s, m) in rows.iter().filter(|(_, _, m)| is_call(m)) {
            out.push(format!("        case {}:", constant(s, m)));
            out.push(format!("            return call(handlers.{}, &I{}Handler::{}, context, method_id, request);",
                             snake(&s.name), s.name, handler_method_name(m)));
        }
        out.extend([
            "        default:",
            "            break;",
            "    }",
            "    const ::reboot::MessageId error = MethodTable::find(method_id) ? msg::kWrongMethodKind : msg::kUnknownMethod;",
            "    return std::unexpected(method_error(error, method_id));",
            "}", "",
            "::reboot::Result<::reboot::OpHandle> dispatch_start(const Handlers& handlers, const CallContext& context,",
            "                                                    u32 method_id, std::span<const u8> request,",
            "                                                    std::optional<::reboot::DisconnectPolicy> disconnect) {",
            "    const MethodSpec* spec = MethodTable::find(method_id);",
            "    if (!spec) return std::unexpected(method_error(msg::kUnknownMethod, method_id));",
            "    if (spec->kind != MethodKind::Operation) return std::unexpected(method_error(msg::kWrongMethodKind, method_id));",
            "    const ::reboot::DisconnectPolicy policy = disconnect.value_or(spec->default_disconnect);",
            "    switch (method_id) {",
        ].map(str::to_owned));
        for (_, s, m) in rows.iter().filter(|(_, _, m)| !is_call(m)) {
            out.push(format!("        case {}:", constant(s, m)));
            out.push(format!("            return start(handlers.{}, &I{}Handler::{}, context, method_id, request, policy);",
                             snake(&s.name), s.name, handler_method_name(m)));
        }
        out.extend([
            "        default:",
            "            return std::unexpected(::reboot::internal_bug(\"api.dispatch_start\"));",
            "    }",
            "}", "",
            "::reboot::Result<Bytes> encode_op_result(u32 method_id, const std::any& value) {",
            "    switch (method_id) {",
        ].map(str::to_owned));
        for (_, s, m) in rows.iter().filter(|(_, _, m)| !is_call(m)) {
            out.push(format!("        case {}:", constant(s, m)));
            out.push(format!("            return encode_result<{}>(value);", short_name(&m.output_type)));
        }
        out.extend([
            "        default:",
            "            return std::unexpected(::reboot::internal_bug(\"api.encode_op_result\"));",
            "    }",
            "}", "",
        ].map(str::to_owned));
        out.extend([format!("}}  // namespace {NAMESPACE}"), String::new()]);
        join(out)
    }

    fn c_methods_header(&self) -> String {
        let rows = self.all_methods();
        let mut out = vec![
            "/* Generated by protoc-gen-reboot-cpp. Do not edit. */".to_owned(),
            "#pragma once".to_owned(),
            String::new(),
            "/* reboot.api.v1 method ids for rb_call (call) and rb_start (operation). Each request and response".to_owned(),
            format!(" * is the named {PACKAGE} message; an operation's outcome carries its response. */"),
            String::new(),
            "/* The schema these ids and their messages come from; a facade compares it with".to_owned(),
            " * EngineInfoResponse.schema_fingerprint. */".to_owned(),
            format!("#define RB_SCHEMA_FINGERPRINT \"{}\"", self.fingerprint()),
            String::new(),
        ];
        for (id, s, m) in &rows {
            let request = short_name(&m.input_type);
            let response = short_name(&m.output_type);
            let kind = if is_call(m) { "call".to_owned() } else {
                let disconnect = m.info.as_ref().map_or(0, |info| info.disconnect);
                let policy = if self.options.disconnect[&disconnect] == "Detached" { "detached" } else { "bound" };
                format!("operation ({policy})")
            };
            out.push(format!("/* {}.{}: {kind}; {request} -> {response} */", snake(&s.name), snake(&m.name)));
            out.push(format!("#define RB_METHOD_{}_{} {id:#010x}u", snake(&s.name).to_ascii_uppercase(),
                             snake(&m.name).to_ascii_uppercase()));
        }
        out.push(String::new());
        join(out)
    }

    pub fn run(mut self) -> Result<BTreeMap<String, String>, String> {
        self.check()?;
        let mut out = BTreeMap::new();
        for f in &self.files {
            out.insert(format!("{API_DIR}/{HEADER_DIR}/{}.hpp", f.stem()), self.file_header(f));
        }
        out.insert(format!("{API_DIR}/{HEADER_DIR}/method_table.hpp"), self.method_table());
        out.insert(format!("{API_DIR}/{HEADER_DIR}/dispatch.hpp"), self.dispatch_header());
        out.insert(format!("{API_DIR}/src/dispatch.cpp"), self.dispatch_source());
        out.insert(C_METHODS_HEADER.to_owned(), self.c_methods_header());
        Ok(out)
    }
}

fn handler_method_name(method: &Method) -> String {
    let name = snake(&method.name);
    if is_call(method) || name == "start" { name } else { format!("start_{name}") }
}

fn constant(s: &Service, m: &Method) -> String {
    format!("k{}{}", s.name, m.name)
}
