// Generated by protoc-gen-reboot-cpp. Do not edit.
#include "reboot/api/v1/dispatch.hpp"

#include <any>
#include <optional>
#include <span>
#include <type_traits>
#include <utility>

#include "messages.hpp"
#include "reboot/api/codec.hpp"
#include "reboot/api/decode_error.hpp"
#include "reboot/api/v1/backend.hpp"
#include "reboot/api/v1/browser.hpp"
#include "reboot/api/v1/catalog.hpp"
#include "reboot/api/v1/components.hpp"
#include "reboot/api/v1/engine.hpp"
#include "reboot/api/v1/guidance.hpp"
#include "reboot/api/v1/host.hpp"
#include "reboot/api/v1/identity.hpp"
#include "reboot/api/v1/install.hpp"
#include "reboot/api/v1/integration.hpp"
#include "reboot/api/v1/join.hpp"
#include "reboot/api/v1/library.hpp"
#include "reboot/api/v1/logs.hpp"
#include "reboot/api/v1/method_table.hpp"
#include "reboot/api/v1/play.hpp"
#include "reboot/api/v1/requests.hpp"
#include "reboot/api/v1/secrets.hpp"
#include "reboot/api/v1/sessions.hpp"
#include "reboot/api/v1/settings.hpp"
#include "reboot/api/v1/support.hpp"
#include "reboot/api/v1/updates.hpp"
#include "reboot/foundation/diag.hpp"

namespace reboot::api {
namespace {

::reboot::Diagnostic method_error(::reboot::MessageId message, u32 method_id) {
    return ::reboot::make_diag(::reboot::ErrorDomain::Api, message)
        .arg("method", method_id)
        .kind(::reboot::ErrorKind::InvalidInput);
}

template <class Handler, class Request, class Response>
::reboot::Result<Bytes> call(Handler& handler,
                             ::reboot::Result<Response> (Handler::*method)(const CallContext&, const Request&),
                             const CallContext& context, u32 method_id, std::span<const u8> bytes) {
    auto request = decode<Request>(bytes);
    if (!request) return std::unexpected(to_diagnostic(request.error(), method_id));
    ::reboot::Result<Response> response = (handler.*method)(context, *request);
    if (!response) return std::unexpected(std::move(response.error()));
    return encode(*response);
}

template <class Handler, class Request>
::reboot::Result<::reboot::OpHandle> start(
    Handler& handler,
    ::reboot::Result<::reboot::OpHandle> (Handler::*method)(const CallContext&, const Request&,
                                                          ::reboot::DisconnectPolicy),
    const CallContext& context, u32 method_id, std::span<const u8> bytes, ::reboot::DisconnectPolicy disconnect) {
    auto request = decode<Request>(bytes);
    if (!request) return std::unexpected(to_diagnostic(request.error(), method_id));
    return (handler.*method)(context, *request, disconnect);
}

template <class Response>
::reboot::Result<Bytes> encode_result(const std::any& value) {
    if (const auto* response = std::any_cast<Response>(&value)) return encode(*response);
    if constexpr (std::is_empty_v<Response>) {
        if (!value.has_value()) return encode(Response{});
    }
    return std::unexpected(::reboot::internal_bug("api.encode_op_result"));
}

}  // namespace

::reboot::Result<Bytes> dispatch_call(const Handlers& handlers, const CallContext& context, u32 method_id,
                                      std::span<const u8> request) {
    switch (method_id) {
        case kEngineStatus:
            return call(handlers.engine, &IEngineHandler::status, context, method_id, request);
        case kEngineInfo:
            return call(handlers.engine, &IEngineHandler::info, context, method_id, request);
        case kEngineDrain:
            return call(handlers.engine, &IEngineHandler::drain, context, method_id, request);
        case kEngineShutdown:
            return call(handlers.engine, &IEngineHandler::shutdown, context, method_id, request);
        case kEngineRestartWhenIdle:
            return call(handlers.engine, &IEngineHandler::restart_when_idle, context, method_id, request);
        case kEngineOperations:
            return call(handlers.engine, &IEngineHandler::operations, context, method_id, request);
        case kSettingsSnapshot:
            return call(handlers.settings, &ISettingsHandler::snapshot, context, method_id, request);
        case kSettingsPatch:
            return call(handlers.settings, &ISettingsHandler::patch, context, method_id, request);
        case kSettingsReset:
            return call(handlers.settings, &ISettingsHandler::reset, context, method_id, request);
        case kSettingsSearch:
            return call(handlers.settings, &ISettingsHandler::search, context, method_id, request);
        case kSettingsFrontendStateGet:
            return call(handlers.settings, &ISettingsHandler::frontend_state_get, context, method_id, request);
        case kSettingsFrontendStatePut:
            return call(handlers.settings, &ISettingsHandler::frontend_state_put, context, method_id, request);
        case kSettingsLanguages:
            return call(handlers.settings, &ISettingsHandler::languages, context, method_id, request);
        case kSettingsDescriptors:
            return call(handlers.settings, &ISettingsHandler::descriptors, context, method_id, request);
        case kSettingsConsoleKeys:
            return call(handlers.settings, &ISettingsHandler::console_keys, context, method_id, request);
        case kSettingsConsoleKeyFromNative:
            return call(handlers.settings, &ISettingsHandler::console_key_from_native, context, method_id, request);
        case kLibraryList:
            return call(handlers.library, &ILibraryHandler::list, context, method_id, request);
        case kLibraryGet:
            return call(handlers.library, &ILibraryHandler::get, context, method_id, request);
        case kLibrarySelect:
            return call(handlers.library, &ILibraryHandler::select, context, method_id, request);
        case kLibraryUpdate:
            return call(handlers.library, &ILibraryHandler::update, context, method_id, request);
        case kCatalogList:
            return call(handlers.catalog, &ICatalogHandler::list, context, method_id, request);
        case kSupportQuery:
            return call(handlers.support, &ISupportHandler::query, context, method_id, request);
        case kComponentsList:
            return call(handlers.components, &IComponentsHandler::list, context, method_id, request);
        case kIdentityGet:
            return call(handlers.identity, &IIdentityHandler::get, context, method_id, request);
        case kIdentitySetDisplayName:
            return call(handlers.identity, &IIdentityHandler::set_display_name, context, method_id, request);
        case kIdentityReset:
            return call(handlers.identity, &IIdentityHandler::reset, context, method_id, request);
        case kSecretsState:
            return call(handlers.secrets, &ISecretsHandler::state, context, method_id, request);
        case kSecretsClear:
            return call(handlers.secrets, &ISecretsHandler::clear, context, method_id, request);
        case kPlayPlan:
            return call(handlers.play, &IPlayHandler::plan, context, method_id, request);
        case kHostProfilesList:
            return call(handlers.host, &IHostHandler::profiles_list, context, method_id, request);
        case kHostProfilesCreate:
            return call(handlers.host, &IHostHandler::profiles_create, context, method_id, request);
        case kHostProfilesUpdate:
            return call(handlers.host, &IHostHandler::profiles_update, context, method_id, request);
        case kHostProfilesDelete:
            return call(handlers.host, &IHostHandler::profiles_delete, context, method_id, request);
        case kHostShareLink:
            return call(handlers.host, &IHostHandler::share_link, context, method_id, request);
        case kHostCommand:
            return call(handlers.host, &IHostHandler::command, context, method_id, request);
        case kHostStatus:
            return call(handlers.host, &IHostHandler::status, context, method_id, request);
        case kHostCancelMatchEnd:
            return call(handlers.host, &IHostHandler::cancel_match_end, context, method_id, request);
        case kSessionsList:
            return call(handlers.sessions, &ISessionsHandler::list, context, method_id, request);
        case kSessionsGet:
            return call(handlers.sessions, &ISessionsHandler::get, context, method_id, request);
        case kSessionsSetLease:
            return call(handlers.sessions, &ISessionsHandler::set_lease, context, method_id, request);
        case kBackendStatus:
            return call(handlers.backend, &IBackendHandler::status, context, method_id, request);
        case kBackendDataDir:
            return call(handlers.backend, &IBackendHandler::data_dir, context, method_id, request);
        case kBackendSetTarget:
            return call(handlers.backend, &IBackendHandler::set_target, context, method_id, request);
        case kBackendAccountsList:
            return call(handlers.backend, &IBackendHandler::accounts_list, context, method_id, request);
        case kBrowserOpenView:
            return call(handlers.browser, &IBrowserHandler::open_view, context, method_id, request);
        case kBrowserUpdateView:
            return call(handlers.browser, &IBrowserHandler::update_view, context, method_id, request);
        case kBrowserCloseView:
            return call(handlers.browser, &IBrowserHandler::close_view, context, method_id, request);
        case kBrowserState:
            return call(handlers.browser, &IBrowserHandler::state, context, method_id, request);
        case kJoinParseAddress:
            return call(handlers.join, &IJoinHandler::parse_address, context, method_id, request);
        case kJoinTarget:
            return call(handlers.join, &IJoinHandler::target, context, method_id, request);
        case kJoinSetCustomTarget:
            return call(handlers.join, &IJoinHandler::set_custom_target, context, method_id, request);
        case kJoinClearTarget:
            return call(handlers.join, &IJoinHandler::clear_target, context, method_id, request);
        case kUpdatesStatus:
            return call(handlers.updates, &IUpdatesHandler::status, context, method_id, request);
        case kIntegrationStatus:
            return call(handlers.integration, &IIntegrationHandler::status, context, method_id, request);
        case kIntegrationPrerequisites:
            return call(handlers.integration, &IIntegrationHandler::prerequisites, context, method_id, request);
        case kIntegrationShellOpenUrl:
            return call(handlers.integration, &IIntegrationHandler::shell_open_url, context, method_id, request);
        case kIntegrationShellOpenPath:
            return call(handlers.integration, &IIntegrationHandler::shell_open_path, context, method_id, request);
        case kIntegrationShellReveal:
            return call(handlers.integration, &IIntegrationHandler::shell_reveal, context, method_id, request);
        case kGuidanceNoticesList:
            return call(handlers.guidance, &IGuidanceHandler::notices_list, context, method_id, request);
        case kGuidanceNoticesDismiss:
            return call(handlers.guidance, &IGuidanceHandler::notices_dismiss, context, method_id, request);
        case kGuidanceOnboardingState:
            return call(handlers.guidance, &IGuidanceHandler::onboarding_state, context, method_id, request);
        case kGuidanceOnboardingAdvance:
            return call(handlers.guidance, &IGuidanceHandler::onboarding_advance, context, method_id, request);
        case kGuidanceOnboardingSkip:
            return call(handlers.guidance, &IGuidanceHandler::onboarding_skip, context, method_id, request);
        case kGuidanceLinks:
            return call(handlers.guidance, &IGuidanceHandler::links, context, method_id, request);
        case kLogsRead:
            return call(handlers.logs, &ILogsHandler::read, context, method_id, request);
        case kRequestsPending:
            return call(handlers.requests, &IRequestsHandler::pending, context, method_id, request);
        case kRequestsRespond:
            return call(handlers.requests, &IRequestsHandler::respond, context, method_id, request);
        default:
            break;
    }
    const ::reboot::MessageId error = MethodTable::find(method_id) ? msg::kWrongMethodKind : msg::kUnknownMethod;
    return std::unexpected(method_error(error, method_id));
}

::reboot::Result<::reboot::OpHandle> dispatch_start(const Handlers& handlers, const CallContext& context,
                                                    u32 method_id, std::span<const u8> request,
                                                    std::optional<::reboot::DisconnectPolicy> disconnect) {
    const MethodSpec* spec = MethodTable::find(method_id);
    if (!spec) return std::unexpected(method_error(msg::kUnknownMethod, method_id));
    if (spec->kind != MethodKind::Operation) return std::unexpected(method_error(msg::kWrongMethodKind, method_id));
    const ::reboot::DisconnectPolicy policy = disconnect.value_or(spec->default_disconnect);
    switch (method_id) {
        case kLibraryRelocate:
            return start(handlers.library, &ILibraryHandler::start_relocate, context, method_id, request, policy);
        case kLibraryImport:
            return start(handlers.library, &ILibraryHandler::start_import, context, method_id, request, policy);
        case kLibraryRemove:
            return start(handlers.library, &ILibraryHandler::start_remove, context, method_id, request, policy);
        case kCatalogRefresh:
            return start(handlers.catalog, &ICatalogHandler::start_refresh, context, method_id, request, policy);
        case kInstallSuggestDestination:
            return start(handlers.install, &IInstallHandler::start_suggest_destination, context, method_id, request, policy);
        case kInstallInstall:
            return start(handlers.install, &IInstallHandler::start_install, context, method_id, request, policy);
        case kInstallDiscardStaging:
            return start(handlers.install, &IInstallHandler::start_discard_staging, context, method_id, request, policy);
        case kInstallDeleteUnregistered:
            return start(handlers.install, &IInstallHandler::start_delete_unregistered, context, method_id, request, policy);
        case kComponentsEnsure:
            return start(handlers.components, &IComponentsHandler::start_ensure, context, method_id, request, policy);
        case kComponentsRemove:
            return start(handlers.components, &IComponentsHandler::start_remove, context, method_id, request, policy);
        case kComponentsRuntimeSetup:
            return start(handlers.components, &IComponentsHandler::start_runtime_setup, context, method_id, request, policy);
        case kPlayStart:
            return start(handlers.play, &IPlayHandler::start, context, method_id, request, policy);
        case kHostStart:
            return start(handlers.host, &IHostHandler::start, context, method_id, request, policy);
        case kHostIdentityExport:
            return start(handlers.host, &IHostHandler::start_identity_export, context, method_id, request, policy);
        case kHostIdentityImport:
            return start(handlers.host, &IHostHandler::start_identity_import, context, method_id, request, policy);
        case kSessionsStop:
            return start(handlers.sessions, &ISessionsHandler::start_stop, context, method_id, request, policy);
        case kBackendStart:
            return start(handlers.backend, &IBackendHandler::start, context, method_id, request, policy);
        case kBackendStop:
            return start(handlers.backend, &IBackendHandler::start_stop, context, method_id, request, policy);
        case kBackendAccountsReset:
            return start(handlers.backend, &IBackendHandler::start_accounts_reset, context, method_id, request, policy);
        case kBackendAccountsDelete:
            return start(handlers.backend, &IBackendHandler::start_accounts_delete, context, method_id, request, policy);
        case kBackendAccountsPrune:
            return start(handlers.backend, &IBackendHandler::start_accounts_prune, context, method_id, request, policy);
        case kBackendAccountsRename:
            return start(handlers.backend, &IBackendHandler::start_accounts_rename, context, method_id, request, policy);
        case kBrowserResolve:
            return start(handlers.browser, &IBrowserHandler::start_resolve, context, method_id, request, policy);
        case kJoinResolveLink:
            return start(handlers.join, &IJoinHandler::start_resolve_link, context, method_id, request, policy);
        case kJoinGrant:
            return start(handlers.join, &IJoinHandler::start_grant, context, method_id, request, policy);
        case kUpdatesCheck:
            return start(handlers.updates, &IUpdatesHandler::start_check, context, method_id, request, policy);
        case kUpdatesApply:
            return start(handlers.updates, &IUpdatesHandler::start_apply, context, method_id, request, policy);
        case kIntegrationApply:
            return start(handlers.integration, &IIntegrationHandler::start_apply, context, method_id, request, policy);
        case kIntegrationRemove:
            return start(handlers.integration, &IIntegrationHandler::start_remove, context, method_id, request, policy);
        case kIntegrationRemediate:
            return start(handlers.integration, &IIntegrationHandler::start_remediate, context, method_id, request, policy);
        case kIntegrationPurge:
            return start(handlers.integration, &IIntegrationHandler::start_purge, context, method_id, request, policy);
        case kLogsExport:
            return start(handlers.logs, &ILogsHandler::start_export, context, method_id, request, policy);
        default:
            return std::unexpected(::reboot::internal_bug("api.dispatch_start"));
    }
}

::reboot::Result<Bytes> encode_op_result(u32 method_id, const std::any& value) {
    switch (method_id) {
        case kLibraryRelocate:
            return encode_result<LibraryRelocateResponse>(value);
        case kLibraryImport:
            return encode_result<LibraryImportResponse>(value);
        case kLibraryRemove:
            return encode_result<LibraryRemoveResponse>(value);
        case kCatalogRefresh:
            return encode_result<CatalogRefreshResponse>(value);
        case kInstallSuggestDestination:
            return encode_result<InstallSuggestDestinationResponse>(value);
        case kInstallInstall:
            return encode_result<InstallInstallResponse>(value);
        case kInstallDiscardStaging:
            return encode_result<InstallDiscardStagingResponse>(value);
        case kInstallDeleteUnregistered:
            return encode_result<InstallDeleteUnregisteredResponse>(value);
        case kComponentsEnsure:
            return encode_result<ComponentsEnsureResponse>(value);
        case kComponentsRemove:
            return encode_result<ComponentsRemoveResponse>(value);
        case kComponentsRuntimeSetup:
            return encode_result<ComponentsRuntimeSetupResponse>(value);
        case kPlayStart:
            return encode_result<PlayStartResponse>(value);
        case kHostStart:
            return encode_result<HostStartResponse>(value);
        case kHostIdentityExport:
            return encode_result<HostIdentityExportResponse>(value);
        case kHostIdentityImport:
            return encode_result<HostIdentityImportResponse>(value);
        case kSessionsStop:
            return encode_result<SessionsStopResponse>(value);
        case kBackendStart:
            return encode_result<BackendStartResponse>(value);
        case kBackendStop:
            return encode_result<BackendStopResponse>(value);
        case kBackendAccountsReset:
            return encode_result<BackendAccountsResetResponse>(value);
        case kBackendAccountsDelete:
            return encode_result<BackendAccountsDeleteResponse>(value);
        case kBackendAccountsPrune:
            return encode_result<BackendAccountsPruneResponse>(value);
        case kBackendAccountsRename:
            return encode_result<BackendAccountsRenameResponse>(value);
        case kBrowserResolve:
            return encode_result<BrowserResolveResponse>(value);
        case kJoinResolveLink:
            return encode_result<JoinResolveLinkResponse>(value);
        case kJoinGrant:
            return encode_result<JoinGrantResponse>(value);
        case kUpdatesCheck:
            return encode_result<UpdatesCheckResponse>(value);
        case kUpdatesApply:
            return encode_result<UpdatesApplyResponse>(value);
        case kIntegrationApply:
            return encode_result<IntegrationApplyResponse>(value);
        case kIntegrationRemove:
            return encode_result<IntegrationRemoveResponse>(value);
        case kIntegrationRemediate:
            return encode_result<IntegrationRemediateResponse>(value);
        case kIntegrationPurge:
            return encode_result<IntegrationPurgeResponse>(value);
        case kLogsExport:
            return encode_result<LogsExportResponse>(value);
        default:
            return std::unexpected(::reboot::internal_bug("api.encode_op_result"));
    }
}

}  // namespace reboot::api
