/* Generated by protoc-gen-reboot-cpp. Do not edit. */
#pragma once

/* reboot.api.v1 method ids for rb_call (call) and rb_start (operation). Each request and response
 * is the named reboot.api.v1 message; an operation's outcome carries its response. */

/* The schema these ids and their messages come from; a facade compares it with
 * EngineInfoResponse.schema_fingerprint. */
#define RB_SCHEMA_FINGERPRINT "5c1fb4d99550f274"

/* engine.status: call; EngineStatusRequest -> EngineStatusResponse */
#define RB_METHOD_ENGINE_STATUS 0x00010001u
/* engine.info: call; EngineInfoRequest -> EngineInfoResponse */
#define RB_METHOD_ENGINE_INFO 0x00010002u
/* engine.drain: call; EngineDrainRequest -> EngineDrainResponse */
#define RB_METHOD_ENGINE_DRAIN 0x00010003u
/* engine.shutdown: call; EngineShutdownRequest -> EngineShutdownResponse */
#define RB_METHOD_ENGINE_SHUTDOWN 0x00010004u
/* engine.restart_when_idle: call; EngineRestartWhenIdleRequest -> EngineRestartWhenIdleResponse */
#define RB_METHOD_ENGINE_RESTART_WHEN_IDLE 0x00010005u
/* engine.operations: call; EngineOperationsRequest -> EngineOperationsResponse */
#define RB_METHOD_ENGINE_OPERATIONS 0x00010006u
/* settings.snapshot: call; SettingsSnapshotRequest -> SettingsSnapshotResponse */
#define RB_METHOD_SETTINGS_SNAPSHOT 0x00020001u
/* settings.patch: call; SettingsPatchRequest -> SettingsPatchResponse */
#define RB_METHOD_SETTINGS_PATCH 0x00020002u
/* settings.reset: call; SettingsResetRequest -> SettingsResetResponse */
#define RB_METHOD_SETTINGS_RESET 0x00020003u
/* settings.search: call; SettingsSearchRequest -> SettingsSearchResponse */
#define RB_METHOD_SETTINGS_SEARCH 0x00020004u
/* settings.frontend_state_get: call; SettingsFrontendStateGetRequest -> SettingsFrontendStateGetResponse */
#define RB_METHOD_SETTINGS_FRONTEND_STATE_GET 0x00020005u
/* settings.frontend_state_put: call; SettingsFrontendStatePutRequest -> SettingsFrontendStatePutResponse */
#define RB_METHOD_SETTINGS_FRONTEND_STATE_PUT 0x00020006u
/* settings.languages: call; SettingsLanguagesRequest -> SettingsLanguagesResponse */
#define RB_METHOD_SETTINGS_LANGUAGES 0x00020007u
/* settings.descriptors: call; SettingsDescriptorsRequest -> SettingsDescriptorsResponse */
#define RB_METHOD_SETTINGS_DESCRIPTORS 0x00020008u
/* settings.console_keys: call; SettingsConsoleKeysRequest -> SettingsConsoleKeysResponse */
#define RB_METHOD_SETTINGS_CONSOLE_KEYS 0x00020009u
/* settings.console_key_from_native: call; SettingsConsoleKeyFromNativeRequest -> SettingsConsoleKeyFromNativeResponse */
#define RB_METHOD_SETTINGS_CONSOLE_KEY_FROM_NATIVE 0x0002000au
/* library.list: call; LibraryListRequest -> LibraryListResponse */
#define RB_METHOD_LIBRARY_LIST 0x00030001u
/* library.get: call; LibraryGetRequest -> LibraryGetResponse */
#define RB_METHOD_LIBRARY_GET 0x00030002u
/* library.select: call; LibrarySelectRequest -> LibrarySelectResponse */
#define RB_METHOD_LIBRARY_SELECT 0x00030003u
/* library.update: call; LibraryUpdateRequest -> LibraryUpdateResponse */
#define RB_METHOD_LIBRARY_UPDATE 0x00030004u
/* library.relocate: operation (bound); LibraryRelocateRequest -> LibraryRelocateResponse */
#define RB_METHOD_LIBRARY_RELOCATE 0x00030005u
/* library.import: operation (bound); LibraryImportRequest -> LibraryImportResponse */
#define RB_METHOD_LIBRARY_IMPORT 0x00030006u
/* library.remove: operation (bound); LibraryRemoveRequest -> LibraryRemoveResponse */
#define RB_METHOD_LIBRARY_REMOVE 0x00030007u
/* catalog.list: call; CatalogListRequest -> CatalogListResponse */
#define RB_METHOD_CATALOG_LIST 0x00040001u
/* catalog.refresh: operation (bound); CatalogRefreshRequest -> CatalogRefreshResponse */
#define RB_METHOD_CATALOG_REFRESH 0x00040002u
/* install.suggest_destination: operation (bound); InstallSuggestDestinationRequest -> InstallSuggestDestinationResponse */
#define RB_METHOD_INSTALL_SUGGEST_DESTINATION 0x00050001u
/* install.install: operation (detached); InstallInstallRequest -> InstallInstallResponse */
#define RB_METHOD_INSTALL_INSTALL 0x00050002u
/* install.discard_staging: operation (bound); InstallDiscardStagingRequest -> InstallDiscardStagingResponse */
#define RB_METHOD_INSTALL_DISCARD_STAGING 0x00050003u
/* install.delete_unregistered: operation (bound); InstallDeleteUnregisteredRequest -> InstallDeleteUnregisteredResponse */
#define RB_METHOD_INSTALL_DELETE_UNREGISTERED 0x00050004u
/* support.query: call; SupportQueryRequest -> SupportQueryResponse */
#define RB_METHOD_SUPPORT_QUERY 0x00060001u
/* components.list: call; ComponentsListRequest -> ComponentsListResponse */
#define RB_METHOD_COMPONENTS_LIST 0x00070001u
/* components.ensure: operation (detached); ComponentsEnsureRequest -> ComponentsEnsureResponse */
#define RB_METHOD_COMPONENTS_ENSURE 0x00070002u
/* components.remove: operation (bound); ComponentsRemoveRequest -> ComponentsRemoveResponse */
#define RB_METHOD_COMPONENTS_REMOVE 0x00070003u
/* components.runtime_setup: operation (detached); ComponentsRuntimeSetupRequest -> ComponentsRuntimeSetupResponse */
#define RB_METHOD_COMPONENTS_RUNTIME_SETUP 0x00070004u
/* identity.get: call; IdentityGetRequest -> IdentityGetResponse */
#define RB_METHOD_IDENTITY_GET 0x00080001u
/* identity.set_display_name: call; IdentitySetDisplayNameRequest -> IdentitySetDisplayNameResponse */
#define RB_METHOD_IDENTITY_SET_DISPLAY_NAME 0x00080002u
/* identity.reset: call; IdentityResetRequest -> IdentityResetResponse */
#define RB_METHOD_IDENTITY_RESET 0x00080003u
/* secrets.state: call; SecretsStateRequest -> SecretsStateResponse */
#define RB_METHOD_SECRETS_STATE 0x00090001u
/* secrets.clear: call; SecretsClearRequest -> SecretsClearResponse */
#define RB_METHOD_SECRETS_CLEAR 0x00090002u
/* play.plan: call; PlayPlanRequest -> PlayPlanResponse */
#define RB_METHOD_PLAY_PLAN 0x000a0001u
/* play.start: operation (detached); PlayStartRequest -> PlayStartResponse */
#define RB_METHOD_PLAY_START 0x000a0002u
/* host.profiles_list: call; HostProfilesListRequest -> HostProfilesListResponse */
#define RB_METHOD_HOST_PROFILES_LIST 0x000b0001u
/* host.profiles_create: call; HostProfilesCreateRequest -> HostProfilesCreateResponse */
#define RB_METHOD_HOST_PROFILES_CREATE 0x000b0002u
/* host.profiles_update: call; HostProfilesUpdateRequest -> HostProfilesUpdateResponse */
#define RB_METHOD_HOST_PROFILES_UPDATE 0x000b0003u
/* host.profiles_delete: call; HostProfilesDeleteRequest -> HostProfilesDeleteResponse */
#define RB_METHOD_HOST_PROFILES_DELETE 0x000b0004u
/* host.share_link: call; HostShareLinkRequest -> HostShareLinkResponse */
#define RB_METHOD_HOST_SHARE_LINK 0x000b0005u
/* host.command: call; HostCommandRequest -> HostCommandResponse */
#define RB_METHOD_HOST_COMMAND 0x000b0006u
/* host.start: operation (detached); HostStartRequest -> HostStartResponse */
#define RB_METHOD_HOST_START 0x000b0007u
/* host.status: call; HostStatusRequest -> HostStatusResponse */
#define RB_METHOD_HOST_STATUS 0x000b0008u
/* host.cancel_match_end: call; HostCancelMatchEndRequest -> HostCancelMatchEndResponse */
#define RB_METHOD_HOST_CANCEL_MATCH_END 0x000b0009u
/* sessions.list: call; SessionsListRequest -> SessionsListResponse */
#define RB_METHOD_SESSIONS_LIST 0x000c0001u
/* sessions.get: call; SessionsGetRequest -> SessionsGetResponse */
#define RB_METHOD_SESSIONS_GET 0x000c0002u
/* sessions.set_lease: call; SessionsSetLeaseRequest -> SessionsSetLeaseResponse */
#define RB_METHOD_SESSIONS_SET_LEASE 0x000c0003u
/* sessions.stop: operation (bound); SessionsStopRequest -> SessionsStopResponse */
#define RB_METHOD_SESSIONS_STOP 0x000c0004u
/* backend.status: call; BackendStatusRequest -> BackendStatusResponse */
#define RB_METHOD_BACKEND_STATUS 0x000d0001u
/* backend.data_dir: call; BackendDataDirRequest -> BackendDataDirResponse */
#define RB_METHOD_BACKEND_DATA_DIR 0x000d0002u
/* backend.set_target: call; BackendSetTargetRequest -> BackendSetTargetResponse */
#define RB_METHOD_BACKEND_SET_TARGET 0x000d0003u
/* backend.accounts_list: call; BackendAccountsListRequest -> BackendAccountsListResponse */
#define RB_METHOD_BACKEND_ACCOUNTS_LIST 0x000d0004u
/* backend.start: operation (bound); BackendStartRequest -> BackendStartResponse */
#define RB_METHOD_BACKEND_START 0x000d0005u
/* backend.stop: operation (bound); BackendStopRequest -> BackendStopResponse */
#define RB_METHOD_BACKEND_STOP 0x000d0006u
/* backend.accounts_reset: operation (bound); BackendAccountsResetRequest -> BackendAccountsResetResponse */
#define RB_METHOD_BACKEND_ACCOUNTS_RESET 0x000d0007u
/* backend.accounts_delete: operation (bound); BackendAccountsDeleteRequest -> BackendAccountsDeleteResponse */
#define RB_METHOD_BACKEND_ACCOUNTS_DELETE 0x000d0008u
/* backend.accounts_prune: operation (bound); BackendAccountsPruneRequest -> BackendAccountsPruneResponse */
#define RB_METHOD_BACKEND_ACCOUNTS_PRUNE 0x000d0009u
/* backend.accounts_rename: operation (bound); BackendAccountsRenameRequest -> BackendAccountsRenameResponse */
#define RB_METHOD_BACKEND_ACCOUNTS_RENAME 0x000d000au
/* browser.open_view: call; BrowserOpenViewRequest -> BrowserOpenViewResponse */
#define RB_METHOD_BROWSER_OPEN_VIEW 0x000e0001u
/* browser.update_view: call; BrowserUpdateViewRequest -> BrowserUpdateViewResponse */
#define RB_METHOD_BROWSER_UPDATE_VIEW 0x000e0002u
/* browser.close_view: call; BrowserCloseViewRequest -> BrowserCloseViewResponse */
#define RB_METHOD_BROWSER_CLOSE_VIEW 0x000e0003u
/* browser.state: call; BrowserStateRequest -> BrowserStateResponse */
#define RB_METHOD_BROWSER_STATE 0x000e0004u
/* browser.resolve: operation (bound); BrowserResolveRequest -> BrowserResolveResponse */
#define RB_METHOD_BROWSER_RESOLVE 0x000e0005u
/* join.parse_address: call; JoinParseAddressRequest -> JoinParseAddressResponse */
#define RB_METHOD_JOIN_PARSE_ADDRESS 0x000f0001u
/* join.target: call; JoinTargetRequest -> JoinTargetResponse */
#define RB_METHOD_JOIN_TARGET 0x000f0002u
/* join.set_custom_target: call; JoinSetCustomTargetRequest -> JoinSetCustomTargetResponse */
#define RB_METHOD_JOIN_SET_CUSTOM_TARGET 0x000f0003u
/* join.clear_target: call; JoinClearTargetRequest -> JoinClearTargetResponse */
#define RB_METHOD_JOIN_CLEAR_TARGET 0x000f0004u
/* join.resolve_link: operation (bound); JoinResolveLinkRequest -> JoinResolveLinkResponse */
#define RB_METHOD_JOIN_RESOLVE_LINK 0x000f0005u
/* join.grant: operation (bound); JoinGrantRequest -> JoinGrantResponse */
#define RB_METHOD_JOIN_GRANT 0x000f0006u
/* updates.status: call; UpdatesStatusRequest -> UpdatesStatusResponse */
#define RB_METHOD_UPDATES_STATUS 0x00100001u
/* updates.check: operation (bound); UpdatesCheckRequest -> UpdatesCheckResponse */
#define RB_METHOD_UPDATES_CHECK 0x00100002u
/* updates.apply: operation (detached); UpdatesApplyRequest -> UpdatesApplyResponse */
#define RB_METHOD_UPDATES_APPLY 0x00100003u
/* integration.status: call; IntegrationStatusRequest -> IntegrationStatusResponse */
#define RB_METHOD_INTEGRATION_STATUS 0x00120001u
/* integration.prerequisites: call; IntegrationPrerequisitesRequest -> IntegrationPrerequisitesResponse */
#define RB_METHOD_INTEGRATION_PREREQUISITES 0x00120002u
/* integration.shell_open_url: call; IntegrationShellOpenUrlRequest -> IntegrationShellOpenUrlResponse */
#define RB_METHOD_INTEGRATION_SHELL_OPEN_URL 0x00120003u
/* integration.shell_open_path: call; IntegrationShellOpenPathRequest -> IntegrationShellOpenPathResponse */
#define RB_METHOD_INTEGRATION_SHELL_OPEN_PATH 0x00120004u
/* integration.shell_reveal: call; IntegrationShellRevealRequest -> IntegrationShellRevealResponse */
#define RB_METHOD_INTEGRATION_SHELL_REVEAL 0x00120005u
/* integration.apply: operation (bound); IntegrationApplyRequest -> IntegrationApplyResponse */
#define RB_METHOD_INTEGRATION_APPLY 0x00120006u
/* integration.remove: operation (bound); IntegrationRemoveRequest -> IntegrationRemoveResponse */
#define RB_METHOD_INTEGRATION_REMOVE 0x00120007u
/* integration.remediate: operation (bound); IntegrationRemediateRequest -> IntegrationRemediateResponse */
#define RB_METHOD_INTEGRATION_REMEDIATE 0x00120008u
/* integration.purge: operation (bound); IntegrationPurgeRequest -> IntegrationPurgeResponse */
#define RB_METHOD_INTEGRATION_PURGE 0x00120009u
/* guidance.notices_list: call; GuidanceNoticesListRequest -> GuidanceNoticesListResponse */
#define RB_METHOD_GUIDANCE_NOTICES_LIST 0x00130001u
/* guidance.notices_dismiss: call; GuidanceNoticesDismissRequest -> GuidanceNoticesDismissResponse */
#define RB_METHOD_GUIDANCE_NOTICES_DISMISS 0x00130002u
/* guidance.onboarding_state: call; GuidanceOnboardingStateRequest -> GuidanceOnboardingStateResponse */
#define RB_METHOD_GUIDANCE_ONBOARDING_STATE 0x00130003u
/* guidance.onboarding_advance: call; GuidanceOnboardingAdvanceRequest -> GuidanceOnboardingAdvanceResponse */
#define RB_METHOD_GUIDANCE_ONBOARDING_ADVANCE 0x00130004u
/* guidance.onboarding_skip: call; GuidanceOnboardingSkipRequest -> GuidanceOnboardingSkipResponse */
#define RB_METHOD_GUIDANCE_ONBOARDING_SKIP 0x00130005u
/* guidance.links: call; GuidanceLinksRequest -> GuidanceLinksResponse */
#define RB_METHOD_GUIDANCE_LINKS 0x00130006u
/* logs.read: call; LogsReadRequest -> LogsReadResponse */
#define RB_METHOD_LOGS_READ 0x00140001u
/* logs.export: operation (bound); LogsExportRequest -> LogsExportResponse */
#define RB_METHOD_LOGS_EXPORT 0x00140002u
/* requests.pending: call; RequestsPendingRequest -> RequestsPendingResponse */
#define RB_METHOD_REQUESTS_PENDING 0x00150001u
/* requests.respond: call; RequestsRespondRequest -> RequestsRespondResponse */
#define RB_METHOD_REQUESTS_RESPOND 0x00150002u
