#pragma once

// Messages exchanged between shards, the replica and search workers.
//   shard  -> replica : ReplicaMsg over the replica's MPSC inbox
//   replica -> shards : RingEvent over the broadcast ring (mutations and ordered replies)
//   search -> shard   : ShardMsg over the shard's MPSC inbox

#include <memory>
#include <optional>
#include <variant>
#include <vector>

#include "core/mpsc.hpp"
#include "core/types.hpp"
#include "registry/model.hpp"
#include "wire/messages.hpp"

namespace sb::registry {

// ---- requests to the replica -----------------------------------------------------------------

struct SubscribeReq {
    u32 req_id = 0;
    u32 sub_id = 0;
    wire::ViewSpec spec;
    u32 window = 0;
    bool resync = false;  // existing subscription asking for a fresh snapshot; no new subscriber
};

struct UnsubscribeReq {
    u32 view_id = 0;
};

struct QueryReq {
    u32 req_id = 0;
    wire::ViewSpec spec;
    u32 limit = 0;
    wire::Bytes cursor;
};

struct ResolveReq {
    u32 req_id = 0;
    Uuid id;
};

struct JoinReq {
    u32 req_id = 0;
    Uuid id;
    std::optional<Digest> password_mac;  // HMAC(pepper, id || password), computed by the shard
};

struct HostRegisterReq {
    u32 req_id = 0;
    wire::HostRegister msg;  // password field cleared by the shard
    std::optional<Digest> password_mac;
    std::optional<Digest> presented_token_hash;  // sha256 of the token the host presented
    wire::Token new_token{};                     // pre-generated by the shard, used on first registration
    Digest new_token_hash{};
    IpAddr addr;
    wire::Region region{};
};

struct HostUpdateReq {
    u32 req_id = 0;
    u32 handle = 0;
    wire::HostUpdate msg;                               // password field cleared by the shard
    std::optional<std::optional<Digest>> password_mac;  // engaged: change; inner nullopt: remove
};

struct HostUnregisterReq {
    u32 req_id = 0;
    u32 handle = 0;
};

// Host connection closed or its heartbeat TTL expired. While the edge drains, hosts are expected
// to re-register elsewhere, so the entry stays online until the grace period ends.
struct HostGoneReq {
    u32 handle = 0;
    bool draining = false;
};

// Asks the replica to publish a drain marker: phase 0 = send GoAway, phase 1 = close connections.
struct DrainReq {
    u32 phase = 0;
};

struct ProbeResultReq {
    u32 handle = 0;
    bool reachable = false;
};

// Backbone deliveries (see backbone/backbone.hpp for the payload formats).
struct BackboneRecord {
    u64 stream_seq = 0;
    std::vector<u8> payload;  // encoded ReplicatedRecord; empty means tombstone
    Uuid id;
};

struct BackboneSoft {
    std::vector<u8> payload;  // encoded SoftUpdate
};

struct BackboneAck {
    u64 op = 0;
    bool ok = false;
    u64 stream_seq = 0;
};

struct BackboneEdgeDown {
    u64 edge_id = 0;
    bool reap = false;  // this edge was elected to tombstone the dead edge's entries
};

using ReplicaPayload =
    std::variant<SubscribeReq, UnsubscribeReq, QueryReq, ResolveReq, JoinReq, HostRegisterReq, HostUpdateReq,
                 HostUnregisterReq, HostGoneReq, ProbeResultReq, DrainReq, BackboneRecord, BackboneSoft, BackboneAck,
                 BackboneEdgeDown>;

struct ReplicaMsg : MpscNode {
    u16 shard = kNoShard;
    u64 conn = 0;
    ReplicaPayload payload;

    ReplicaMsg(u16 s, u64 c, ReplicaPayload p) : shard(s), conn(c), payload(std::move(p)) {}
};

// ---- replies to shards -----------------------------------------------------------------------

struct SubscribeReply {
    u32 req_id = 0;
    u32 sub_id = 0;
    u32 view_id = 0;
    u32 window = 0;
    u64 vseq = 0;
    bool resync = false;
    std::shared_ptr<const SnapshotBlob> snapshot;
};

struct JoinReply {
    u32 req_id = 0;
    Uuid id;
    IpAddr addr;
    u16 port = 0;
};

struct HostRegisteredReply {
    wire::HostRegistered msg;
    u32 handle = 0;
};

// The host connection no longer owns its entry (re-registered elsewhere or unregistered).
struct HostSupersededReply {};

using ReplyPayload = std::variant<SubscribeReply, wire::QueryResult, wire::ResolveResult, JoinReply,
                                  HostRegisteredReply, HostSupersededReply, wire::Ack, wire::Error, wire::HostStatus>;

struct ShardMsg : MpscNode {
    u8 node_kind = 0;  // 0: reply; other values are reserved for shard-internal messages
    u64 conn = 0;
    ReplyPayload payload;

    ShardMsg(u64 c, ReplyPayload p) : conn(c), payload(std::move(p)) {}
    virtual ~ShardMsg() = default;
};

// ---- the broadcast ring ----------------------------------------------------------------------

struct RingEvent {
    enum class Kind : u8 { mutation, reply, drain };
    Kind kind = Kind::mutation;

    // mutation
    u32 handle = kNoHandle;
    const PubEntry* pub = nullptr;  // new state; nullptr when the entry was removed
    bool text_changed = false;      // name, author or id changed (search reindex)
    std::vector<Frame*> frames;
    std::vector<const PubEntry*> retired;

    // reply (only the target shard acts on it); for drain events `conn` carries the phase
    u16 target = kNoShard;
    u64 conn = 0;
    std::optional<ReplyPayload> reply;
};

}  // namespace sb::registry
