// Generated by protoc-gen-reboot-cpp from reboot/api/v1/backend.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace reboot::api {

enum class BackendKind : u32 {
    // The bundled reboot-backend, supervised by the engine.
    Embedded = 0,
    Local = 1,
    Remote = 2,
};

enum class BackendState : u32 {
    Stopped = 0,
    Starting = 1,
    Running = 2,
    Stopping = 3,
    Restarting = 4,
    Failed = 5,
};

enum class AccountKind : u32 {
    Player = 0,
    Host = 1,
};

enum class RenameConflict : u32 {
    // Raise AccountRenameConflict.
    Ask = 0,
    KeepExisting = 1,
    Replace = 2,
};

enum class XmppUnavailableReason : u32 {
    // A LegacyFixed session under Wine: 127.0.0.1:80 is bound only on Windows, so the custom auth
    // DLL's XMPP has no server.
    ThirdPartyAuthDll = 0,
};

struct BackendTarget {
    BackendKind kind{};
    // The upstream URL for Local and Remote; empty for Embedded.
    std::string origin;

    bool operator==(const BackendTarget&) const = default;
};

struct BackendAccount {
    std::string account_id;
    std::string display_name;
    AccountKind kind{};
    u64 last_login_unix_ms = 0;

    bool operator==(const BackendAccount&) const = default;
};

struct BackendStatusRequest {
    bool operator==(const BackendStatusRequest&) const = default;
};

struct BackendStatusResponse {
    BackendTarget target;
    BackendState state{};
    // Kept running by the user, not only by sessions.
    bool pinned = false;
    u32 leases = 0;
    std::optional<u32> http_port;
    std::string version;
    bool allow_lan = false;
    std::optional<Diagnostic> last_error;

    bool operator==(const BackendStatusResponse&) const = default;
};

struct BackendDataDirRequest {
    bool operator==(const BackendDataDirRequest&) const = default;
};

struct BackendDataDirResponse {
    Path path;

    bool operator==(const BackendDataDirResponse&) const = default;
};

struct BackendSetTargetRequest {
    BackendTarget target;
    RunningPolicy running_policy{};

    bool operator==(const BackendSetTargetRequest&) const = default;
};

struct BackendSetTargetResponse {
    bool operator==(const BackendSetTargetResponse&) const = default;
};

struct BackendAccountsListRequest {
    bool operator==(const BackendAccountsListRequest&) const = default;
};

struct BackendAccountsListResponse {
    std::vector<BackendAccount> accounts;

    bool operator==(const BackendAccountsListResponse&) const = default;
};

struct BackendStartRequest {
    // Keep it running after the last session ends.
    bool pin = false;

    bool operator==(const BackendStartRequest&) const = default;
};

struct BackendStartResponse {
    u32 http_port = 0;

    bool operator==(const BackendStartResponse&) const = default;
};

struct BackendStopRequest {
    bool operator==(const BackendStopRequest&) const = default;
};

struct BackendStopResponse {
    bool operator==(const BackendStopResponse&) const = default;
};

struct BackendAccountsResetRequest {
    std::string account_id;

    bool operator==(const BackendAccountsResetRequest&) const = default;
};

struct BackendAccountsResetResponse {
    bool operator==(const BackendAccountsResetResponse&) const = default;
};

struct BackendAccountsDeleteRequest {
    std::string account_id;

    bool operator==(const BackendAccountsDeleteRequest&) const = default;
};

struct BackendAccountsDeleteResponse {
    bool operator==(const BackendAccountsDeleteResponse&) const = default;
};

struct BackendAccountsPruneRequest {
    // Accounts with no login for this many days.
    u32 older_than_days = 0;
    AccountKind kind{};

    bool operator==(const BackendAccountsPruneRequest&) const = default;
};

struct BackendAccountsPruneResponse {
    u32 removed = 0;

    bool operator==(const BackendAccountsPruneResponse&) const = default;
};

struct BackendAccountsRenameRequest {
    std::string account_id;
    std::string display_name;
    RenameConflict on_conflict{};

    bool operator==(const BackendAccountsRenameRequest&) const = default;
};

struct BackendAccountsRenameResponse {
    std::string account_id;

    bool operator==(const BackendAccountsRenameResponse&) const = default;
};

struct BackendStateChanged {
    BackendState state{};
    std::optional<u32> http_port;
    std::optional<Diagnostic> error;

    bool operator==(const BackendStateChanged&) const = default;
};

// After every account op and backend start that reloaded the list.
struct BackendAccountsChanged {
    std::vector<BackendAccount> accounts;

    bool operator==(const BackendAccountsChanged&) const = default;
};

struct XmppUnavailable {
    XmppUnavailableReason reason{};

    bool operator==(const XmppUnavailable&) const = default;
};

// The backend target, its process and its accounts.
class IBackendHandler {
public:
    virtual ~IBackendHandler() = default;

    virtual ::reboot::Result<BackendStatusResponse> status(const CallContext& context, const BackendStatusRequest& request) = 0;
    virtual ::reboot::Result<BackendDataDirResponse> data_dir(const CallContext& context, const BackendDataDirRequest& request) = 0;
    virtual ::reboot::Result<BackendSetTargetResponse> set_target(const CallContext& context, const BackendSetTargetRequest& request) = 0;
    virtual ::reboot::Result<BackendAccountsListResponse> accounts_list(const CallContext& context, const BackendAccountsListRequest& request) = 0;
    // Completes with BackendStartResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start(const CallContext& context, const BackendStartRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
    // Completes with BackendStopResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_stop(const CallContext& context, const BackendStopRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
    // Completes with BackendAccountsResetResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_accounts_reset(const CallContext& context, const BackendAccountsResetRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
    // Completes with BackendAccountsDeleteResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_accounts_delete(const CallContext& context, const BackendAccountsDeleteRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
    // Completes with BackendAccountsPruneResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_accounts_prune(const CallContext& context, const BackendAccountsPruneRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
    // Completes with BackendAccountsRenameResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_accounts_rename(const CallContext& context, const BackendAccountsRenameRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
};

}  // namespace reboot::api
