// Generated by protoc-gen-reboot-cpp from reboot/api/v1/browser.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

// Values match rbsb/1.
enum class Region : u32 {
    All = 0,
    Africa = 1,
    Antarctica = 2,
    Asia = 3,
    Europe = 4,
    NorthAmerica = 5,
    Oceania = 6,
    SouthAmerica = 7,
};

enum class PasswordFilter : u32 {
    Any = 0,
    Without = 1,
    Only = 2,
};

enum class ServerSort : u32 {
    Players = 0,
    Newest = 1,
    Name = 2,
};

enum class ConnectionState : u32 {
    Idle = 0,
    Connecting = 1,
    Connected = 2,
    Backoff = 3,
    Draining = 4,
    UdpBlocked = 5,
};

// Text fields come from strangers: sanitized, but render each one in its own isolated element.
struct ServerEntry {
    ServerId id;
    std::string name;
    std::string author;
    std::string description;
    std::string version;
    u32 bucket = 0;
    u32 players = 0;
    u32 max_players = 0;
    Region region{};
    bool has_password = false;
    bool reachable = false;
    bool online = false;
    u64 created_unix_ms = 0;
    // A library build whose version is in the entry's bucket.
    std::optional<BuildId> compatible_build;
    // Published by this user; joining it is refused.
    bool own = false;

    bool operator==(const ServerEntry&) const = default;
};

struct ViewSpec {
    // rbsb/1 bucket: 0 is every version, 1 is unparseable versions.
    u32 bucket = 0;
    PasswordFilter password{};
    Region region{};
    ServerSort sort{};
    // Rows kept live; the engine clamps it to the edge's limit.
    u32 window = 0;
    // Free-text search; empty lists everything.
    std::string text;

    bool operator==(const ViewSpec&) const = default;
};

struct BrowserOpenViewRequest {
    ViewSpec spec;

    bool operator==(const BrowserOpenViewRequest&) const = default;
};

struct BrowserOpenViewResponse {
    u64 view_id = 0;

    bool operator==(const BrowserOpenViewResponse&) const = default;
};

struct BrowserUpdateViewRequest {
    u64 view_id = 0;
    ViewSpec spec;

    bool operator==(const BrowserUpdateViewRequest&) const = default;
};

struct BrowserUpdateViewResponse {
    bool operator==(const BrowserUpdateViewResponse&) const = default;
};

struct BrowserCloseViewRequest {
    u64 view_id = 0;

    bool operator==(const BrowserCloseViewRequest&) const = default;
};

struct BrowserCloseViewResponse {
    bool operator==(const BrowserCloseViewResponse&) const = default;
};

struct BrowserStateRequest {
    bool operator==(const BrowserStateRequest&) const = default;
};

struct BrowserStateResponse {
    ConnectionState state{};
    std::vector<u64> open_views;
    std::optional<Diagnostic> error;

    bool operator==(const BrowserStateResponse&) const = default;
};

struct BrowserResolveRequest {
    ServerId server;

    bool operator==(const BrowserResolveRequest&) const = default;
};

struct BrowserResolveResponse {
    ServerEntry entry;
    // Unlisted: reachable only by id or link.
    bool hidden = false;

    bool operator==(const BrowserResolveResponse&) const = default;
};

struct BrowserConnectionChanged {
    ConnectionState state{};
    std::optional<u32> retry_in_ms;
    std::optional<Diagnostic> error;

    bool operator==(const BrowserConnectionChanged&) const = default;
};

struct ViewSnapshot {
    u64 view_id = 0;
    u32 total = 0;
    u32 offset = 0;
    std::vector<ServerEntry> rows;
    // The edge is unreachable; rows are the last known ones.
    bool stale = false;

    bool operator==(const ViewSnapshot&) const = default;
};

// Replaces the whole window, so a newer delta supersedes an older one.
struct ViewDelta {
    u64 view_id = 0;
    u32 total = 0;
    u32 offset = 0;
    std::vector<ServerEntry> rows;

    bool operator==(const ViewDelta&) const = default;
};

// Live server-browser views over rbsb/1.
class IBrowserHandler {
public:
    virtual ~IBrowserHandler() = default;

    virtual ::rb::Result<BrowserOpenViewResponse> open_view(const CallContext& context, const BrowserOpenViewRequest& request) = 0;
    virtual ::rb::Result<BrowserUpdateViewResponse> update_view(const CallContext& context, const BrowserUpdateViewRequest& request) = 0;
    virtual ::rb::Result<BrowserCloseViewResponse> close_view(const CallContext& context, const BrowserCloseViewRequest& request) = 0;
    virtual ::rb::Result<BrowserStateResponse> state(const CallContext& context, const BrowserStateRequest& request) = 0;
    // Completes with BrowserResolveResponse.
    virtual ::rb::Result<::rb::OpHandle> start_resolve(const CallContext& context, const BrowserResolveRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
};

}  // namespace rb::api
