// Generated by protoc-gen-reboot-cpp from reboot/api/v1/catalog.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace reboot::api {

enum class CatalogEntryStatus : u32 {
    Available = 0,
    Unavailable = 1,
    Withdrawn = 2,
};

enum class CatalogSource : u32 {
    Remote = 0,
    Cache = 1,
    Bundled = 2,
};

struct CatalogEntry {
    // Stable, such as "12.41".
    std::string id;
    GameVersion version;
    std::optional<u32> changelist;
    std::string display_name;
    CatalogEntryStatus status{};
    std::optional<u64> archive_size;
    std::optional<u64> installed_size;
    // A library build was installed from this entry.
    bool installed = false;

    bool operator==(const CatalogEntry&) const = default;
};

struct CatalogListRequest {
    bool include_unavailable = false;
    // Matches the id and display name; empty matches everything.
    std::string text;

    bool operator==(const CatalogListRequest&) const = default;
};

struct CatalogListResponse {
    u64 serial = 0;
    u64 generated_unix_ms = 0;
    CatalogSource source{};
    // Past its expiry; still used until a refresh succeeds.
    bool expired = false;
    std::vector<CatalogEntry> entries;

    bool operator==(const CatalogListResponse&) const = default;
};

struct CatalogRefreshRequest {
    // Fetch even when the cached copy has not expired.
    bool force = false;

    bool operator==(const CatalogRefreshRequest&) const = default;
};

struct CatalogRefreshResponse {
    u64 serial = 0;
    CatalogSource source{};

    bool operator==(const CatalogRefreshResponse&) const = default;
};

struct CatalogChanged {
    u64 serial = 0;
    CatalogSource source{};

    bool operator==(const CatalogChanged&) const = default;
};

// The signed catalog of downloadable builds.
class ICatalogHandler {
public:
    virtual ~ICatalogHandler() = default;

    virtual ::reboot::Result<CatalogListResponse> list(const CallContext& context, const CatalogListRequest& request) = 0;
    // Completes with CatalogRefreshResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_refresh(const CallContext& context, const CatalogRefreshRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
};

}  // namespace reboot::api
