// Generated by protoc-gen-reboot-cpp from reboot/api/v1/common.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/codec.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

enum class GameRole : u32 {
    Client = 0,
    Host = 1,
};

// Mirrors ports::RunnerKind.
enum class RunnerKind : u32 {
    Native = 0,
    Umu = 1,
    Wine = 2,
    // The launcher-built Wine runtime on macOS.
    MacRuntime = 3,
};

// What a change does when it affects live sessions.
enum class RunningPolicy : u32 {
    Refuse = 0,
    StopSessions = 1,
};

enum class NetMode : u32 {
    PerSession = 0,
    // A custom auth DLL: the backend at 127.0.0.1:3551, plus :80 on Windows, one session at a time.
    LegacyFixed = 1,
};

// Mirrors the alternatives of reboot::Arg, in order.
enum class ArgKind : u32 {
    String = 0,
    Signed = 1,
    Unsigned = 2,
    Bool = 3,
    Millis = 4,
    Path = 5,
    SemVer = 6,
};

// Mirrors reboot::SystemError::Origin.
enum class OsErrorOrigin : u32 {
    Host = 0,
    GuestWindows = 1,
};

// Mirrors reboot::ErrorKind; drives the CLI exit code.
enum class ErrorKind : u32 {
    Generic = 0,
    InvalidInput = 1,
    NotFound = 2,
    Conflict = 3,
    EngineUnavailable = 4,
    Unsupported = 5,
    Cancelled = 6,
};

// Mirrors reboot::CancelReason.
enum class CancelReason : u32 {
    User = 0,
    Deadline = 1,
    Shutdown = 2,
    Disconnect = 3,
    Superseded = 4,
};

// Each value with a payload has the EventPayload member of the same name.
enum class EventKind : u32 {
    Unspecified = 0,
    // Events were lost; re-read state before trusting later ones.
    Resync = 1,
    ConnectionLost = 2,
    // The envelope's epoch tells whether earlier ops and sessions survived.
    Reconnected = 3,
    OpProgress = 4,
    OpCompleted = 5,
    EngineState = 6,
    SettingsChanged = 7,
    LibraryChanged = 8,
    CatalogChanged = 9,
    ComponentChanged = 10,
    IdentityChanged = 11,
    SessionStateChanged = 12,
    SessionSpawned = 13,
    SessionDegraded = 14,
    SessionEnded = 15,
    HostPhaseChanged = 16,
    HostListening = 17,
    ReachabilityChanged = 18,
    PortMappingChanged = 19,
    PublishStateChanged = 20,
    MatchEvent = 21,
    PlayerEvent = 22,
    BackendStateChanged = 23,
    XmppUnavailable = 24,
    BrowserConnectionChanged = 25,
    ViewSnapshot = 26,
    ViewDelta = 27,
    JoinTargetChanged = 28,
    UpdateAvailable = 29,
    UpdateStaged = 30,
    EngineUpdating = 31,
    UpdateFailed = 32,
    NoticeAdded = 33,
    LogLine = 34,
    UserActionRequired = 35,
    UserActionResolved = 36,
    // Any client started an op; Engine.operations lists the live ones.
    OpStarted = 37,
    HostProfilesChanged = 38,
    BackendAccountsChanged = 39,
    NoticeRemoved = 40,
    OnboardingChanged = 41,
    IntegrationChanged = 42,
    PrerequisitesChanged = 43,
    SecretStateChanged = 44,
    StorageModeChanged = 45,
};

struct SessionId {
    Uuid uuid;

    bool operator==(const SessionId&) const = default;
};

struct BuildId {
    Uuid uuid;

    bool operator==(const BuildId&) const = default;
};

struct HostProfileId {
    Uuid uuid;

    bool operator==(const HostProfileId&) const = default;
};

struct ServerId {
    Uuid uuid;

    bool operator==(const ServerId&) const = default;
};

// UTF-16LE on Windows and raw bytes elsewhere, so it round-trips; `display` is for messages only.
struct Path {
    std::string display;
    Bytes native;

    bool operator==(const Path&) const = default;
};

struct SemVer {
    u32 major = 0;
    u32 minor = 0;
    u32 patch = 0;
    std::string pre;

    bool operator==(const SemVer&) const = default;
};

// The changelist travels beside it, never inside it.
struct GameVersion {
    u32 major = 0;
    u32 minor = 0;
    std::optional<u32> patch;

    bool operator==(const GameVersion&) const = default;
};

struct DiagnosticArg {
    std::string name;
    ArgKind kind{};
    std::string value;

    bool operator==(const DiagnosticArg&) const = default;
};

// Layout-identical to contracts::common::WireDiagnostic, so reboot_client passes it through.
// UIs render `id` and `args` from their own message catalog.
struct Diagnostic {
    std::string id;
    std::vector<DiagnosticArg> args;
    // Literal text; never translated.
    std::optional<std::string> detail;
    OsErrorOrigin os_origin{};
    std::optional<i64> os_code;
    bool retryable = false;
    ErrorKind kind{};

    bool operator==(const Diagnostic&) const = default;
};

// The terminal state of an operation; rb_op_result returns it.
struct Outcome {
    u64 op_id = 0;
    u32 method_id = 0;
    // Exactly one of the following is set; none set is a case this build does not know.
    // The method's encoded response message.
    std::optional<Bytes> completed;
    std::optional<Diagnostic> failed;
    std::optional<CancelReason> cancelled;
    // The phase that ran out of time.
    std::optional<std::string> timed_out;

    bool operator==(const Outcome&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const Outcome& m) noexcept {
    if (auto error = one_case({m.completed.has_value(),
                               m.failed.has_value(),
                               m.cancelled.has_value(),
                               m.timed_out.has_value()}))
        return error;
    return std::nullopt;
}

struct EnvVar {
    std::string name;
    std::string value;

    bool operator==(const EnvVar&) const = default;
};

// Coalesced to 10 Hz per operation.
struct Progress {
    u64 op_id = 0;
    u32 method_id = 0;
    // A stable id such as "install.downloading"; UIs translate it.
    std::string phase;
    u64 done = 0;
    std::optional<u64> total;
    std::optional<u64> rate_per_s;
    std::optional<u32> eta_s;
    // Set while the operation waits on this UserActionRequired request.
    std::optional<u64> awaiting_request;

    bool operator==(const Progress&) const = default;
};

// rb_subscribe's filter.
struct EventFilter {
    // Empty matches every kind.
    std::vector<EventKind> kinds;
    std::optional<SessionId> session;
    std::optional<u64> op_id;

    bool operator==(const EventFilter&) const = default;
};

// Layout-identical to contracts::ipc::WireEvent; rb_events_next returns it.
struct Event {
    EventKind kind{};
    u64 epoch = 0;
    // Global within an epoch.
    u64 seq = 0;
    std::optional<Uuid> session;
    std::optional<u64> op_id;
    // An encoded EventPayload; empty for kinds without one.
    Bytes payload;

    bool operator==(const Event&) const = default;
};

}  // namespace rb::api
