// Generated by protoc-gen-reboot-cpp from reboot/api/v1/components.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

enum class ComponentKind : u32 {
    // Our client DLL set.
    Payload = 0,
    // A Wine or Proton runtime and what it needs, for play on macOS and Linux.
    Runtime = 1,
};

enum class ComponentState : u32 {
    Missing = 0,
    Installing = 1,
    Installed = 2,
    UpdateAvailable = 3,
    // Failed verification or was quarantined; `problem` says which.
    Broken = 4,
};

// Mirrors components::RemediationStep: what the UI offers for a quarantined file. No step adds a
// security-product exclusion.
enum class RemediationStep : u32 {
    RestoreFromQuarantine = 0,
    OpenSecurityCenter = 1,
    // The UI builds the command from ComponentProblem.file.
    CopyRestoreCommand = 2,
    ReportFalsePositive = 3,
    ExplainSmartAppControl = 4,
};

enum class RecoveryState : u32 {
    Refetching = 0,
    Recovered = 1,
    RefetchFailed = 2,
};

// A file that vanished or changed, usually quarantined by security software.
struct ComponentProblem {
    // Names the security product when one was found.
    Diagnostic reason;
    Path file;
    std::vector<RemediationStep> remediation;
    RecoveryState recovery{};
    std::optional<Diagnostic> refetch_error;

    bool operator==(const ComponentProblem&) const = default;
};

struct Component {
    std::string id;
    ComponentKind kind{};
    ComponentState state{};
    std::string version;
    std::optional<std::string> available_version;
    u64 size_bytes = 0;
    // Pinned by a live session.
    bool in_use = false;
    std::optional<ComponentProblem> problem;

    bool operator==(const Component&) const = default;
};

struct ComponentsListRequest {
    bool operator==(const ComponentsListRequest&) const = default;
};

struct ComponentsListResponse {
    std::vector<Component> components;

    bool operator==(const ComponentsListResponse&) const = default;
};

struct ComponentsEnsureRequest {
    std::string id;

    bool operator==(const ComponentsEnsureRequest&) const = default;
};

struct ComponentsEnsureResponse {
    Component component;

    bool operator==(const ComponentsEnsureResponse&) const = default;
};

struct ComponentsRemoveRequest {
    std::string id;

    bool operator==(const ComponentsRemoveRequest&) const = default;
};

struct ComponentsRemoveResponse {
    bool operator==(const ComponentsRemoveResponse&) const = default;
};

struct ComponentsRuntimeSetupRequest {
    RunnerKind runner{};

    bool operator==(const ComponentsRuntimeSetupRequest&) const = default;
};

struct ComponentsRuntimeSetupResponse {
    std::vector<Component> components;

    bool operator==(const ComponentsRuntimeSetupResponse&) const = default;
};

struct ComponentChanged {
    Component component;

    bool operator==(const ComponentChanged&) const = default;
};

// Downloadable payloads and play runtimes.
class IComponentsHandler {
public:
    virtual ~IComponentsHandler() = default;

    virtual ::rb::Result<ComponentsListResponse> list(const CallContext& context, const ComponentsListRequest& request) = 0;
    // Completes with ComponentsEnsureResponse.
    virtual ::rb::Result<::rb::OpHandle> start_ensure(const CallContext& context, const ComponentsEnsureRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
    // Completes with ComponentsRemoveResponse.
    virtual ::rb::Result<::rb::OpHandle> start_remove(const CallContext& context, const ComponentsRemoveRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
    // Completes with ComponentsRuntimeSetupResponse.
    virtual ::rb::Result<::rb::OpHandle> start_runtime_setup(const CallContext& context, const ComponentsRuntimeSetupRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
};

}  // namespace rb::api
