// Generated by protoc-gen-reboot-cpp. Do not edit.
#pragma once

#include <any>
#include <optional>
#include <span>

#include "reboot/api/call_context.hpp"
#include "reboot/api/codec.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

class IBackendHandler;
class IBrowserHandler;
class ICatalogHandler;
class IComponentsHandler;
class IEngineHandler;
class IGuidanceHandler;
class IHostHandler;
class IIdentityHandler;
class IInstallHandler;
class IIntegrationHandler;
class IJoinHandler;
class ILibraryHandler;
class ILogsHandler;
class IPlayHandler;
class IRequestsHandler;
class ISecretsHandler;
class ISessionsHandler;
class ISettingsHandler;
class ISupportHandler;
class IUpdatesHandler;

struct Handlers {
    IBackendHandler& backend;
    IBrowserHandler& browser;
    ICatalogHandler& catalog;
    IComponentsHandler& components;
    IEngineHandler& engine;
    IGuidanceHandler& guidance;
    IHostHandler& host;
    IIdentityHandler& identity;
    IInstallHandler& install;
    IIntegrationHandler& integration;
    IJoinHandler& join;
    ILibraryHandler& library;
    ILogsHandler& logs;
    IPlayHandler& play;
    IRequestsHandler& requests;
    ISecretsHandler& secrets;
    ISessionsHandler& sessions;
    ISettingsHandler& settings;
    ISupportHandler& support;
    IUpdatesHandler& updates;
};

// Decodes the request, runs the CALL method and encodes its response.
[[nodiscard]] ::rb::Result<Bytes> dispatch_call(const Handlers& handlers, const CallContext& context, u32 method_id, std::span<const u8> request);

// Decodes the request and starts the OPERATION; no `disconnect` means the method's default.
[[nodiscard]] ::rb::Result<::rb::OpHandle> dispatch_start(const Handlers& handlers, const CallContext& context, u32 method_id, std::span<const u8> request, std::optional<::rb::DisconnectPolicy> disconnect);

// Encodes the value an operation completed with: the method's response message, or an empty
// any (Operation<void>) when that message has no fields. Anything else is the engine's bug.
[[nodiscard]] ::rb::Result<Bytes> encode_op_result(u32 method_id, const std::any& value);

}  // namespace rb::api
