// Generated by protoc-gen-reboot-cpp from reboot/api/v1/engine.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/codec.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

enum class EngineOrigin : u32 {
    OnDemand = 0,
    ServiceManager = 1,
    Foreground = 2,
};

enum class EnginePhase : u32 {
    Running = 0,
    Draining = 1,
    ShuttingDown = 2,
    Updating = 3,
};

// Mirrors contracts::ipc::StorageMode.
enum class StorageMode : u32 {
    ReadWrite = 0,
    // A store has a newer schema than this build.
    ReadOnly = 1,
    InMemory = 2,
};

enum class HostOs : u32 {
    Windows = 0,
    Macos = 1,
    Linux = 2,
};

enum class DrainReason : u32 {
    Update = 0,
    UserStop = 1,
    Replace = 2,
};

enum class ShutdownWhen : u32 {
    Now = 0,
    Idle = 1,
};

// Frozen with the bootstrap subset: fields are only ever appended.
struct EngineStatusRequest {
    bool operator==(const EngineStatusRequest&) const = default;
};

// Frozen with the bootstrap subset.
struct EngineStatusResponse {
    std::string engine_build;
    u64 epoch = 0;
    u32 pid = 0;
    EngineOrigin origin{};
    EnginePhase phase{};
    u32 sessions = 0;
    u32 operations = 0;

    bool operator==(const EngineStatusResponse&) const = default;
};

struct EngineInfoRequest {
    bool operator==(const EngineInfoRequest&) const = default;
};

struct EngineInfoResponse {
    std::string engine_build;
    SemVer app_version;
    HostOs os{};
    std::string os_version;
    Path image_path;
    Path data_root;
    StorageMode storage_mode{};
    bool secrets_available = false;
    // The engine build's reboot.api.v1 fingerprint; a facade whose RB_SCHEMA_FINGERPRINT differs
    // decodes other payloads than the engine sends.
    std::string schema_fingerprint;

    bool operator==(const EngineInfoResponse&) const = default;
};

// Engine.operations lists every live op a client started, so another UI can attach and cancel it.
struct OperationSummary {
    u64 op_id = 0;
    u32 method_id = 0;
    // The encoded request message of `method_id`, such as which entry an install downloads.
    Bytes request;
    bool detached = false;
    std::optional<SessionId> session;
    u64 started_unix_ms = 0;
    // The last coalesced progress; absent before the first.
    std::optional<Progress> progress;

    bool operator==(const OperationSummary&) const = default;
};

// Not in the bootstrap subset: `request` only decodes with this build's schema.
struct EngineOperationsRequest {
    bool operator==(const EngineOperationsRequest&) const = default;
};

struct EngineOperationsResponse {
    std::vector<OperationSummary> operations;

    bool operator==(const EngineOperationsResponse&) const = default;
};

// Frozen with the bootstrap subset.
struct EngineDrainRequest {
    DrainReason reason{};

    bool operator==(const EngineDrainRequest&) const = default;
};

// Frozen with the bootstrap subset.
struct EngineDrainResponse {
    bool operator==(const EngineDrainResponse&) const = default;
};

// Frozen with the bootstrap subset.
struct EngineShutdownRequest {
    ShutdownWhen when{};

    bool operator==(const EngineShutdownRequest&) const = default;
};

// Frozen with the bootstrap subset.
struct EngineShutdownResponse {
    bool operator==(const EngineShutdownResponse&) const = default;
};

// Frozen with the bootstrap subset.
struct EngineRestartWhenIdleRequest {
    bool operator==(const EngineRestartWhenIdleRequest&) const = default;
};

// Frozen with the bootstrap subset.
struct EngineRestartWhenIdleResponse {
    bool operator==(const EngineRestartWhenIdleResponse&) const = default;
};

struct OpStarted {
    OperationSummary operation;

    bool operator==(const OpStarted&) const = default;
};

struct StorageModeChanged {
    // The store, such as "settings" or "host-profiles".
    std::string document;
    StorageMode mode{};
    // The write error while in memory.
    std::optional<Diagnostic> reason;

    bool operator==(const StorageModeChanged&) const = default;
};

struct EngineState {
    EnginePhase phase{};
    u32 sessions = 0;
    u32 operations = 0;

    bool operator==(const EngineState&) const = default;
};

// Engine lifetime and the frozen bootstrap calls.
class IEngineHandler {
public:
    virtual ~IEngineHandler() = default;

    virtual ::rb::Result<EngineStatusResponse> status(const CallContext& context, const EngineStatusRequest& request) = 0;
    virtual ::rb::Result<EngineInfoResponse> info(const CallContext& context, const EngineInfoRequest& request) = 0;
    virtual ::rb::Result<EngineDrainResponse> drain(const CallContext& context, const EngineDrainRequest& request) = 0;
    virtual ::rb::Result<EngineShutdownResponse> shutdown(const CallContext& context, const EngineShutdownRequest& request) = 0;
    virtual ::rb::Result<EngineRestartWhenIdleResponse> restart_when_idle(const CallContext& context, const EngineRestartWhenIdleRequest& request) = 0;
    virtual ::rb::Result<EngineOperationsResponse> operations(const CallContext& context, const EngineOperationsRequest& request) = 0;
};

}  // namespace rb::api
