// Generated by protoc-gen-reboot-cpp from reboot/api/v1/events.proto. Do not edit.
#pragma once

#include <optional>

#include "reboot/api/codec.hpp"
#include "reboot/api/v1/backend.hpp"
#include "reboot/api/v1/browser.hpp"
#include "reboot/api/v1/catalog.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/api/v1/components.hpp"
#include "reboot/api/v1/engine.hpp"
#include "reboot/api/v1/guidance.hpp"
#include "reboot/api/v1/host.hpp"
#include "reboot/api/v1/identity.hpp"
#include "reboot/api/v1/integration.hpp"
#include "reboot/api/v1/join.hpp"
#include "reboot/api/v1/library.hpp"
#include "reboot/api/v1/logs.hpp"
#include "reboot/api/v1/requests.hpp"
#include "reboot/api/v1/secrets.hpp"
#include "reboot/api/v1/sessions.hpp"
#include "reboot/api/v1/settings.hpp"
#include "reboot/api/v1/updates.hpp"

namespace reboot::api {

// Event.payload. Each member is named after its EventKind value; session and op ids live in the envelope.
struct EventPayload {
    // Exactly one of the following is set; none set is a case this build does not know.
    std::optional<Progress> op_progress;
    std::optional<Outcome> op_completed;
    std::optional<EngineState> engine_state;
    std::optional<SettingsChanged> settings_changed;
    std::optional<LibraryChanged> library_changed;
    std::optional<CatalogChanged> catalog_changed;
    std::optional<ComponentChanged> component_changed;
    std::optional<IdentityChanged> identity_changed;
    std::optional<SessionStateChanged> session_state_changed;
    std::optional<SessionSpawned> session_spawned;
    std::optional<SessionDegraded> session_degraded;
    std::optional<SessionEnded> session_ended;
    std::optional<HostPhaseChanged> host_phase_changed;
    std::optional<HostListening> host_listening;
    std::optional<ReachabilityChanged> reachability_changed;
    std::optional<PortMappingChanged> port_mapping_changed;
    std::optional<PublishStateChanged> publish_state_changed;
    std::optional<MatchEvent> match_event;
    std::optional<PlayerEvent> player_event;
    std::optional<BackendStateChanged> backend_state_changed;
    std::optional<XmppUnavailable> xmpp_unavailable;
    std::optional<BrowserConnectionChanged> browser_connection_changed;
    std::optional<ViewSnapshot> view_snapshot;
    std::optional<ViewDelta> view_delta;
    std::optional<JoinTargetChanged> join_target_changed;
    std::optional<UpdateAvailable> update_available;
    std::optional<UpdateStaged> update_staged;
    std::optional<EngineUpdating> engine_updating;
    std::optional<UpdateFailed> update_failed;
    std::optional<NoticeAdded> notice_added;
    std::optional<LogLine> log_line;
    std::optional<UserActionRequired> user_action_required;
    std::optional<UserActionResolved> user_action_resolved;
    std::optional<OpStarted> op_started;
    std::optional<HostProfilesChanged> host_profiles_changed;
    std::optional<BackendAccountsChanged> backend_accounts_changed;
    std::optional<NoticeRemoved> notice_removed;
    std::optional<OnboardingChanged> onboarding_changed;
    std::optional<IntegrationChanged> integration_changed;
    std::optional<PrerequisitesChanged> prerequisites_changed;
    std::optional<SecretStateChanged> secret_state_changed;
    std::optional<StorageModeChanged> storage_mode_changed;

    bool operator==(const EventPayload&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const EventPayload& m) noexcept {
    if (auto error = one_case({m.op_progress.has_value(),
                               m.op_completed.has_value(),
                               m.engine_state.has_value(),
                               m.settings_changed.has_value(),
                               m.library_changed.has_value(),
                               m.catalog_changed.has_value(),
                               m.component_changed.has_value(),
                               m.identity_changed.has_value(),
                               m.session_state_changed.has_value(),
                               m.session_spawned.has_value(),
                               m.session_degraded.has_value(),
                               m.session_ended.has_value(),
                               m.host_phase_changed.has_value(),
                               m.host_listening.has_value(),
                               m.reachability_changed.has_value(),
                               m.port_mapping_changed.has_value(),
                               m.publish_state_changed.has_value(),
                               m.match_event.has_value(),
                               m.player_event.has_value(),
                               m.backend_state_changed.has_value(),
                               m.xmpp_unavailable.has_value(),
                               m.browser_connection_changed.has_value(),
                               m.view_snapshot.has_value(),
                               m.view_delta.has_value(),
                               m.join_target_changed.has_value(),
                               m.update_available.has_value(),
                               m.update_staged.has_value(),
                               m.engine_updating.has_value(),
                               m.update_failed.has_value(),
                               m.notice_added.has_value(),
                               m.log_line.has_value(),
                               m.user_action_required.has_value(),
                               m.user_action_resolved.has_value(),
                               m.op_started.has_value(),
                               m.host_profiles_changed.has_value(),
                               m.backend_accounts_changed.has_value(),
                               m.notice_removed.has_value(),
                               m.onboarding_changed.has_value(),
                               m.integration_changed.has_value(),
                               m.prerequisites_changed.has_value(),
                               m.secret_state_changed.has_value(),
                               m.storage_mode_changed.has_value()}))
        return error;
    if (auto error = m.op_completed ? check_cases(*m.op_completed) : std::nullopt) return error;
    if (auto error = m.player_event ? check_cases(*m.player_event) : std::nullopt) return error;
    if (auto error = m.join_target_changed ? check_cases(*m.join_target_changed) : std::nullopt) return error;
    if (auto error = m.notice_added ? check_cases(*m.notice_added) : std::nullopt) return error;
    if (auto error = m.user_action_required ? check_cases(*m.user_action_required) : std::nullopt) return error;
    if (auto error = m.secret_state_changed ? check_cases(*m.secret_state_changed) : std::nullopt) return error;
    return std::nullopt;
}

// Unspecified only for a payload that failed check_cases.
[[nodiscard]] inline EventKind event_kind(const EventPayload& payload) noexcept {
    if (payload.op_progress) return EventKind::OpProgress;
    if (payload.op_completed) return EventKind::OpCompleted;
    if (payload.engine_state) return EventKind::EngineState;
    if (payload.settings_changed) return EventKind::SettingsChanged;
    if (payload.library_changed) return EventKind::LibraryChanged;
    if (payload.catalog_changed) return EventKind::CatalogChanged;
    if (payload.component_changed) return EventKind::ComponentChanged;
    if (payload.identity_changed) return EventKind::IdentityChanged;
    if (payload.session_state_changed) return EventKind::SessionStateChanged;
    if (payload.session_spawned) return EventKind::SessionSpawned;
    if (payload.session_degraded) return EventKind::SessionDegraded;
    if (payload.session_ended) return EventKind::SessionEnded;
    if (payload.host_phase_changed) return EventKind::HostPhaseChanged;
    if (payload.host_listening) return EventKind::HostListening;
    if (payload.reachability_changed) return EventKind::ReachabilityChanged;
    if (payload.port_mapping_changed) return EventKind::PortMappingChanged;
    if (payload.publish_state_changed) return EventKind::PublishStateChanged;
    if (payload.match_event) return EventKind::MatchEvent;
    if (payload.player_event) return EventKind::PlayerEvent;
    if (payload.backend_state_changed) return EventKind::BackendStateChanged;
    if (payload.xmpp_unavailable) return EventKind::XmppUnavailable;
    if (payload.browser_connection_changed) return EventKind::BrowserConnectionChanged;
    if (payload.view_snapshot) return EventKind::ViewSnapshot;
    if (payload.view_delta) return EventKind::ViewDelta;
    if (payload.join_target_changed) return EventKind::JoinTargetChanged;
    if (payload.update_available) return EventKind::UpdateAvailable;
    if (payload.update_staged) return EventKind::UpdateStaged;
    if (payload.engine_updating) return EventKind::EngineUpdating;
    if (payload.update_failed) return EventKind::UpdateFailed;
    if (payload.notice_added) return EventKind::NoticeAdded;
    if (payload.log_line) return EventKind::LogLine;
    if (payload.user_action_required) return EventKind::UserActionRequired;
    if (payload.user_action_resolved) return EventKind::UserActionResolved;
    if (payload.op_started) return EventKind::OpStarted;
    if (payload.host_profiles_changed) return EventKind::HostProfilesChanged;
    if (payload.backend_accounts_changed) return EventKind::BackendAccountsChanged;
    if (payload.notice_removed) return EventKind::NoticeRemoved;
    if (payload.onboarding_changed) return EventKind::OnboardingChanged;
    if (payload.integration_changed) return EventKind::IntegrationChanged;
    if (payload.prerequisites_changed) return EventKind::PrerequisitesChanged;
    if (payload.secret_state_changed) return EventKind::SecretStateChanged;
    if (payload.storage_mode_changed) return EventKind::StorageModeChanged;
    return EventKind::Unspecified;
}

// Whether Event.payload holds an EventPayload. False for a kind this build does not know;
// consumers skip such events, and those whose payload fails to decode.
[[nodiscard]] constexpr bool has_payload(EventKind kind) noexcept {
    switch (kind) {
        case EventKind::OpProgress:
        case EventKind::OpCompleted:
        case EventKind::EngineState:
        case EventKind::SettingsChanged:
        case EventKind::LibraryChanged:
        case EventKind::CatalogChanged:
        case EventKind::ComponentChanged:
        case EventKind::IdentityChanged:
        case EventKind::SessionStateChanged:
        case EventKind::SessionSpawned:
        case EventKind::SessionDegraded:
        case EventKind::SessionEnded:
        case EventKind::HostPhaseChanged:
        case EventKind::HostListening:
        case EventKind::ReachabilityChanged:
        case EventKind::PortMappingChanged:
        case EventKind::PublishStateChanged:
        case EventKind::MatchEvent:
        case EventKind::PlayerEvent:
        case EventKind::BackendStateChanged:
        case EventKind::XmppUnavailable:
        case EventKind::BrowserConnectionChanged:
        case EventKind::ViewSnapshot:
        case EventKind::ViewDelta:
        case EventKind::JoinTargetChanged:
        case EventKind::UpdateAvailable:
        case EventKind::UpdateStaged:
        case EventKind::EngineUpdating:
        case EventKind::UpdateFailed:
        case EventKind::NoticeAdded:
        case EventKind::LogLine:
        case EventKind::UserActionRequired:
        case EventKind::UserActionResolved:
        case EventKind::OpStarted:
        case EventKind::HostProfilesChanged:
        case EventKind::BackendAccountsChanged:
        case EventKind::NoticeRemoved:
        case EventKind::OnboardingChanged:
        case EventKind::IntegrationChanged:
        case EventKind::PrerequisitesChanged:
        case EventKind::SecretStateChanged:
        case EventKind::StorageModeChanged:
            return true;
        default:
            return false;
    }
}

}  // namespace reboot::api
