// Generated by protoc-gen-reboot-cpp from reboot/api/v1/guidance.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/codec.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

// Mirrors reboot::Severity.
enum class NoticeLevel : u32 {
    Info = 0,
    Warning = 1,
    Error = 2,
};

// A message id and its args, which UIs render from their own catalog.
struct MessageText {
    std::string id;
    std::vector<DiagnosticArg> args;

    bool operator==(const MessageText&) const = default;
};

struct NoticeKey {
    // Stable, such as "unlisted_live".
    std::string kind;
    // Set for a notice about one session.
    std::optional<SessionId> session;

    bool operator==(const NoticeKey&) const = default;
};

// Integration.remediate(prerequisite).
struct RemediatePrerequisiteAction {
    std::string prerequisite;

    bool operator==(const RemediatePrerequisiteAction&) const = default;
};

// Catalog.list, then Install.install.
struct InstallBuildAction {
    bool operator==(const InstallBuildAction&) const = default;
};

// Library.import.
struct ImportBuildAction {
    bool operator==(const ImportBuildAction&) const = default;
};

// Identity.set_display_name(role).
struct EditDisplayNameAction {
    GameRole role{};

    bool operator==(const EditDisplayNameAction&) const = default;
};

// Settings.patch of host.listing, then Host.profiles_update of the built-in default profile's listing.
struct SetDefaultHostListingAction {
    bool listed = false;

    bool operator==(const SetDefaultHostListingAction&) const = default;
};

// Host.profiles_update of `profile` with listing LISTED.
struct ListHostProfileAction {
    HostProfileId profile;

    bool operator==(const ListHostProfileAction&) const = default;
};

// Host.share_link(session), copied by the UI.
struct CopyShareLinkAction {
    SessionId session;

    bool operator==(const CopyShareLinkAction&) const = default;
};

// Integration.shell_open_url of the Guidance.links entry with this id.
struct OpenAppLinkAction {
    std::string link;

    bool operator==(const OpenAppLinkAction&) const = default;
};

// A button; the UI makes the calls its action names, the engine never does.
struct SuggestedAction {
    // The button's message id.
    std::string label;
    // Exactly one of the following is set; none set is a case this build does not know.
    std::optional<RemediatePrerequisiteAction> remediate_prerequisite;
    std::optional<InstallBuildAction> install_build;
    std::optional<ImportBuildAction> import_build;
    std::optional<EditDisplayNameAction> edit_display_name;
    std::optional<SetDefaultHostListingAction> set_default_host_listing;
    std::optional<ListHostProfileAction> list_host_profile;
    std::optional<CopyShareLinkAction> copy_share_link;
    std::optional<OpenAppLinkAction> open_app_link;

    bool operator==(const SuggestedAction&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const SuggestedAction& m) noexcept {
    if (auto error = one_case({m.remediate_prerequisite.has_value(),
                               m.install_build.has_value(),
                               m.import_build.has_value(),
                               m.edit_display_name.has_value(),
                               m.set_default_host_listing.has_value(),
                               m.list_host_profile.has_value(),
                               m.copy_share_link.has_value(),
                               m.open_app_link.has_value()}))
        return error;
    return std::nullopt;
}

// An info bar that stays until dismissed or until its condition ends.
struct Notice {
    NoticeKey key;
    NoticeLevel level{};
    MessageText title;
    MessageText body;
    std::vector<SuggestedAction> actions;
    u64 created_unix_ms = 0;
    bool dismissible = false;

    bool operator==(const Notice&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const Notice& m) noexcept {
    if (auto error = check_all_cases(m.actions)) return error;
    return std::nullopt;
}

struct OnboardingState {
    std::vector<std::string> steps;
    std::string current;
    bool finished = false;
    bool skipped = false;

    bool operator==(const OnboardingState&) const = default;
};

struct Link {
    // Stable, such as "bug_report" or "port_forwarding".
    std::string id;
    std::string url;

    bool operator==(const Link&) const = default;
};

struct GuidanceNoticesListRequest {
    bool operator==(const GuidanceNoticesListRequest&) const = default;
};

struct GuidanceNoticesListResponse {
    std::vector<Notice> notices;

    bool operator==(const GuidanceNoticesListResponse&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const GuidanceNoticesListResponse& m) noexcept {
    if (auto error = check_all_cases(m.notices)) return error;
    return std::nullopt;
}

struct GuidanceNoticesDismissRequest {
    NoticeKey key;

    bool operator==(const GuidanceNoticesDismissRequest&) const = default;
};

struct GuidanceNoticesDismissResponse {
    bool operator==(const GuidanceNoticesDismissResponse&) const = default;
};

struct GuidanceOnboardingStateRequest {
    bool operator==(const GuidanceOnboardingStateRequest&) const = default;
};

struct GuidanceOnboardingStateResponse {
    OnboardingState state;

    bool operator==(const GuidanceOnboardingStateResponse&) const = default;
};

struct GuidanceOnboardingAdvanceRequest {
    // The step the user finished; a stale step is refused.
    std::string step;
    // The answer for a step that asks one, such as the host listing choice.
    std::string choice;

    bool operator==(const GuidanceOnboardingAdvanceRequest&) const = default;
};

struct GuidanceOnboardingAdvanceResponse {
    OnboardingState state;
    // What the chosen choice asks the UI to do.
    std::optional<SuggestedAction> action;

    bool operator==(const GuidanceOnboardingAdvanceResponse&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const GuidanceOnboardingAdvanceResponse& m) noexcept {
    if (auto error = m.action ? check_cases(*m.action) : std::nullopt) return error;
    return std::nullopt;
}

struct GuidanceOnboardingSkipRequest {
    bool operator==(const GuidanceOnboardingSkipRequest&) const = default;
};

struct GuidanceOnboardingSkipResponse {
    OnboardingState state;

    bool operator==(const GuidanceOnboardingSkipResponse&) const = default;
};

struct GuidanceLinksRequest {
    bool operator==(const GuidanceLinksRequest&) const = default;
};

struct GuidanceLinksResponse {
    std::vector<Link> links;

    bool operator==(const GuidanceLinksResponse&) const = default;
};

struct NoticeAdded {
    Notice notice;

    bool operator==(const NoticeAdded&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const NoticeAdded& m) noexcept {
    if (auto error = check_cases(m.notice)) return error;
    return std::nullopt;
}

// Dismissed, or its condition ended.
struct NoticeRemoved {
    NoticeKey key;

    bool operator==(const NoticeRemoved&) const = default;
};

struct OnboardingChanged {
    OnboardingState state;

    bool operator==(const OnboardingChanged&) const = default;
};

// Notices, onboarding and help links.
class IGuidanceHandler {
public:
    virtual ~IGuidanceHandler() = default;

    virtual ::rb::Result<GuidanceNoticesListResponse> notices_list(const CallContext& context, const GuidanceNoticesListRequest& request) = 0;
    virtual ::rb::Result<GuidanceNoticesDismissResponse> notices_dismiss(const CallContext& context, const GuidanceNoticesDismissRequest& request) = 0;
    virtual ::rb::Result<GuidanceOnboardingStateResponse> onboarding_state(const CallContext& context, const GuidanceOnboardingStateRequest& request) = 0;
    virtual ::rb::Result<GuidanceOnboardingAdvanceResponse> onboarding_advance(const CallContext& context, const GuidanceOnboardingAdvanceRequest& request) = 0;
    virtual ::rb::Result<GuidanceOnboardingSkipResponse> onboarding_skip(const CallContext& context, const GuidanceOnboardingSkipRequest& request) = 0;
    virtual ::rb::Result<GuidanceLinksResponse> links(const CallContext& context, const GuidanceLinksRequest& request) = 0;
};

}  // namespace rb::api
