// Generated by protoc-gen-reboot-cpp from reboot/api/v1/host.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/codec.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace reboot::api {

enum class Listing : u32 {
    Unlisted = 0,
    Listed = 1,
};

enum class MatchEndAction : u32 {
    Restart = 0,
    Shutdown = 1,
    Nothing = 2,
};

enum class HostPhase : u32 {
    Preparing = 0,
    Spawning = 1,
    WaitingForListen = 2,
    WaitingForReadiness = 3,
    MappingPorts = 4,
    Publishing = 5,
    Live = 6,
    // Readiness timed out; running but not published.
    LiveUnpublished = 7,
    Restarting = 8,
    Draining = 9,
    Stopping = 10,
    Stopped = 11,
    Failed = 12,
};

enum class HostUpdatePolicy : u32 {
    // Drain, then update once the match ends or nobody is connected.
    AfterMatch = 0,
    // Keep running until the user stops the server.
    Manual = 1,
};

enum class HostProfileChange : u32 {
    Added = 0,
    Updated = 1,
    Removed = 2,
    // A Host reset rewrote every profile.
    Reset = 3,
};

enum class SocketRole : u32 {
    Game = 0,
    Beacon = 1,
};

enum class Reachability : u32 {
    Unknown = 0,
    AwaitingProbe = 1,
    Reachable = 2,
    Unreachable = 3,
};

enum class MappingProtocol : u32 {
    Unmapped = 0,
    Upnp = 1,
    NatPmp = 2,
};

enum class PublishState : u32 {
    Unpublished = 0,
    Registering = 1,
    Published = 2,
    Failed = 3,
};

enum class MatchState : u32 {
    Lobby = 0,
    Warmup = 1,
    InProgress = 2,
    Ending = 3,
    Ended = 4,
};

struct PortRange {
    u32 first = 0;
    u32 last = 0;

    bool operator==(const PortRange&) const = default;
};

// The block holds one port per socket the game server declares.
struct PortPolicy {
    // Exactly one of the following is set; none set is a case this build does not know.
    // The block starts here; a busy port fails the start.
    std::optional<u32> pinned;
    // The lowest free block inside the range.
    std::optional<PortRange> range;

    bool operator==(const PortPolicy&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const PortPolicy& m) noexcept {
    if (auto error = one_case({m.pinned.has_value(), m.range.has_value()})) return error;
    return std::nullopt;
}

struct StartPolicy {
    // Exactly one of the following is set; none set is a case this build does not know.
    std::optional<u32> auto_at_players;
    std::optional<bool> manual;

    bool operator==(const StartPolicy&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const StartPolicy& m) noexcept {
    if (auto error = one_case({m.auto_at_players.has_value(), m.manual.has_value()})) return error;
    return std::nullopt;
}

struct MatchEndPolicy {
    MatchEndAction action{};
    u32 delay_s = 0;

    bool operator==(const MatchEndPolicy&) const = default;
};

// At least one of address and account_id. Account ids are self-asserted, so a ban without an
// address is evadable.
struct Ban {
    // An IP address or CIDR block; bans match the address first.
    std::optional<std::string> address;
    std::optional<std::string> account_id;
    std::string reason;
    u64 created_unix_ms = 0;
    // Absent: permanent.
    std::optional<u64> expires_unix_ms;

    bool operator==(const Ban&) const = default;
};

// A game version to host without an installed build; our game server needs no game files.
struct HostVersion {
    GameVersion version;
    u32 changelist = 0;

    bool operator==(const HostVersion&) const = default;
};

// The password is a secret: rb_secret_put with HOST_JOIN_PASSWORD and the profile id.
struct HostProfile {
    HostProfileId id;
    // Refused with a conflict when stale on update.
    u64 revision = 0;
    std::string name;
    // Absent with `version`: the library's host selection.
    std::optional<BuildId> build;
    PortPolicy port;
    bool port_mapping = false;
    Listing listing{};
    std::string server_name;
    std::string description;
    bool has_password = false;
    u32 max_players = 0;
    std::string playlist;
    StartPolicy start;
    u32 tick_rate = 0;
    MatchEndPolicy match_end;
    std::vector<std::string> operator_cidrs;
    std::vector<Ban> bans;
    // The profile Play uses for a linked auto-server.
    bool auto_server = false;
    // Absent: the host.update_policy setting.
    std::optional<HostUpdatePolicy> update_policy;
    // Never set together with `build`.
    std::optional<HostVersion> version;

    bool operator==(const HostProfile&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const HostProfile& m) noexcept {
    if (auto error = check_cases(m.port)) return error;
    if (auto error = check_cases(m.start)) return error;
    return std::nullopt;
}

// Applies to one start only.
struct HostOverrides {
    std::optional<Listing> listing;
    std::optional<u32> port;
    std::optional<BuildId> build;

    bool operator==(const HostOverrides&) const = default;
};

struct StartMatch {
    u32 countdown_s = 0;

    bool operator==(const StartMatch&) const = default;
};

struct EndMatch {
    bool operator==(const EndMatch&) const = default;
};

struct ResetMatch {
    bool operator==(const ResetMatch&) const = default;
};

struct KickPlayer {
    // Player.player_id; account ids are self-asserted and may collide.
    u32 player_id = 0;
    std::string reason;

    bool operator==(const KickPlayer&) const = default;
};

struct SetBans {
    std::vector<Ban> bans;

    bool operator==(const SetBans&) const = default;
};

struct SetOperators {
    std::vector<std::string> cidrs;

    bool operator==(const SetOperators&) const = default;
};

struct ConsoleCommand {
    std::string text;

    bool operator==(const ConsoleCommand&) const = default;
};

struct OperatorCommand {
    // Exactly one of the following is set; none set is a case this build does not know.
    std::optional<StartMatch> start_match;
    std::optional<EndMatch> end_match;
    std::optional<ResetMatch> reset;
    std::optional<KickPlayer> kick;
    std::optional<SetBans> set_bans;
    std::optional<SetOperators> set_operators;
    std::optional<ConsoleCommand> console;

    bool operator==(const OperatorCommand&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const OperatorCommand& m) noexcept {
    if (auto error = one_case({m.start_match.has_value(),
                               m.end_match.has_value(),
                               m.reset.has_value(),
                               m.kick.has_value(),
                               m.set_bans.has_value(),
                               m.set_operators.has_value(),
                               m.console.has_value()}))
        return error;
    return std::nullopt;
}

struct BoundSocket {
    SocketRole role{};
    u32 port = 0;

    bool operator==(const BoundSocket&) const = default;
};

struct MappedPort {
    u32 internal = 0;
    u32 external = 0;

    bool operator==(const MappedPort&) const = default;
};

struct Placement {
    std::string account_id;
    u32 place = 0;

    bool operator==(const Placement&) const = default;
};

struct MatchResult {
    std::string reason;
    std::optional<std::string> winner;
    std::vector<Placement> placements;

    bool operator==(const MatchResult&) const = default;
};

// The account id is what the client claimed; the server does not verify it.
struct Player {
    std::string account_id;
    std::string display_name;
    std::string address;
    // The server's id for this connection; KickPlayer takes it.
    u32 player_id = 0;

    bool operator==(const Player&) const = default;
};

struct HostProfilesListRequest {
    bool operator==(const HostProfilesListRequest&) const = default;
};

struct HostProfilesListResponse {
    std::vector<HostProfile> profiles;

    bool operator==(const HostProfilesListResponse&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const HostProfilesListResponse& m) noexcept {
    if (auto error = check_all_cases(m.profiles)) return error;
    return std::nullopt;
}

struct HostProfilesCreateRequest {
    // id and revision are assigned by the engine.
    HostProfile profile;

    bool operator==(const HostProfilesCreateRequest&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const HostProfilesCreateRequest& m) noexcept {
    if (auto error = check_cases(m.profile)) return error;
    return std::nullopt;
}

struct HostProfilesCreateResponse {
    HostProfile profile;

    bool operator==(const HostProfilesCreateResponse&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const HostProfilesCreateResponse& m) noexcept {
    if (auto error = check_cases(m.profile)) return error;
    return std::nullopt;
}

struct HostProfilesUpdateRequest {
    HostProfile profile;

    bool operator==(const HostProfilesUpdateRequest&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const HostProfilesUpdateRequest& m) noexcept {
    if (auto error = check_cases(m.profile)) return error;
    return std::nullopt;
}

struct HostProfilesUpdateResponse {
    HostProfile profile;

    bool operator==(const HostProfilesUpdateResponse&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const HostProfilesUpdateResponse& m) noexcept {
    if (auto error = check_cases(m.profile)) return error;
    return std::nullopt;
}

struct HostProfilesDeleteRequest {
    HostProfileId id;

    bool operator==(const HostProfilesDeleteRequest&) const = default;
};

struct HostProfilesDeleteResponse {
    bool operator==(const HostProfilesDeleteResponse&) const = default;
};

struct HostShareLinkRequest {
    SessionId session;

    bool operator==(const HostShareLinkRequest&) const = default;
};

struct HostShareLinkResponse {
    std::string url;
    ServerId server;

    bool operator==(const HostShareLinkResponse&) const = default;
};

struct HostCommandRequest {
    SessionId session;
    OperatorCommand command;

    bool operator==(const HostCommandRequest&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const HostCommandRequest& m) noexcept {
    if (auto error = check_cases(m.command)) return error;
    return std::nullopt;
}

struct HostCommandResponse {
    bool operator==(const HostCommandResponse&) const = default;
};

struct HostStartRequest {
    HostProfileId profile;
    HostOverrides overrides;
    // The caller's environment at this launch, filtered as PlayRequest.environment is.
    std::vector<EnvVar> environment;
    // The running play session this server is for; set exactly with the auto profile, and the
    // server stops with that session.
    std::optional<SessionId> linked_to;

    bool operator==(const HostStartRequest&) const = default;
};

// Sent once the game server is listening; publication continues in the session.
struct HostStartResponse {
    SessionId session;

    bool operator==(const HostStartResponse&) const = default;
};

struct HostStatusRequest {
    SessionId session;

    bool operator==(const HostStatusRequest&) const = default;
};

struct HostPhaseChanged {
    HostPhase phase{};
    std::optional<Diagnostic> reason;

    bool operator==(const HostPhaseChanged&) const = default;
};

struct HostListening {
    std::vector<BoundSocket> sockets;

    bool operator==(const HostListening&) const = default;
};

struct ReachabilityChanged {
    Reachability reachability{};
    // As the server browser observed it.
    std::string public_address;

    bool operator==(const ReachabilityChanged&) const = default;
};

struct PortMappingChanged {
    MappingProtocol protocol{};
    std::vector<MappedPort> ports;
    u32 lease_s = 0;
    // Mapping failures never stop the host.
    std::optional<Diagnostic> error;

    bool operator==(const PortMappingChanged&) const = default;
};

struct PublishStateChanged {
    PublishState state{};
    std::optional<ServerId> server;
    bool hidden = false;
    std::optional<Diagnostic> error;

    bool operator==(const PublishStateChanged&) const = default;
};

struct MatchEvent {
    MatchState state{};
    std::optional<MatchResult> result;
    // Set while the match-end timer runs.
    std::optional<u64> restart_at_unix_ms;

    bool operator==(const MatchEvent&) const = default;
};

// Each member is the latest event of its kind, so a UI that attaches mid-session renders it as it
// renders those events.
struct HostStatus {
    HostPhaseChanged phase;
    // Absent before Listening and during a respawn.
    std::optional<HostListening> listening;
    ReachabilityChanged reachability;
    PortMappingChanged mapping;
    PublishStateChanged publish;
    MatchEvent match;
    std::vector<Player> players;

    bool operator==(const HostStatus&) const = default;
};

struct HostStatusResponse {
    HostStatus status;

    bool operator==(const HostStatusResponse&) const = default;
};

struct HostCancelMatchEndRequest {
    SessionId session;

    bool operator==(const HostCancelMatchEndRequest&) const = default;
};

struct HostCancelMatchEndResponse {
    // False when no match-end action was pending.
    bool cancelled = false;

    bool operator==(const HostCancelMatchEndResponse&) const = default;
};

// Moves a profile's rbsb identity, and so its server id and share link, to another PC or VPS.
struct HostIdentityExportRequest {
    HostProfileId profile;
    // A directory that does not exist yet; it is created readable by the owner only.
    Path destination;

    bool operator==(const HostIdentityExportRequest&) const = default;
};

struct HostIdentityExportResponse {
    bool operator==(const HostIdentityExportResponse&) const = default;
};

// Replaces the profile's identity with one an export wrote; refused while the profile is hosting.
struct HostIdentityImportRequest {
    HostProfileId profile;
    // The directory an export created.
    Path source;

    bool operator==(const HostIdentityImportRequest&) const = default;
};

struct HostIdentityImportResponse {
    ServerId server;

    bool operator==(const HostIdentityImportResponse&) const = default;
};

struct HostProfilesChanged {
    HostProfileChange change{};
    // Absent for RESET.
    std::optional<HostProfileId> profile;

    bool operator==(const HostProfilesChanged&) const = default;
};

struct PlayerEvent {
    // Exactly one of the following is set; none set is a case this build does not know.
    std::optional<Player> joined;
    std::optional<Player> left;
    u32 player_count = 0;

    bool operator==(const PlayerEvent&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const PlayerEvent& m) noexcept {
    if (auto error = one_case({m.joined.has_value(), m.left.has_value()})) return error;
    return std::nullopt;
}

// Host profiles and running our game server.
class IHostHandler {
public:
    virtual ~IHostHandler() = default;

    virtual ::reboot::Result<HostProfilesListResponse> profiles_list(const CallContext& context, const HostProfilesListRequest& request) = 0;
    virtual ::reboot::Result<HostProfilesCreateResponse> profiles_create(const CallContext& context, const HostProfilesCreateRequest& request) = 0;
    virtual ::reboot::Result<HostProfilesUpdateResponse> profiles_update(const CallContext& context, const HostProfilesUpdateRequest& request) = 0;
    virtual ::reboot::Result<HostProfilesDeleteResponse> profiles_delete(const CallContext& context, const HostProfilesDeleteRequest& request) = 0;
    virtual ::reboot::Result<HostShareLinkResponse> share_link(const CallContext& context, const HostShareLinkRequest& request) = 0;
    virtual ::reboot::Result<HostCommandResponse> command(const CallContext& context, const HostCommandRequest& request) = 0;
    // Completes with HostStartResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start(const CallContext& context, const HostStartRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
    virtual ::reboot::Result<HostStatusResponse> status(const CallContext& context, const HostStatusRequest& request) = 0;
    // Stops the pending match-end action and leaves the server running.
    virtual ::reboot::Result<HostCancelMatchEndResponse> cancel_match_end(const CallContext& context, const HostCancelMatchEndRequest& request) = 0;
    // Completes with HostIdentityExportResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_identity_export(const CallContext& context, const HostIdentityExportRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
    // Completes with HostIdentityImportResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_identity_import(const CallContext& context, const HostIdentityImportRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
};

}  // namespace reboot::api
