// Generated by protoc-gen-reboot-cpp from reboot/api/v1/identity.proto. Do not edit.
#pragma once

#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/result_fwd.hpp"

namespace reboot::api {

struct IdentityProfile {
    GameRole role{};
    std::string display_name;
    // What the game logs in as; derived from display_name and unique per role.
    std::string account_id;
    bool is_default = false;

    bool operator==(const IdentityProfile&) const = default;
};

struct IdentityGetRequest {
    bool operator==(const IdentityGetRequest&) const = default;
};

struct IdentityGetResponse {
    std::vector<IdentityProfile> profiles;

    bool operator==(const IdentityGetResponse&) const = default;
};

struct IdentitySetDisplayNameRequest {
    GameRole role{};
    std::string display_name;

    bool operator==(const IdentitySetDisplayNameRequest&) const = default;
};

struct IdentitySetDisplayNameResponse {
    IdentityProfile profile;

    bool operator==(const IdentitySetDisplayNameResponse&) const = default;
};

struct IdentityResetRequest {
    GameRole role{};

    bool operator==(const IdentityResetRequest&) const = default;
};

struct IdentityResetResponse {
    IdentityProfile profile;

    bool operator==(const IdentityResetResponse&) const = default;
};

struct IdentityChanged {
    IdentityProfile profile;

    bool operator==(const IdentityChanged&) const = default;
};

// Display names and account ids per role.
class IIdentityHandler {
public:
    virtual ~IIdentityHandler() = default;

    virtual ::reboot::Result<IdentityGetResponse> get(const CallContext& context, const IdentityGetRequest& request) = 0;
    virtual ::reboot::Result<IdentitySetDisplayNameResponse> set_display_name(const CallContext& context, const IdentitySetDisplayNameRequest& request) = 0;
    virtual ::reboot::Result<IdentityResetResponse> reset(const CallContext& context, const IdentityResetRequest& request) = 0;
};

}  // namespace reboot::api
