// Generated by protoc-gen-reboot-cpp from reboot/api/v1/install.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/api/v1/library.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace reboot::api {

struct Volume {
    Path root;
    std::string label;
    u64 free_bytes = 0;
    u64 total_bytes = 0;
    // Why the volume cannot hold the build; absent when it can.
    std::optional<Diagnostic> problem;

    bool operator==(const Volume&) const = default;
};

struct InstallSuggestDestinationRequest {
    std::string entry_id;

    bool operator==(const InstallSuggestDestinationRequest&) const = default;
};

struct InstallSuggestDestinationResponse {
    Path destination;
    std::string name;
    u64 required_bytes = 0;
    std::vector<Volume> volumes;

    bool operator==(const InstallSuggestDestinationResponse&) const = default;
};

struct InstallDiscardStagingRequest {
    // The destination of a cancelled or failed install.
    Path destination;

    bool operator==(const InstallDiscardStagingRequest&) const = default;
};

struct InstallDiscardStagingResponse {
    bool operator==(const InstallDiscardStagingResponse&) const = default;
};

struct InstallDeleteUnregisteredRequest {
    // A folder this engine run installed but could not add to the library.
    Path folder;

    bool operator==(const InstallDeleteUnregisteredRequest&) const = default;
};

struct InstallDeleteUnregisteredResponse {
    bool operator==(const InstallDeleteUnregisteredResponse&) const = default;
};

struct InstallInstallRequest {
    std::string entry_id;
    Path destination;
    std::string name;

    bool operator==(const InstallInstallRequest&) const = default;
};

struct InstallInstallResponse {
    Build build;

    bool operator==(const InstallInstallResponse&) const = default;
};

// Downloading a catalog build into the library.
class IInstallHandler {
public:
    virtual ~IInstallHandler() = default;

    // An operation: a volume query can hang on a network or empty optical drive.
    // Completes with InstallSuggestDestinationResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_suggest_destination(const CallContext& context, const InstallSuggestDestinationRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
    // Completes with InstallInstallResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_install(const CallContext& context, const InstallInstallRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
    // Drops the archive a cancelled or failed install kept for resuming.
    // Completes with InstallDiscardStagingResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_discard_staging(const CallContext& context, const InstallDiscardStagingRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
    // Completes with InstallDeleteUnregisteredResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_delete_unregistered(const CallContext& context, const InstallDeleteUnregisteredRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
};

}  // namespace reboot::api
