// Generated by protoc-gen-reboot-cpp from reboot/api/v1/integration.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

// Mirrors ports::IntegrationKind.
enum class IntegrationItem : u32 {
    UrlScheme = 0,
    Autostart = 1,
    // How clients start the engine: systemd user units, the on-demand task or the login agent.
    EngineAgent = 2,
    DesktopEntry = 3,
};

enum class IntegrationState : u32 {
    Absent = 0,
    Installed = 1,
    // Ours, but turned off in the OS by the user, who keeps that choice.
    Disabled = 2,
    // Ours, waiting for the user to allow it in macOS Login Items.
    AwaitingApproval = 3,
    // Points at another install or app; never overwritten or removed.
    Foreign = 4,
    // Ours, but for an older copy or with other arguments.
    Stale = 5,
    // This OS or install has no such entry.
    Unsupported = 6,
    // Inspection failed; `detail` says why.
    Unknown = 7,
};

enum class PrerequisiteState : u32 {
    Unknown = 0,
    Met = 1,
    Missing = 2,
    Degraded = 3,
};

enum class PurgeScope : u32 {
    // OS registrations only.
    Integration = 0,
    Caches = 1,
    AllData = 2,
};

struct IntegrationStatusEntry {
    IntegrationItem item{};
    IntegrationState state{};
    std::optional<Diagnostic> detail;
    // The user removed it, so the engine does not add it back.
    bool declined = false;
    // What the entry runs or points at, as the OS reports it.
    std::string target;

    bool operator==(const IntegrationStatusEntry&) const = default;
};

struct Prerequisite {
    // Stable, such as "mac.rosetta" or "linux.vulkan".
    std::string id;
    PrerequisiteState state{};
    bool remediable = false;
    std::optional<Diagnostic> detail;

    bool operator==(const Prerequisite&) const = default;
};

struct SecurityProduct {
    std::string name;
    bool active = false;

    bool operator==(const SecurityProduct&) const = default;
};

struct IntegrationStatusRequest {
    bool operator==(const IntegrationStatusRequest&) const = default;
};

struct IntegrationStatusResponse {
    std::vector<IntegrationStatusEntry> items;

    bool operator==(const IntegrationStatusResponse&) const = default;
};

struct IntegrationPrerequisitesRequest {
    bool operator==(const IntegrationPrerequisitesRequest&) const = default;
};

struct IntegrationPrerequisitesResponse {
    std::vector<Prerequisite> prerequisites;
    // Named in quarantine remediation; empty outside Windows.
    std::vector<SecurityProduct> security_products;

    bool operator==(const IntegrationPrerequisitesResponse&) const = default;
};

// https only.
struct IntegrationShellOpenUrlRequest {
    std::string url;

    bool operator==(const IntegrationShellOpenUrlRequest&) const = default;
};

struct IntegrationShellOpenUrlResponse {
    bool operator==(const IntegrationShellOpenUrlResponse&) const = default;
};

struct IntegrationShellOpenPathRequest {
    Path path;

    bool operator==(const IntegrationShellOpenPathRequest&) const = default;
};

struct IntegrationShellOpenPathResponse {
    bool operator==(const IntegrationShellOpenPathResponse&) const = default;
};

struct IntegrationShellRevealRequest {
    Path path;

    bool operator==(const IntegrationShellRevealRequest&) const = default;
};

struct IntegrationShellRevealResponse {
    bool operator==(const IntegrationShellRevealResponse&) const = default;
};

struct IntegrationApplyRequest {
    std::vector<IntegrationItem> items;

    bool operator==(const IntegrationApplyRequest&) const = default;
};

struct IntegrationApplyResponse {
    std::vector<IntegrationStatusEntry> items;

    bool operator==(const IntegrationApplyResponse&) const = default;
};

struct IntegrationRemoveRequest {
    std::vector<IntegrationItem> items;

    bool operator==(const IntegrationRemoveRequest&) const = default;
};

struct IntegrationRemoveResponse {
    std::vector<IntegrationStatusEntry> items;

    bool operator==(const IntegrationRemoveResponse&) const = default;
};

struct IntegrationRemediateRequest {
    std::string prerequisite;

    bool operator==(const IntegrationRemediateRequest&) const = default;
};

struct IntegrationRemediateResponse {
    Prerequisite prerequisite;

    bool operator==(const IntegrationRemediateResponse&) const = default;
};

struct IntegrationPurgeRequest {
    PurgeScope scope{};
    RunningPolicy running_policy{};

    bool operator==(const IntegrationPurgeRequest&) const = default;
};

struct IntegrationPurgeResponse {
    bool operator==(const IntegrationPurgeResponse&) const = default;
};

// After apply, remove and a reconcile that changed anything.
struct IntegrationChanged {
    std::vector<IntegrationStatusEntry> items;

    bool operator==(const IntegrationChanged&) const = default;
};

// After a remediation.
struct PrerequisitesChanged {
    std::vector<Prerequisite> prerequisites;

    bool operator==(const PrerequisitesChanged&) const = default;
};

// OS integration, prerequisites and shell actions.
class IIntegrationHandler {
public:
    virtual ~IIntegrationHandler() = default;

    virtual ::rb::Result<IntegrationStatusResponse> status(const CallContext& context, const IntegrationStatusRequest& request) = 0;
    virtual ::rb::Result<IntegrationPrerequisitesResponse> prerequisites(const CallContext& context, const IntegrationPrerequisitesRequest& request) = 0;
    virtual ::rb::Result<IntegrationShellOpenUrlResponse> shell_open_url(const CallContext& context, const IntegrationShellOpenUrlRequest& request) = 0;
    virtual ::rb::Result<IntegrationShellOpenPathResponse> shell_open_path(const CallContext& context, const IntegrationShellOpenPathRequest& request) = 0;
    virtual ::rb::Result<IntegrationShellRevealResponse> shell_reveal(const CallContext& context, const IntegrationShellRevealRequest& request) = 0;
    // Completes with IntegrationApplyResponse.
    virtual ::rb::Result<::rb::OpHandle> start_apply(const CallContext& context, const IntegrationApplyRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
    // Completes with IntegrationRemoveResponse.
    virtual ::rb::Result<::rb::OpHandle> start_remove(const CallContext& context, const IntegrationRemoveRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
    // Completes with IntegrationRemediateResponse.
    virtual ::rb::Result<::rb::OpHandle> start_remediate(const CallContext& context, const IntegrationRemediateRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
    // Completes with IntegrationPurgeResponse.
    virtual ::rb::Result<::rb::OpHandle> start_purge(const CallContext& context, const IntegrationPurgeRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
};

}  // namespace rb::api
