// Generated by protoc-gen-reboot-cpp from reboot/api/v1/join.proto. Do not edit.
#pragma once

#include <optional>
#include <string>

#include "reboot/api/call_context.hpp"
#include "reboot/api/codec.hpp"
#include "reboot/api/v1/browser.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

struct ServerTarget {
    ServerId id;
    std::string name;
    std::string author;

    bool operator==(const ServerTarget&) const = default;
};

// What Play joins when its request names no target.
struct JoinTarget {
    // Exactly one of the following is set; none set is a case this build does not know.
    std::optional<ServerTarget> server;
    // host:port as the user typed it.
    std::optional<std::string> address;

    bool operator==(const JoinTarget&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const JoinTarget& m) noexcept {
    if (auto error = one_case({m.server.has_value(), m.address.has_value()})) return error;
    return std::nullopt;
}

struct JoinParseAddressRequest {
    std::string text;

    bool operator==(const JoinParseAddressRequest&) const = default;
};

struct JoinParseAddressResponse {
    std::string host;
    u32 port = 0;

    bool operator==(const JoinParseAddressResponse&) const = default;
};

struct JoinTargetRequest {
    bool operator==(const JoinTargetRequest&) const = default;
};

struct JoinTargetResponse {
    // Absent: the local or linked auto-server.
    std::optional<JoinTarget> target;

    bool operator==(const JoinTargetResponse&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const JoinTargetResponse& m) noexcept {
    if (auto error = m.target ? check_cases(*m.target) : std::nullopt) return error;
    return std::nullopt;
}

struct JoinSetCustomTargetRequest {
    std::string address;

    bool operator==(const JoinSetCustomTargetRequest&) const = default;
};

struct JoinSetCustomTargetResponse {
    JoinTarget target;

    bool operator==(const JoinSetCustomTargetResponse&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const JoinSetCustomTargetResponse& m) noexcept {
    if (auto error = check_cases(m.target)) return error;
    return std::nullopt;
}

struct JoinClearTargetRequest {
    bool operator==(const JoinClearTargetRequest&) const = default;
};

struct JoinClearTargetResponse {
    bool operator==(const JoinClearTargetResponse&) const = default;
};

struct JoinResolveLinkRequest {
    // A reboot:// link or a bare server id.
    std::string url;

    bool operator==(const JoinResolveLinkRequest&) const = default;
};

// Raises ConfirmJoin before it becomes the target.
struct JoinResolveLinkResponse {
    ServerEntry server;
    bool hidden = false;

    bool operator==(const JoinResolveLinkResponse&) const = default;
};

struct JoinGrantRequest {
    ServerId server;

    bool operator==(const JoinGrantRequest&) const = default;
};

struct JoinGrantResponse {
    ServerEntry server;
    // The granted IPv4 host:port.
    std::string address;

    bool operator==(const JoinGrantResponse&) const = default;
};

struct JoinTargetChanged {
    std::optional<JoinTarget> target;

    bool operator==(const JoinTargetChanged&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const JoinTargetChanged& m) noexcept {
    if (auto error = m.target ? check_cases(*m.target) : std::nullopt) return error;
    return std::nullopt;
}

// What Play joins, and reboot:// links.
class IJoinHandler {
public:
    virtual ~IJoinHandler() = default;

    virtual ::rb::Result<JoinParseAddressResponse> parse_address(const CallContext& context, const JoinParseAddressRequest& request) = 0;
    virtual ::rb::Result<JoinTargetResponse> target(const CallContext& context, const JoinTargetRequest& request) = 0;
    virtual ::rb::Result<JoinSetCustomTargetResponse> set_custom_target(const CallContext& context, const JoinSetCustomTargetRequest& request) = 0;
    virtual ::rb::Result<JoinClearTargetResponse> clear_target(const CallContext& context, const JoinClearTargetRequest& request) = 0;
    // Completes with JoinResolveLinkResponse.
    virtual ::rb::Result<::rb::OpHandle> start_resolve_link(const CallContext& context, const JoinResolveLinkRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
    // Joins as Play.start does, ConfirmJoin and password included, but only returns the address,
    // for Copy IP while the backend is Local or Remote.
    // Completes with JoinGrantResponse.
    virtual ::rb::Result<::rb::OpHandle> start_grant(const CallContext& context, const JoinGrantRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
};

}  // namespace rb::api
