// Generated by protoc-gen-reboot-cpp from reboot/api/v1/library.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace reboot::api {

enum class VersionSource : u32 {
    PeString = 0,
    ChangelistMap = 1,
    RawScan = 2,
    Catalog = 3,
    User = 4,
};

enum class RemoveFiles : u32 {
    Keep = 0,
    Trash = 1,
    Delete = 2,
};

enum class LibraryChange : u32 {
    Added = 0,
    Updated = 1,
    Removed = 2,
    SelectionChanged = 3,
};

struct Build {
    BuildId id;
    std::string name;
    // The build root, never Binaries\Win64.
    Path root;
    GameVersion version;
    std::optional<u32> changelist;
    VersionSource version_source{};
    std::optional<std::string> catalog_entry;
    u64 added_unix_ms = 0;
    // False when the layout no longer resolves on disk.
    bool present = false;

    bool operator==(const Build&) const = default;
};

struct LibraryListRequest {
    bool operator==(const LibraryListRequest&) const = default;
};

struct LibraryListResponse {
    std::vector<Build> builds;
    std::optional<BuildId> selected_client;
    std::optional<BuildId> selected_host;

    bool operator==(const LibraryListResponse&) const = default;
};

struct LibraryGetRequest {
    BuildId id;

    bool operator==(const LibraryGetRequest&) const = default;
};

struct LibraryGetResponse {
    Build build;

    bool operator==(const LibraryGetResponse&) const = default;
};

struct LibrarySelectRequest {
    GameRole role{};
    // Absent clears the selection.
    std::optional<BuildId> id;

    bool operator==(const LibrarySelectRequest&) const = default;
};

struct LibrarySelectResponse {
    bool operator==(const LibrarySelectResponse&) const = default;
};

// Absent fields keep their value.
struct LibraryUpdateRequest {
    BuildId id;
    std::optional<std::string> name;
    std::optional<GameVersion> version;
    std::optional<u32> changelist;

    bool operator==(const LibraryUpdateRequest&) const = default;
};

struct LibraryUpdateResponse {
    Build build;

    bool operator==(const LibraryUpdateResponse&) const = default;
};

// Detects the version at `root`; files of another confirmed version are refused.
struct LibraryRelocateRequest {
    BuildId id;
    Path root;
    RunningPolicy running_policy{};

    bool operator==(const LibraryRelocateRequest&) const = default;
};

struct LibraryRelocateResponse {
    Build build;

    bool operator==(const LibraryRelocateResponse&) const = default;
};

// Without a version the import asks ChooseVersion when detection is not conclusive.
struct LibraryImportRequest {
    Path path;
    std::string name;
    std::optional<GameVersion> version;
    std::optional<u32> changelist;

    bool operator==(const LibraryImportRequest&) const = default;
};

struct LibraryImportResponse {
    Build build;

    bool operator==(const LibraryImportResponse&) const = default;
};

struct LibraryRemoveRequest {
    BuildId id;
    RemoveFiles files{};
    RunningPolicy running_policy{};

    bool operator==(const LibraryRemoveRequest&) const = default;
};

struct LibraryRemoveResponse {
    bool operator==(const LibraryRemoveResponse&) const = default;
};

struct LibraryChanged {
    LibraryChange change{};
    std::optional<BuildId> build;

    bool operator==(const LibraryChanged&) const = default;
};

// Installed builds and the per-role selection.
class ILibraryHandler {
public:
    virtual ~ILibraryHandler() = default;

    virtual ::reboot::Result<LibraryListResponse> list(const CallContext& context, const LibraryListRequest& request) = 0;
    virtual ::reboot::Result<LibraryGetResponse> get(const CallContext& context, const LibraryGetRequest& request) = 0;
    virtual ::reboot::Result<LibrarySelectResponse> select(const CallContext& context, const LibrarySelectRequest& request) = 0;
    virtual ::reboot::Result<LibraryUpdateResponse> update(const CallContext& context, const LibraryUpdateRequest& request) = 0;
    // Completes with LibraryRelocateResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_relocate(const CallContext& context, const LibraryRelocateRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
    // Completes with LibraryImportResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_import(const CallContext& context, const LibraryImportRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
    // Completes with LibraryRemoveResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_remove(const CallContext& context, const LibraryRemoveRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
};

}  // namespace reboot::api
