// Generated by protoc-gen-reboot-cpp from reboot/api/v1/logs.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

// Mirrors reboot::LogLevel.
enum class LogLevel : u32 {
    Trace = 0,
    Debug = 1,
    Info = 2,
    Warn = 3,
    Error = 4,
};

// Mirrors reboot::LogCategory.
enum class LogCategory : u32 {
    Engine = 0,
    Ipc = 1,
    Net = 2,
    Storage = 3,
    Builds = 4,
    Play = 5,
    Host = 6,
    Backend = 7,
    GameOutput = 8,
    Wine = 9,
    Browser = 10,
    Update = 11,
    Client = 12,
    Ui = 13,
};

// Text is redacted before it leaves the engine.
struct LogEntry {
    u64 seq = 0;
    u64 unix_ms = 0;
    LogLevel level{};
    LogCategory category{};
    std::optional<SessionId> session;
    std::string text;

    bool operator==(const LogEntry&) const = default;
};

struct LogFilter {
    LogLevel min_level{};
    // Empty matches every category.
    std::vector<LogCategory> categories;
    std::optional<SessionId> session;

    bool operator==(const LogFilter&) const = default;
};

struct LogsReadRequest {
    // 0 starts at the oldest retained entry.
    u64 cursor = 0;
    u32 limit = 0;
    LogFilter filter;

    bool operator==(const LogsReadRequest&) const = default;
};

struct LogsReadResponse {
    std::vector<LogEntry> entries;
    u64 next_cursor = 0;
    // Entries that rotated out between cursor and the first returned entry.
    u64 skipped = 0;

    bool operator==(const LogsReadResponse&) const = default;
};

struct LogsExportRequest {
    Path destination;
    bool include_crash_dumps = false;

    bool operator==(const LogsExportRequest&) const = default;
};

struct LogsExportResponse {
    Path bundle;
    u64 size_bytes = 0;

    bool operator==(const LogsExportResponse&) const = default;
};

struct LogLine {
    LogEntry entry;
    // Lines this subscription dropped since the previous one it received.
    u64 dropped = 0;

    bool operator==(const LogLine&) const = default;
};

// Reading and exporting redacted logs.
class ILogsHandler {
public:
    virtual ~ILogsHandler() = default;

    virtual ::rb::Result<LogsReadResponse> read(const CallContext& context, const LogsReadRequest& request) = 0;
    // Completes with LogsExportResponse.
    virtual ::rb::Result<::rb::OpHandle> start_export(const CallContext& context, const LogsExportRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
};

}  // namespace rb::api
