// Generated by protoc-gen-reboot-cpp. Do not edit.
#pragma once

#include <array>
#include <cstddef>
#include <span>
#include <string_view>

#include "reboot/api/method_spec.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

// Changes with every change to the schema's payloads or methods; Engine.info reports the engine's.
inline constexpr std::string_view kSchemaFingerprint = "0a4a6eaa9ef739b7";

inline constexpr u32 kEngineStatus = 0x00010001;
inline constexpr u32 kEngineInfo = 0x00010002;
inline constexpr u32 kEngineDrain = 0x00010003;
inline constexpr u32 kEngineShutdown = 0x00010004;
inline constexpr u32 kEngineRestartWhenIdle = 0x00010005;
inline constexpr u32 kEngineOperations = 0x00010006;
inline constexpr u32 kSettingsSnapshot = 0x00020001;
inline constexpr u32 kSettingsPatch = 0x00020002;
inline constexpr u32 kSettingsReset = 0x00020003;
inline constexpr u32 kSettingsSearch = 0x00020004;
inline constexpr u32 kSettingsFrontendStateGet = 0x00020005;
inline constexpr u32 kSettingsFrontendStatePut = 0x00020006;
inline constexpr u32 kSettingsLanguages = 0x00020007;
inline constexpr u32 kSettingsDescriptors = 0x00020008;
inline constexpr u32 kSettingsConsoleKeys = 0x00020009;
inline constexpr u32 kSettingsConsoleKeyFromNative = 0x0002000a;
inline constexpr u32 kLibraryList = 0x00030001;
inline constexpr u32 kLibraryGet = 0x00030002;
inline constexpr u32 kLibrarySelect = 0x00030003;
inline constexpr u32 kLibraryUpdate = 0x00030004;
inline constexpr u32 kLibraryRelocate = 0x00030005;
inline constexpr u32 kLibraryImport = 0x00030006;
inline constexpr u32 kLibraryRemove = 0x00030007;
inline constexpr u32 kCatalogList = 0x00040001;
inline constexpr u32 kCatalogRefresh = 0x00040002;
inline constexpr u32 kInstallSuggestDestination = 0x00050001;
inline constexpr u32 kInstallInstall = 0x00050002;
inline constexpr u32 kInstallDiscardStaging = 0x00050003;
inline constexpr u32 kInstallDeleteUnregistered = 0x00050004;
inline constexpr u32 kSupportQuery = 0x00060001;
inline constexpr u32 kComponentsList = 0x00070001;
inline constexpr u32 kComponentsEnsure = 0x00070002;
inline constexpr u32 kComponentsRemove = 0x00070003;
inline constexpr u32 kComponentsRuntimeSetup = 0x00070004;
inline constexpr u32 kIdentityGet = 0x00080001;
inline constexpr u32 kIdentitySetDisplayName = 0x00080002;
inline constexpr u32 kIdentityReset = 0x00080003;
inline constexpr u32 kSecretsState = 0x00090001;
inline constexpr u32 kSecretsClear = 0x00090002;
inline constexpr u32 kPlayPlan = 0x000a0001;
inline constexpr u32 kPlayStart = 0x000a0002;
inline constexpr u32 kHostProfilesList = 0x000b0001;
inline constexpr u32 kHostProfilesCreate = 0x000b0002;
inline constexpr u32 kHostProfilesUpdate = 0x000b0003;
inline constexpr u32 kHostProfilesDelete = 0x000b0004;
inline constexpr u32 kHostShareLink = 0x000b0005;
inline constexpr u32 kHostCommand = 0x000b0006;
inline constexpr u32 kHostStart = 0x000b0007;
inline constexpr u32 kHostStatus = 0x000b0008;
inline constexpr u32 kHostCancelMatchEnd = 0x000b0009;
inline constexpr u32 kHostIdentityExport = 0x000b000a;
inline constexpr u32 kHostIdentityImport = 0x000b000b;
inline constexpr u32 kSessionsList = 0x000c0001;
inline constexpr u32 kSessionsGet = 0x000c0002;
inline constexpr u32 kSessionsSetLease = 0x000c0003;
inline constexpr u32 kSessionsStop = 0x000c0004;
inline constexpr u32 kBackendStatus = 0x000d0001;
inline constexpr u32 kBackendDataDir = 0x000d0002;
inline constexpr u32 kBackendSetTarget = 0x000d0003;
inline constexpr u32 kBackendAccountsList = 0x000d0004;
inline constexpr u32 kBackendStart = 0x000d0005;
inline constexpr u32 kBackendStop = 0x000d0006;
inline constexpr u32 kBackendAccountsReset = 0x000d0007;
inline constexpr u32 kBackendAccountsDelete = 0x000d0008;
inline constexpr u32 kBackendAccountsPrune = 0x000d0009;
inline constexpr u32 kBackendAccountsRename = 0x000d000a;
inline constexpr u32 kBrowserOpenView = 0x000e0001;
inline constexpr u32 kBrowserUpdateView = 0x000e0002;
inline constexpr u32 kBrowserCloseView = 0x000e0003;
inline constexpr u32 kBrowserState = 0x000e0004;
inline constexpr u32 kBrowserResolve = 0x000e0005;
inline constexpr u32 kJoinParseAddress = 0x000f0001;
inline constexpr u32 kJoinTarget = 0x000f0002;
inline constexpr u32 kJoinSetCustomTarget = 0x000f0003;
inline constexpr u32 kJoinClearTarget = 0x000f0004;
inline constexpr u32 kJoinResolveLink = 0x000f0005;
inline constexpr u32 kJoinGrant = 0x000f0006;
inline constexpr u32 kUpdatesStatus = 0x00100001;
inline constexpr u32 kUpdatesCheck = 0x00100002;
inline constexpr u32 kUpdatesApply = 0x00100003;
inline constexpr u32 kIntegrationStatus = 0x00120001;
inline constexpr u32 kIntegrationPrerequisites = 0x00120002;
inline constexpr u32 kIntegrationShellOpenUrl = 0x00120003;
inline constexpr u32 kIntegrationShellOpenPath = 0x00120004;
inline constexpr u32 kIntegrationShellReveal = 0x00120005;
inline constexpr u32 kIntegrationApply = 0x00120006;
inline constexpr u32 kIntegrationRemove = 0x00120007;
inline constexpr u32 kIntegrationRemediate = 0x00120008;
inline constexpr u32 kIntegrationPurge = 0x00120009;
inline constexpr u32 kGuidanceNoticesList = 0x00130001;
inline constexpr u32 kGuidanceNoticesDismiss = 0x00130002;
inline constexpr u32 kGuidanceOnboardingState = 0x00130003;
inline constexpr u32 kGuidanceOnboardingAdvance = 0x00130004;
inline constexpr u32 kGuidanceOnboardingSkip = 0x00130005;
inline constexpr u32 kGuidanceLinks = 0x00130006;
inline constexpr u32 kLogsRead = 0x00140001;
inline constexpr u32 kLogsExport = 0x00140002;
inline constexpr u32 kRequestsPending = 0x00150001;
inline constexpr u32 kRequestsRespond = 0x00150002;

// Sorted by id.
inline constexpr std::array<MethodSpec, 99> kMethods{{
    MethodSpec{
        .id = kEngineStatus,
        .service = "reboot.api.v1.Engine",
        .name = "engine.status",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.EngineStatusRequest",
        .response_type = "reboot.api.v1.EngineStatusResponse",
    },
    MethodSpec{
        .id = kEngineInfo,
        .service = "reboot.api.v1.Engine",
        .name = "engine.info",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.EngineInfoRequest",
        .response_type = "reboot.api.v1.EngineInfoResponse",
    },
    MethodSpec{
        .id = kEngineDrain,
        .service = "reboot.api.v1.Engine",
        .name = "engine.drain",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.EngineDrainRequest",
        .response_type = "reboot.api.v1.EngineDrainResponse",
    },
    MethodSpec{
        .id = kEngineShutdown,
        .service = "reboot.api.v1.Engine",
        .name = "engine.shutdown",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.EngineShutdownRequest",
        .response_type = "reboot.api.v1.EngineShutdownResponse",
    },
    MethodSpec{
        .id = kEngineRestartWhenIdle,
        .service = "reboot.api.v1.Engine",
        .name = "engine.restart_when_idle",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.EngineRestartWhenIdleRequest",
        .response_type = "reboot.api.v1.EngineRestartWhenIdleResponse",
    },
    MethodSpec{
        .id = kEngineOperations,
        .service = "reboot.api.v1.Engine",
        .name = "engine.operations",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.EngineOperationsRequest",
        .response_type = "reboot.api.v1.EngineOperationsResponse",
    },
    MethodSpec{
        .id = kSettingsSnapshot,
        .service = "reboot.api.v1.Settings",
        .name = "settings.snapshot",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SettingsSnapshotRequest",
        .response_type = "reboot.api.v1.SettingsSnapshotResponse",
    },
    MethodSpec{
        .id = kSettingsPatch,
        .service = "reboot.api.v1.Settings",
        .name = "settings.patch",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SettingsPatchRequest",
        .response_type = "reboot.api.v1.SettingsPatchResponse",
    },
    MethodSpec{
        .id = kSettingsReset,
        .service = "reboot.api.v1.Settings",
        .name = "settings.reset",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SettingsResetRequest",
        .response_type = "reboot.api.v1.SettingsResetResponse",
    },
    MethodSpec{
        .id = kSettingsSearch,
        .service = "reboot.api.v1.Settings",
        .name = "settings.search",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SettingsSearchRequest",
        .response_type = "reboot.api.v1.SettingsSearchResponse",
    },
    MethodSpec{
        .id = kSettingsFrontendStateGet,
        .service = "reboot.api.v1.Settings",
        .name = "settings.frontend_state_get",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SettingsFrontendStateGetRequest",
        .response_type = "reboot.api.v1.SettingsFrontendStateGetResponse",
    },
    MethodSpec{
        .id = kSettingsFrontendStatePut,
        .service = "reboot.api.v1.Settings",
        .name = "settings.frontend_state_put",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SettingsFrontendStatePutRequest",
        .response_type = "reboot.api.v1.SettingsFrontendStatePutResponse",
    },
    MethodSpec{
        .id = kSettingsLanguages,
        .service = "reboot.api.v1.Settings",
        .name = "settings.languages",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SettingsLanguagesRequest",
        .response_type = "reboot.api.v1.SettingsLanguagesResponse",
    },
    MethodSpec{
        .id = kSettingsDescriptors,
        .service = "reboot.api.v1.Settings",
        .name = "settings.descriptors",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SettingsDescriptorsRequest",
        .response_type = "reboot.api.v1.SettingsDescriptorsResponse",
    },
    MethodSpec{
        .id = kSettingsConsoleKeys,
        .service = "reboot.api.v1.Settings",
        .name = "settings.console_keys",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SettingsConsoleKeysRequest",
        .response_type = "reboot.api.v1.SettingsConsoleKeysResponse",
    },
    MethodSpec{
        .id = kSettingsConsoleKeyFromNative,
        .service = "reboot.api.v1.Settings",
        .name = "settings.console_key_from_native",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SettingsConsoleKeyFromNativeRequest",
        .response_type = "reboot.api.v1.SettingsConsoleKeyFromNativeResponse",
    },
    MethodSpec{
        .id = kLibraryList,
        .service = "reboot.api.v1.Library",
        .name = "library.list",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.LibraryListRequest",
        .response_type = "reboot.api.v1.LibraryListResponse",
    },
    MethodSpec{
        .id = kLibraryGet,
        .service = "reboot.api.v1.Library",
        .name = "library.get",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.LibraryGetRequest",
        .response_type = "reboot.api.v1.LibraryGetResponse",
    },
    MethodSpec{
        .id = kLibrarySelect,
        .service = "reboot.api.v1.Library",
        .name = "library.select",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.LibrarySelectRequest",
        .response_type = "reboot.api.v1.LibrarySelectResponse",
    },
    MethodSpec{
        .id = kLibraryUpdate,
        .service = "reboot.api.v1.Library",
        .name = "library.update",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.LibraryUpdateRequest",
        .response_type = "reboot.api.v1.LibraryUpdateResponse",
    },
    MethodSpec{
        .id = kLibraryRelocate,
        .service = "reboot.api.v1.Library",
        .name = "library.relocate",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::ItemCount,
        .request_type = "reboot.api.v1.LibraryRelocateRequest",
        .response_type = "reboot.api.v1.LibraryRelocateResponse",
    },
    MethodSpec{
        .id = kLibraryImport,
        .service = "reboot.api.v1.Library",
        .name = "library.import",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::ItemCount,
        .request_type = "reboot.api.v1.LibraryImportRequest",
        .response_type = "reboot.api.v1.LibraryImportResponse",
    },
    MethodSpec{
        .id = kLibraryRemove,
        .service = "reboot.api.v1.Library",
        .name = "library.remove",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::ItemCount,
        .request_type = "reboot.api.v1.LibraryRemoveRequest",
        .response_type = "reboot.api.v1.LibraryRemoveResponse",
    },
    MethodSpec{
        .id = kCatalogList,
        .service = "reboot.api.v1.Catalog",
        .name = "catalog.list",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.CatalogListRequest",
        .response_type = "reboot.api.v1.CatalogListResponse",
    },
    MethodSpec{
        .id = kCatalogRefresh,
        .service = "reboot.api.v1.Catalog",
        .name = "catalog.refresh",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.CatalogRefreshRequest",
        .response_type = "reboot.api.v1.CatalogRefreshResponse",
    },
    MethodSpec{
        .id = kInstallSuggestDestination,
        .service = "reboot.api.v1.Install",
        .name = "install.suggest_destination",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.InstallSuggestDestinationRequest",
        .response_type = "reboot.api.v1.InstallSuggestDestinationResponse",
    },
    MethodSpec{
        .id = kInstallInstall,
        .service = "reboot.api.v1.Install",
        .name = "install.install",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::Detached,
        .progress = ProgressUnit::ByteCount,
        .request_type = "reboot.api.v1.InstallInstallRequest",
        .response_type = "reboot.api.v1.InstallInstallResponse",
    },
    MethodSpec{
        .id = kInstallDiscardStaging,
        .service = "reboot.api.v1.Install",
        .name = "install.discard_staging",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.InstallDiscardStagingRequest",
        .response_type = "reboot.api.v1.InstallDiscardStagingResponse",
    },
    MethodSpec{
        .id = kInstallDeleteUnregistered,
        .service = "reboot.api.v1.Install",
        .name = "install.delete_unregistered",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::ItemCount,
        .request_type = "reboot.api.v1.InstallDeleteUnregisteredRequest",
        .response_type = "reboot.api.v1.InstallDeleteUnregisteredResponse",
    },
    MethodSpec{
        .id = kSupportQuery,
        .service = "reboot.api.v1.Support",
        .name = "support.query",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SupportQueryRequest",
        .response_type = "reboot.api.v1.SupportQueryResponse",
    },
    MethodSpec{
        .id = kComponentsList,
        .service = "reboot.api.v1.Components",
        .name = "components.list",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.ComponentsListRequest",
        .response_type = "reboot.api.v1.ComponentsListResponse",
    },
    MethodSpec{
        .id = kComponentsEnsure,
        .service = "reboot.api.v1.Components",
        .name = "components.ensure",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::Detached,
        .progress = ProgressUnit::ByteCount,
        .request_type = "reboot.api.v1.ComponentsEnsureRequest",
        .response_type = "reboot.api.v1.ComponentsEnsureResponse",
    },
    MethodSpec{
        .id = kComponentsRemove,
        .service = "reboot.api.v1.Components",
        .name = "components.remove",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.ComponentsRemoveRequest",
        .response_type = "reboot.api.v1.ComponentsRemoveResponse",
    },
    MethodSpec{
        .id = kComponentsRuntimeSetup,
        .service = "reboot.api.v1.Components",
        .name = "components.runtime_setup",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::Detached,
        .progress = ProgressUnit::ByteCount,
        .request_type = "reboot.api.v1.ComponentsRuntimeSetupRequest",
        .response_type = "reboot.api.v1.ComponentsRuntimeSetupResponse",
    },
    MethodSpec{
        .id = kIdentityGet,
        .service = "reboot.api.v1.Identity",
        .name = "identity.get",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.IdentityGetRequest",
        .response_type = "reboot.api.v1.IdentityGetResponse",
    },
    MethodSpec{
        .id = kIdentitySetDisplayName,
        .service = "reboot.api.v1.Identity",
        .name = "identity.set_display_name",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.IdentitySetDisplayNameRequest",
        .response_type = "reboot.api.v1.IdentitySetDisplayNameResponse",
    },
    MethodSpec{
        .id = kIdentityReset,
        .service = "reboot.api.v1.Identity",
        .name = "identity.reset",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.IdentityResetRequest",
        .response_type = "reboot.api.v1.IdentityResetResponse",
    },
    MethodSpec{
        .id = kSecretsState,
        .service = "reboot.api.v1.Secrets",
        .name = "secrets.state",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SecretsStateRequest",
        .response_type = "reboot.api.v1.SecretsStateResponse",
    },
    MethodSpec{
        .id = kSecretsClear,
        .service = "reboot.api.v1.Secrets",
        .name = "secrets.clear",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SecretsClearRequest",
        .response_type = "reboot.api.v1.SecretsClearResponse",
    },
    MethodSpec{
        .id = kPlayPlan,
        .service = "reboot.api.v1.Play",
        .name = "play.plan",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.PlayPlanRequest",
        .response_type = "reboot.api.v1.PlayPlanResponse",
    },
    MethodSpec{
        .id = kPlayStart,
        .service = "reboot.api.v1.Play",
        .name = "play.start",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::Detached,
        .progress = ProgressUnit::ItemCount,
        .request_type = "reboot.api.v1.PlayStartRequest",
        .response_type = "reboot.api.v1.PlayStartResponse",
    },
    MethodSpec{
        .id = kHostProfilesList,
        .service = "reboot.api.v1.Host",
        .name = "host.profiles_list",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.HostProfilesListRequest",
        .response_type = "reboot.api.v1.HostProfilesListResponse",
    },
    MethodSpec{
        .id = kHostProfilesCreate,
        .service = "reboot.api.v1.Host",
        .name = "host.profiles_create",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.HostProfilesCreateRequest",
        .response_type = "reboot.api.v1.HostProfilesCreateResponse",
    },
    MethodSpec{
        .id = kHostProfilesUpdate,
        .service = "reboot.api.v1.Host",
        .name = "host.profiles_update",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.HostProfilesUpdateRequest",
        .response_type = "reboot.api.v1.HostProfilesUpdateResponse",
    },
    MethodSpec{
        .id = kHostProfilesDelete,
        .service = "reboot.api.v1.Host",
        .name = "host.profiles_delete",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.HostProfilesDeleteRequest",
        .response_type = "reboot.api.v1.HostProfilesDeleteResponse",
    },
    MethodSpec{
        .id = kHostShareLink,
        .service = "reboot.api.v1.Host",
        .name = "host.share_link",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.HostShareLinkRequest",
        .response_type = "reboot.api.v1.HostShareLinkResponse",
    },
    MethodSpec{
        .id = kHostCommand,
        .service = "reboot.api.v1.Host",
        .name = "host.command",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.HostCommandRequest",
        .response_type = "reboot.api.v1.HostCommandResponse",
    },
    MethodSpec{
        .id = kHostStart,
        .service = "reboot.api.v1.Host",
        .name = "host.start",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::Detached,
        .progress = ProgressUnit::ItemCount,
        .request_type = "reboot.api.v1.HostStartRequest",
        .response_type = "reboot.api.v1.HostStartResponse",
    },
    MethodSpec{
        .id = kHostStatus,
        .service = "reboot.api.v1.Host",
        .name = "host.status",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.HostStatusRequest",
        .response_type = "reboot.api.v1.HostStatusResponse",
    },
    MethodSpec{
        .id = kHostCancelMatchEnd,
        .service = "reboot.api.v1.Host",
        .name = "host.cancel_match_end",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.HostCancelMatchEndRequest",
        .response_type = "reboot.api.v1.HostCancelMatchEndResponse",
    },
    MethodSpec{
        .id = kHostIdentityExport,
        .service = "reboot.api.v1.Host",
        .name = "host.identity_export",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.HostIdentityExportRequest",
        .response_type = "reboot.api.v1.HostIdentityExportResponse",
    },
    MethodSpec{
        .id = kHostIdentityImport,
        .service = "reboot.api.v1.Host",
        .name = "host.identity_import",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.HostIdentityImportRequest",
        .response_type = "reboot.api.v1.HostIdentityImportResponse",
    },
    MethodSpec{
        .id = kSessionsList,
        .service = "reboot.api.v1.Sessions",
        .name = "sessions.list",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SessionsListRequest",
        .response_type = "reboot.api.v1.SessionsListResponse",
    },
    MethodSpec{
        .id = kSessionsGet,
        .service = "reboot.api.v1.Sessions",
        .name = "sessions.get",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SessionsGetRequest",
        .response_type = "reboot.api.v1.SessionsGetResponse",
    },
    MethodSpec{
        .id = kSessionsSetLease,
        .service = "reboot.api.v1.Sessions",
        .name = "sessions.set_lease",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SessionsSetLeaseRequest",
        .response_type = "reboot.api.v1.SessionsSetLeaseResponse",
    },
    MethodSpec{
        .id = kSessionsStop,
        .service = "reboot.api.v1.Sessions",
        .name = "sessions.stop",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.SessionsStopRequest",
        .response_type = "reboot.api.v1.SessionsStopResponse",
    },
    MethodSpec{
        .id = kBackendStatus,
        .service = "reboot.api.v1.Backend",
        .name = "backend.status",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BackendStatusRequest",
        .response_type = "reboot.api.v1.BackendStatusResponse",
    },
    MethodSpec{
        .id = kBackendDataDir,
        .service = "reboot.api.v1.Backend",
        .name = "backend.data_dir",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BackendDataDirRequest",
        .response_type = "reboot.api.v1.BackendDataDirResponse",
    },
    MethodSpec{
        .id = kBackendSetTarget,
        .service = "reboot.api.v1.Backend",
        .name = "backend.set_target",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BackendSetTargetRequest",
        .response_type = "reboot.api.v1.BackendSetTargetResponse",
    },
    MethodSpec{
        .id = kBackendAccountsList,
        .service = "reboot.api.v1.Backend",
        .name = "backend.accounts_list",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BackendAccountsListRequest",
        .response_type = "reboot.api.v1.BackendAccountsListResponse",
    },
    MethodSpec{
        .id = kBackendStart,
        .service = "reboot.api.v1.Backend",
        .name = "backend.start",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BackendStartRequest",
        .response_type = "reboot.api.v1.BackendStartResponse",
    },
    MethodSpec{
        .id = kBackendStop,
        .service = "reboot.api.v1.Backend",
        .name = "backend.stop",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BackendStopRequest",
        .response_type = "reboot.api.v1.BackendStopResponse",
    },
    MethodSpec{
        .id = kBackendAccountsReset,
        .service = "reboot.api.v1.Backend",
        .name = "backend.accounts_reset",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BackendAccountsResetRequest",
        .response_type = "reboot.api.v1.BackendAccountsResetResponse",
    },
    MethodSpec{
        .id = kBackendAccountsDelete,
        .service = "reboot.api.v1.Backend",
        .name = "backend.accounts_delete",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BackendAccountsDeleteRequest",
        .response_type = "reboot.api.v1.BackendAccountsDeleteResponse",
    },
    MethodSpec{
        .id = kBackendAccountsPrune,
        .service = "reboot.api.v1.Backend",
        .name = "backend.accounts_prune",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BackendAccountsPruneRequest",
        .response_type = "reboot.api.v1.BackendAccountsPruneResponse",
    },
    MethodSpec{
        .id = kBackendAccountsRename,
        .service = "reboot.api.v1.Backend",
        .name = "backend.accounts_rename",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BackendAccountsRenameRequest",
        .response_type = "reboot.api.v1.BackendAccountsRenameResponse",
    },
    MethodSpec{
        .id = kBrowserOpenView,
        .service = "reboot.api.v1.Browser",
        .name = "browser.open_view",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BrowserOpenViewRequest",
        .response_type = "reboot.api.v1.BrowserOpenViewResponse",
    },
    MethodSpec{
        .id = kBrowserUpdateView,
        .service = "reboot.api.v1.Browser",
        .name = "browser.update_view",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BrowserUpdateViewRequest",
        .response_type = "reboot.api.v1.BrowserUpdateViewResponse",
    },
    MethodSpec{
        .id = kBrowserCloseView,
        .service = "reboot.api.v1.Browser",
        .name = "browser.close_view",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BrowserCloseViewRequest",
        .response_type = "reboot.api.v1.BrowserCloseViewResponse",
    },
    MethodSpec{
        .id = kBrowserState,
        .service = "reboot.api.v1.Browser",
        .name = "browser.state",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BrowserStateRequest",
        .response_type = "reboot.api.v1.BrowserStateResponse",
    },
    MethodSpec{
        .id = kBrowserResolve,
        .service = "reboot.api.v1.Browser",
        .name = "browser.resolve",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.BrowserResolveRequest",
        .response_type = "reboot.api.v1.BrowserResolveResponse",
    },
    MethodSpec{
        .id = kJoinParseAddress,
        .service = "reboot.api.v1.Join",
        .name = "join.parse_address",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.JoinParseAddressRequest",
        .response_type = "reboot.api.v1.JoinParseAddressResponse",
    },
    MethodSpec{
        .id = kJoinTarget,
        .service = "reboot.api.v1.Join",
        .name = "join.target",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.JoinTargetRequest",
        .response_type = "reboot.api.v1.JoinTargetResponse",
    },
    MethodSpec{
        .id = kJoinSetCustomTarget,
        .service = "reboot.api.v1.Join",
        .name = "join.set_custom_target",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.JoinSetCustomTargetRequest",
        .response_type = "reboot.api.v1.JoinSetCustomTargetResponse",
    },
    MethodSpec{
        .id = kJoinClearTarget,
        .service = "reboot.api.v1.Join",
        .name = "join.clear_target",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.JoinClearTargetRequest",
        .response_type = "reboot.api.v1.JoinClearTargetResponse",
    },
    MethodSpec{
        .id = kJoinResolveLink,
        .service = "reboot.api.v1.Join",
        .name = "join.resolve_link",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.JoinResolveLinkRequest",
        .response_type = "reboot.api.v1.JoinResolveLinkResponse",
    },
    MethodSpec{
        .id = kJoinGrant,
        .service = "reboot.api.v1.Join",
        .name = "join.grant",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.JoinGrantRequest",
        .response_type = "reboot.api.v1.JoinGrantResponse",
    },
    MethodSpec{
        .id = kUpdatesStatus,
        .service = "reboot.api.v1.Updates",
        .name = "updates.status",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.UpdatesStatusRequest",
        .response_type = "reboot.api.v1.UpdatesStatusResponse",
    },
    MethodSpec{
        .id = kUpdatesCheck,
        .service = "reboot.api.v1.Updates",
        .name = "updates.check",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.UpdatesCheckRequest",
        .response_type = "reboot.api.v1.UpdatesCheckResponse",
    },
    MethodSpec{
        .id = kUpdatesApply,
        .service = "reboot.api.v1.Updates",
        .name = "updates.apply",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::Detached,
        .progress = ProgressUnit::ByteCount,
        .request_type = "reboot.api.v1.UpdatesApplyRequest",
        .response_type = "reboot.api.v1.UpdatesApplyResponse",
    },
    MethodSpec{
        .id = kIntegrationStatus,
        .service = "reboot.api.v1.Integration",
        .name = "integration.status",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.IntegrationStatusRequest",
        .response_type = "reboot.api.v1.IntegrationStatusResponse",
    },
    MethodSpec{
        .id = kIntegrationPrerequisites,
        .service = "reboot.api.v1.Integration",
        .name = "integration.prerequisites",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.IntegrationPrerequisitesRequest",
        .response_type = "reboot.api.v1.IntegrationPrerequisitesResponse",
    },
    MethodSpec{
        .id = kIntegrationShellOpenUrl,
        .service = "reboot.api.v1.Integration",
        .name = "integration.shell_open_url",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.IntegrationShellOpenUrlRequest",
        .response_type = "reboot.api.v1.IntegrationShellOpenUrlResponse",
    },
    MethodSpec{
        .id = kIntegrationShellOpenPath,
        .service = "reboot.api.v1.Integration",
        .name = "integration.shell_open_path",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.IntegrationShellOpenPathRequest",
        .response_type = "reboot.api.v1.IntegrationShellOpenPathResponse",
    },
    MethodSpec{
        .id = kIntegrationShellReveal,
        .service = "reboot.api.v1.Integration",
        .name = "integration.shell_reveal",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.IntegrationShellRevealRequest",
        .response_type = "reboot.api.v1.IntegrationShellRevealResponse",
    },
    MethodSpec{
        .id = kIntegrationApply,
        .service = "reboot.api.v1.Integration",
        .name = "integration.apply",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.IntegrationApplyRequest",
        .response_type = "reboot.api.v1.IntegrationApplyResponse",
    },
    MethodSpec{
        .id = kIntegrationRemove,
        .service = "reboot.api.v1.Integration",
        .name = "integration.remove",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.IntegrationRemoveRequest",
        .response_type = "reboot.api.v1.IntegrationRemoveResponse",
    },
    MethodSpec{
        .id = kIntegrationRemediate,
        .service = "reboot.api.v1.Integration",
        .name = "integration.remediate",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::ByteCount,
        .request_type = "reboot.api.v1.IntegrationRemediateRequest",
        .response_type = "reboot.api.v1.IntegrationRemediateResponse",
    },
    MethodSpec{
        .id = kIntegrationPurge,
        .service = "reboot.api.v1.Integration",
        .name = "integration.purge",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::ItemCount,
        .request_type = "reboot.api.v1.IntegrationPurgeRequest",
        .response_type = "reboot.api.v1.IntegrationPurgeResponse",
    },
    MethodSpec{
        .id = kGuidanceNoticesList,
        .service = "reboot.api.v1.Guidance",
        .name = "guidance.notices_list",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.GuidanceNoticesListRequest",
        .response_type = "reboot.api.v1.GuidanceNoticesListResponse",
    },
    MethodSpec{
        .id = kGuidanceNoticesDismiss,
        .service = "reboot.api.v1.Guidance",
        .name = "guidance.notices_dismiss",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.GuidanceNoticesDismissRequest",
        .response_type = "reboot.api.v1.GuidanceNoticesDismissResponse",
    },
    MethodSpec{
        .id = kGuidanceOnboardingState,
        .service = "reboot.api.v1.Guidance",
        .name = "guidance.onboarding_state",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.GuidanceOnboardingStateRequest",
        .response_type = "reboot.api.v1.GuidanceOnboardingStateResponse",
    },
    MethodSpec{
        .id = kGuidanceOnboardingAdvance,
        .service = "reboot.api.v1.Guidance",
        .name = "guidance.onboarding_advance",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.GuidanceOnboardingAdvanceRequest",
        .response_type = "reboot.api.v1.GuidanceOnboardingAdvanceResponse",
    },
    MethodSpec{
        .id = kGuidanceOnboardingSkip,
        .service = "reboot.api.v1.Guidance",
        .name = "guidance.onboarding_skip",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.GuidanceOnboardingSkipRequest",
        .response_type = "reboot.api.v1.GuidanceOnboardingSkipResponse",
    },
    MethodSpec{
        .id = kGuidanceLinks,
        .service = "reboot.api.v1.Guidance",
        .name = "guidance.links",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.GuidanceLinksRequest",
        .response_type = "reboot.api.v1.GuidanceLinksResponse",
    },
    MethodSpec{
        .id = kLogsRead,
        .service = "reboot.api.v1.Logs",
        .name = "logs.read",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.LogsReadRequest",
        .response_type = "reboot.api.v1.LogsReadResponse",
    },
    MethodSpec{
        .id = kLogsExport,
        .service = "reboot.api.v1.Logs",
        .name = "logs.export",
        .kind = MethodKind::Operation,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::ItemCount,
        .request_type = "reboot.api.v1.LogsExportRequest",
        .response_type = "reboot.api.v1.LogsExportResponse",
    },
    MethodSpec{
        .id = kRequestsPending,
        .service = "reboot.api.v1.Requests",
        .name = "requests.pending",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.RequestsPendingRequest",
        .response_type = "reboot.api.v1.RequestsPendingResponse",
    },
    MethodSpec{
        .id = kRequestsRespond,
        .service = "reboot.api.v1.Requests",
        .name = "requests.respond",
        .kind = MethodKind::Call,
        .default_disconnect = ::rb::DisconnectPolicy::BoundToConnection,
        .progress = ProgressUnit::NoProgress,
        .request_type = "reboot.api.v1.RequestsRespondRequest",
        .response_type = "reboot.api.v1.RequestsRespondResponse",
    },
}};

class MethodTable {
public:
    [[nodiscard]] static constexpr std::span<const MethodSpec> all() noexcept { return kMethods; }

    [[nodiscard]] static constexpr const MethodSpec* find(u32 id) noexcept {
        std::size_t low = 0;
        std::size_t high = kMethods.size();
        while (low < high) {
            const std::size_t mid = low + (high - low) / 2;
            if (kMethods[mid].id < id) low = mid + 1;
            else high = mid;
        }
        return low < kMethods.size() && kMethods[low].id == id ? &kMethods[low] : nullptr;
    }
};

}  // namespace rb::api
