// Generated by protoc-gen-reboot-cpp from reboot/api/v1/play.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/codec.hpp"
#include "reboot/api/v1/backend.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/api/v1/requests.hpp"
#include "reboot/api/v1/support.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"

namespace rb::api {

struct PlayTarget {
    // Exactly one of the following is set; none set is a case this build does not know.
    std::optional<ServerId> server;
    // host:port, resolved and probed at start.
    std::optional<std::string> address;

    bool operator==(const PlayTarget&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const PlayTarget& m) noexcept {
    if (auto error = one_case({m.server.has_value(), m.address.has_value()})) return error;
    return std::nullopt;
}

struct PlayRequest {
    // Absent: the library's client selection.
    std::optional<BuildId> build;
    // Absent: the Join target, or the linked auto-server when auto_server is set.
    std::optional<PlayTarget> target;
    // Starts a linked, unlisted host for this client.
    bool auto_server = false;
    // Absent: the configured backend target.
    std::optional<BackendTarget> backend;
    // Extra game arguments with shell-style quoting.
    std::string custom_args;
    // The caller's environment at this launch, so a long-lived connection never launches with a
    // stale DISPLAY. Replaces the one captured at connect; empty keeps that. Names outside the
    // engine's client allow-list (display, audio, D-Bus, locale) are dropped.
    std::vector<EnvVar> environment;

    bool operator==(const PlayRequest&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const PlayRequest& m) noexcept {
    if (auto error = m.target ? check_cases(*m.target) : std::nullopt) return error;
    return std::nullopt;
}

struct PlayPlanRequest {
    PlayRequest request;

    bool operator==(const PlayPlanRequest&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const PlayPlanRequest& m) noexcept {
    if (auto error = check_cases(m.request)) return error;
    return std::nullopt;
}

// What start would do now; nothing is reserved.
struct PlayPlanResponse {
    SupportTier tier{};
    NetMode net_mode{};
    RunnerKind runner{};
    std::vector<Diagnostic> blockers;
    std::vector<Diagnostic> warnings;
    // Requests start is expected to raise.
    std::vector<UserRequestKind> questions;

    bool operator==(const PlayPlanResponse&) const = default;
};

// Play needs the caller and the engine in the same OS session.
struct PlayStartRequest {
    PlayRequest request;

    bool operator==(const PlayStartRequest&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const PlayStartRequest& m) noexcept {
    if (auto error = check_cases(m.request)) return error;
    return std::nullopt;
}

// Sent once the game logged in.
struct PlayStartResponse {
    SessionId session;

    bool operator==(const PlayStartResponse&) const = default;
};

// Launching the game as a client.
class IPlayHandler {
public:
    virtual ~IPlayHandler() = default;

    virtual ::rb::Result<PlayPlanResponse> plan(const CallContext& context, const PlayPlanRequest& request) = 0;
    // Completes with PlayStartResponse.
    virtual ::rb::Result<::rb::OpHandle> start(const CallContext& context, const PlayStartRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
};

}  // namespace rb::api
