// Generated by protoc-gen-reboot-cpp from reboot/api/v1/requests.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/codec.hpp"
#include "reboot/api/v1/backend.hpp"
#include "reboot/api/v1/browser.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/api/v1/secrets.hpp"
#include "reboot/api/v1/sessions.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

// Mirrors reboot::UserRequestKind, in order.
enum class UserRequestKind : u32 {
    NeedsSecret = 0,
    ConfirmJoin = 1,
    NeedsJoinPassword = 2,
    AutoServerConsent = 3,
    ConfirmUnencryptedUpstream = 4,
    AccountRenameConflict = 5,
    RosettaInstall = 6,
    AgentRequiresApproval = 7,
    ChooseVersion = 8,
    ConfirmUntested = 9,
    ConfirmStopSessions = 10,
};

// Mirrors reboot::RequestResolution.
enum class RequestResolution : u32 {
    Answered = 0,
    // Its operation ended or was cancelled first.
    Withdrawn = 1,
};

struct NeedsSecretPrompt {
    SecretTarget target;

    bool operator==(const NeedsSecretPrompt&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const NeedsSecretPrompt& m) noexcept {
    if (auto error = check_cases(m.target)) return error;
    return std::nullopt;
}

struct ConfirmJoinPrompt {
    ServerEntry server;

    bool operator==(const ConfirmJoinPrompt&) const = default;
};

struct NeedsJoinPasswordPrompt {
    ServerEntry server;
    // The previous password was wrong.
    bool retry = false;

    bool operator==(const NeedsJoinPasswordPrompt&) const = default;
};

struct AutoServerConsentPrompt {
    GameVersion version;

    bool operator==(const AutoServerConsentPrompt&) const = default;
};

struct ConfirmUnencryptedUpstreamPrompt {
    std::string origin;

    bool operator==(const ConfirmUnencryptedUpstreamPrompt&) const = default;
};

struct AccountRenameConflictPrompt {
    std::string account_id;
    std::string display_name;
    std::string conflicting_account_id;

    bool operator==(const AccountRenameConflictPrompt&) const = default;
};

struct RosettaInstallPrompt {
    bool operator==(const RosettaInstallPrompt&) const = default;
};

struct AgentRequiresApprovalPrompt {
    bool operator==(const AgentRequiresApprovalPrompt&) const = default;
};

struct ChooseVersionPrompt {
    Path build_root;
    // What the detector read, if anything; empty when nothing was found.
    std::string detected;
    std::vector<GameVersion> candidates;

    bool operator==(const ChooseVersionPrompt&) const = default;
};

struct ConfirmUntestedPrompt {
    GameVersion version;
    GameRole role{};
    RunnerKind runner{};
    std::vector<Diagnostic> reasons;

    bool operator==(const ConfirmUntestedPrompt&) const = default;
};

struct ConfirmStopSessionsPrompt {
    std::vector<SessionSummary> sessions;

    bool operator==(const ConfirmStopSessionsPrompt&) const = default;
};

struct RequestPrompt {
    // Exactly one of the following is set; none set is a case this build does not know.
    std::optional<NeedsSecretPrompt> needs_secret;
    std::optional<ConfirmJoinPrompt> confirm_join;
    std::optional<NeedsJoinPasswordPrompt> needs_join_password;
    std::optional<AutoServerConsentPrompt> auto_server_consent;
    std::optional<ConfirmUnencryptedUpstreamPrompt> confirm_unencrypted_upstream;
    std::optional<AccountRenameConflictPrompt> account_rename_conflict;
    std::optional<RosettaInstallPrompt> rosetta_install;
    std::optional<AgentRequiresApprovalPrompt> agent_requires_approval;
    std::optional<ChooseVersionPrompt> choose_version;
    std::optional<ConfirmUntestedPrompt> confirm_untested;
    std::optional<ConfirmStopSessionsPrompt> confirm_stop_sessions;

    bool operator==(const RequestPrompt&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const RequestPrompt& m) noexcept {
    if (auto error = one_case({m.needs_secret.has_value(),
                               m.confirm_join.has_value(),
                               m.needs_join_password.has_value(),
                               m.auto_server_consent.has_value(),
                               m.confirm_unencrypted_upstream.has_value(),
                               m.account_rename_conflict.has_value(),
                               m.rosetta_install.has_value(),
                               m.agent_requires_approval.has_value(),
                               m.choose_version.has_value(),
                               m.confirm_untested.has_value(),
                               m.confirm_stop_sessions.has_value()}))
        return error;
    if (auto error = m.needs_secret ? check_cases(*m.needs_secret) : std::nullopt) return error;
    return std::nullopt;
}

struct Decision {
    bool accept = false;
    // Apply the same answer to this subject from now on.
    bool remember = false;

    bool operator==(const Decision&) const = default;
};

struct RequestAnswer {
    // Exactly one of the following is set; none set is a case this build does not know.
    std::optional<Decision> decision;
    // ChooseVersion.
    std::optional<GameVersion> version;
    // AccountRenameConflict; ASK is refused.
    std::optional<RenameConflict> rename;
    // NeedsSecret and NeedsJoinPassword, after rb_secret_put stored the secret.
    std::optional<bool> secret_provided;

    bool operator==(const RequestAnswer&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const RequestAnswer& m) noexcept {
    if (auto error = one_case({m.decision.has_value(),
                               m.version.has_value(),
                               m.rename.has_value(),
                               m.secret_provided.has_value()}))
        return error;
    return std::nullopt;
}

struct UserActionRequired {
    u64 request_id = 0;
    UserRequestKind kind{};
    std::optional<u64> op_id;
    std::optional<SessionId> session;
    RequestPrompt prompt;

    bool operator==(const UserActionRequired&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const UserActionRequired& m) noexcept {
    if (auto error = check_cases(m.prompt)) return error;
    return std::nullopt;
}

struct UserActionResolved {
    u64 request_id = 0;
    RequestResolution resolution{};

    bool operator==(const UserActionResolved&) const = default;
};

struct RequestsPendingRequest {
    bool operator==(const RequestsPendingRequest&) const = default;
};

struct RequestsPendingResponse {
    std::vector<UserActionRequired> requests;

    bool operator==(const RequestsPendingResponse&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const RequestsPendingResponse& m) noexcept {
    if (auto error = check_all_cases(m.requests)) return error;
    return std::nullopt;
}

// The first valid answer wins; later ones get requests.already_resolved.
struct RequestsRespondRequest {
    u64 request_id = 0;
    RequestAnswer answer;

    bool operator==(const RequestsRespondRequest&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const RequestsRespondRequest& m) noexcept {
    if (auto error = check_cases(m.answer)) return error;
    return std::nullopt;
}

struct RequestsRespondResponse {
    bool operator==(const RequestsRespondResponse&) const = default;
};

// Questions the engine asks a human.
class IRequestsHandler {
public:
    virtual ~IRequestsHandler() = default;

    virtual ::rb::Result<RequestsPendingResponse> pending(const CallContext& context, const RequestsPendingRequest& request) = 0;
    virtual ::rb::Result<RequestsRespondResponse> respond(const CallContext& context, const RequestsRespondRequest& request) = 0;
};

}  // namespace rb::api
