// Generated by protoc-gen-reboot-cpp from reboot/api/v1/secrets.proto. Do not edit.
#pragma once

#include <optional>
#include <string>

#include "reboot/api/call_context.hpp"
#include "reboot/api/codec.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

enum class SecretKind : u32 {
    Unspecified = 0,
    HostJoinPassword = 1,
    BackendPassword = 2,
    // Kept only until its NeedsJoinPassword request resolves.
    JoinPassword = 3,
};

enum class SecretStore : u32 {
    Unavailable = 0,
    CredentialManager = 1,
    DpapiFile = 2,
    Keychain = 3,
    Libsecret = 4,
    OwnerOnlyFile = 5,
};

struct BackendHost {
    // Compared case-insensitively.
    std::string host;
    // Absent when the backend origin names no port.
    std::optional<u32> port;

    bool operator==(const BackendHost&) const = default;
};

// rb_secret_put and rb_secret_reveal take this, encoded, as their target.
struct SecretTarget {
    SecretKind kind{};
    // Exactly one of the following is set; none set is a case this build does not know.
    // HostJoinPassword.
    std::optional<HostProfileId> host_profile;
    // BackendPassword.
    std::optional<BackendHost> backend;
    // JoinPassword: the id of its NeedsJoinPassword request.
    std::optional<u64> join_request;

    bool operator==(const SecretTarget&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const SecretTarget& m) noexcept {
    if (auto error = one_case({m.host_profile.has_value(),
                               m.backend.has_value(),
                               m.join_request.has_value()}))
        return error;
    return std::nullopt;
}

struct SecretsStateRequest {
    SecretTarget target;

    bool operator==(const SecretsStateRequest&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const SecretsStateRequest& m) noexcept {
    if (auto error = check_cases(m.target)) return error;
    return std::nullopt;
}

struct SecretsStateResponse {
    bool present = false;
    SecretStore store{};

    bool operator==(const SecretsStateResponse&) const = default;
};

// Never carries a value.
struct SecretStateChanged {
    SecretTarget target;
    bool present = false;
    SecretStore store{};

    bool operator==(const SecretStateChanged&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const SecretStateChanged& m) noexcept {
    if (auto error = check_cases(m.target)) return error;
    return std::nullopt;
}

struct SecretsClearRequest {
    SecretTarget target;

    bool operator==(const SecretsClearRequest&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const SecretsClearRequest& m) noexcept {
    if (auto error = check_cases(m.target)) return error;
    return std::nullopt;
}

struct SecretsClearResponse {
    bool operator==(const SecretsClearResponse&) const = default;
};

// Presence of stored secrets; values only travel through rb_secret_put.
class ISecretsHandler {
public:
    virtual ~ISecretsHandler() = default;

    virtual ::rb::Result<SecretsStateResponse> state(const CallContext& context, const SecretsStateRequest& request) = 0;
    virtual ::rb::Result<SecretsClearResponse> clear(const CallContext& context, const SecretsClearRequest& request) = 0;
};

}  // namespace rb::api
