// Generated by protoc-gen-reboot-cpp from reboot/api/v1/sessions.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/api/v1/support.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace reboot::api {

enum class SessionKind : u32 {
    Play = 0,
    Host = 1,
};

enum class SessionPhase : u32 {
    Preparing = 0,
    Launching = 1,
    Loading = 2,
    Running = 3,
    Stopping = 4,
    Ended = 5,
};

enum class LeaseKind : u32 {
    // The session survives every UI.
    Engine = 0,
    // The session stops when the connection that set the lease closes.
    Client = 1,
};

enum class ProcessRole : u32 {
    Game = 0,
    Companion = 1,
    GameServer = 2,
    Winhost = 3,
};

enum class EndReason : u32 {
    Stopped = 0,
    Exited = 1,
    Crashed = 2,
    Failed = 3,
    EngineShutdown = 4,
    LeaseEnded = 5,
};

// Frozen with the bootstrap subset: fields are only ever appended.
struct SessionSummary {
    SessionId id;
    SessionKind kind{};
    SessionPhase phase{};
    // The play session a linked auto-server belongs to.
    std::optional<SessionId> parent;
    u64 started_unix_ms = 0;
    // The build or host profile name.
    std::string label;

    bool operator==(const SessionSummary&) const = default;
};

struct SessionProcess {
    ProcessRole role{};
    u32 pid = 0;

    bool operator==(const SessionProcess&) const = default;
};

struct SessionDetail {
    LeaseKind lease{};
    std::optional<BuildId> build;
    GameVersion version;
    RunnerKind runner{};
    NetMode net_mode{};
    SupportTier tier{};
    std::optional<HostProfileId> profile;
    std::vector<SessionProcess> processes;
    // Problems that did not end the session.
    std::vector<Diagnostic> degraded;

    bool operator==(const SessionDetail&) const = default;
};

// Frozen with the bootstrap subset.
struct SessionsListRequest {
    bool operator==(const SessionsListRequest&) const = default;
};

// Frozen with the bootstrap subset.
struct SessionsListResponse {
    std::vector<SessionSummary> sessions;

    bool operator==(const SessionsListResponse&) const = default;
};

struct SessionsGetRequest {
    SessionId id;

    bool operator==(const SessionsGetRequest&) const = default;
};

struct SessionsGetResponse {
    SessionSummary summary;
    SessionDetail detail;

    bool operator==(const SessionsGetResponse&) const = default;
};

struct SessionsSetLeaseRequest {
    SessionId id;
    LeaseKind lease{};

    bool operator==(const SessionsSetLeaseRequest&) const = default;
};

struct SessionsSetLeaseResponse {
    bool operator==(const SessionsSetLeaseResponse&) const = default;
};

// Frozen with the bootstrap subset.
struct SessionsStopRequest {
    SessionId id;
    // Time between the graceful request and the kill; 0 means the default.
    u32 grace_ms = 0;

    bool operator==(const SessionsStopRequest&) const = default;
};

// Frozen with the bootstrap subset.
struct SessionsStopResponse {
    bool operator==(const SessionsStopResponse&) const = default;
};

struct SessionStateChanged {
    SessionSummary session;

    bool operator==(const SessionStateChanged&) const = default;
};

struct SessionSpawned {
    ProcessRole role{};
    u32 pid = 0;

    bool operator==(const SessionSpawned&) const = default;
};

struct SessionDegraded {
    Diagnostic reason;

    bool operator==(const SessionDegraded&) const = default;
};

struct SessionEnded {
    EndReason reason{};
    std::optional<i32> exit_code;
    std::optional<Diagnostic> error;

    bool operator==(const SessionEnded&) const = default;
};

// Play and host sessions, whatever started them.
class ISessionsHandler {
public:
    virtual ~ISessionsHandler() = default;

    virtual ::reboot::Result<SessionsListResponse> list(const CallContext& context, const SessionsListRequest& request) = 0;
    virtual ::reboot::Result<SessionsGetResponse> get(const CallContext& context, const SessionsGetRequest& request) = 0;
    virtual ::reboot::Result<SessionsSetLeaseResponse> set_lease(const CallContext& context, const SessionsSetLeaseRequest& request) = 0;
    // Completes with SessionsStopResponse.
    virtual ::reboot::Result<::reboot::OpHandle> start_stop(const CallContext& context, const SessionsStopRequest& request, ::reboot::DisconnectPolicy disconnect) = 0;
};

}  // namespace reboot::api
