// Generated by protoc-gen-reboot-cpp from reboot/api/v1/settings.proto. Do not edit.
#pragma once

#include <optional>
#include <string>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/codec.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace reboot::api {

enum class SettingGroup : u32 {
    Play = 0,
    Host = 1,
    Backend = 2,
    App = 3,
};

// Mirrors storage::ValueKind: the editor a key needs.
enum class SettingKind : u32 {
    Bool = 0,
    Text = 1,
    OptionalPath = 2,
    // One of SettingDescriptor.choices.
    Choice = 3,
    // One of Settings.console_keys.
    ConsoleKey = 4,
    BackendTarget = 5,
};

// Mirrors reboot::Sensitivity: how much of the value logs and exports may show.
enum class Sensitivity : u32 {
    Public = 0,
    Personal = 1,
    Secret = 2,
};

// Where a native key event comes from.
enum class KeySource : u32 {
    // A usage id on the USB HID Keyboard/Keypad page.
    HidUsage = 0,
    // A set 1 scancode, as WM_KEYDOWN and WinUI KeyStatus report it.
    WindowsScancode = 1,
    // NSEvent.keyCode.
    MacosKeycode = 2,
    // A linux/input-event-codes.h KEY_* code: the X11 or xkb keycode minus 8.
    Evdev = 3,
};

struct SettingDescriptor {
    std::string key;
    // The message id UIs label it with; settings search matches it too.
    std::string label;
    SettingKind kind{};
    // The persisted names CHOICE accepts, in display order.
    std::vector<std::string> choices;
    // The tab whose reset returns it to its default; absent when no reset does.
    std::optional<SettingGroup> reset_group;
    Sensitivity sensitivity{};

    bool operator==(const SettingDescriptor&) const = default;
};

// A console key a UE binding can use.
struct ConsoleKey {
    // The Unreal key name stored in backend.console_key, such as "F8".
    std::string name;
    // The key cap a picker shows, such as "`" or "Num 1"; not translated.
    std::string label;

    bool operator==(const ConsoleKey&) const = default;
};

struct SettingValue {
    // Exactly one of the following is set; none set is a case this build does not know.
    std::optional<bool> flag;
    std::optional<i64> integer;
    std::optional<std::string> text;
    std::optional<Path> path;

    bool operator==(const SettingValue&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const SettingValue& m) noexcept {
    if (auto error = one_case({m.flag.has_value(),
                               m.integer.has_value(),
                               m.text.has_value(),
                               m.path.has_value()}))
        return error;
    return std::nullopt;
}

struct Setting {
    // A dotted key such as "host.listing".
    std::string key;
    SettingValue value;
    bool is_default = false;

    bool operator==(const Setting&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const Setting& m) noexcept {
    if (auto error = check_cases(m.value)) return error;
    return std::nullopt;
}

struct SettingSearchHit {
    std::string key;
    u32 score = 0;

    bool operator==(const SettingSearchHit&) const = default;
};

struct Language {
    // A BCP-47 tag.
    std::string tag;
    bool shipped = false;

    bool operator==(const Language&) const = default;
};

struct SettingsSnapshotRequest {
    bool operator==(const SettingsSnapshotRequest&) const = default;
};

struct SettingsSnapshotResponse {
    u64 revision = 0;
    std::vector<Setting> settings;

    bool operator==(const SettingsSnapshotResponse&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const SettingsSnapshotResponse& m) noexcept {
    if (auto error = check_all_cases(m.settings)) return error;
    return std::nullopt;
}

// Refused with a conflict when the document moved past expected_revision.
struct SettingsPatchRequest {
    u64 expected_revision = 0;
    std::vector<Setting> changes;
    // Keys returned to their defaults.
    std::vector<std::string> reset_keys;

    bool operator==(const SettingsPatchRequest&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const SettingsPatchRequest& m) noexcept {
    if (auto error = check_all_cases(m.changes)) return error;
    return std::nullopt;
}

struct SettingsPatchResponse {
    u64 revision = 0;

    bool operator==(const SettingsPatchResponse&) const = default;
};

struct SettingsResetRequest {
    SettingGroup group{};
    RunningPolicy running_policy{};

    bool operator==(const SettingsResetRequest&) const = default;
};

struct SettingsResetResponse {
    u64 revision = 0;
    std::vector<std::string> reset_keys;

    bool operator==(const SettingsResetResponse&) const = default;
};

struct SettingsSearchRequest {
    std::string text;
    // The UI language the text was typed in; empty means the engine's resolved language.
    std::string language;

    bool operator==(const SettingsSearchRequest&) const = default;
};

struct SettingsSearchResponse {
    std::vector<SettingSearchHit> hits;

    bool operator==(const SettingsSearchResponse&) const = default;
};

struct SettingsFrontendStateGetRequest {
    // "windows", "macos", "linux" or "cli".
    std::string shell;

    bool operator==(const SettingsFrontendStateGetRequest&) const = default;
};

// `state` is opaque to the engine.
struct SettingsFrontendStateGetResponse {
    Bytes state;

    bool operator==(const SettingsFrontendStateGetResponse&) const = default;
};

struct SettingsFrontendStatePutRequest {
    std::string shell;
    Bytes state;

    bool operator==(const SettingsFrontendStatePutRequest&) const = default;
};

struct SettingsFrontendStatePutResponse {
    bool operator==(const SettingsFrontendStatePutResponse&) const = default;
};

struct SettingsLanguagesRequest {
    bool operator==(const SettingsLanguagesRequest&) const = default;
};

struct SettingsLanguagesResponse {
    std::vector<Language> languages;
    // "system" or a BCP-47 tag, kept even when that language is not shipped.
    std::string selected;
    std::string resolved;

    bool operator==(const SettingsLanguagesResponse&) const = default;
};

struct SettingsDescriptorsRequest {
    bool operator==(const SettingsDescriptorsRequest&) const = default;
};

// Every key, in display order.
struct SettingsDescriptorsResponse {
    std::vector<SettingDescriptor> descriptors;

    bool operator==(const SettingsDescriptorsResponse&) const = default;
};

struct SettingsConsoleKeysRequest {
    bool operator==(const SettingsConsoleKeysRequest&) const = default;
};

struct SettingsConsoleKeysResponse {
    std::vector<ConsoleKey> keys;

    bool operator==(const SettingsConsoleKeysResponse&) const = default;
};

// UIs capture a key natively and convert it here, so the tables exist once.
struct SettingsConsoleKeyFromNativeRequest {
    KeySource source{};
    u32 code = 0;
    // WINDOWS_SCANCODE: the 0xE0 prefix.
    bool extended = false;

    bool operator==(const SettingsConsoleKeyFromNativeRequest&) const = default;
};

struct SettingsConsoleKeyFromNativeResponse {
    // Absent for a key no console binding can use.
    std::optional<ConsoleKey> key;

    bool operator==(const SettingsConsoleKeyFromNativeResponse&) const = default;
};

struct SettingsChanged {
    u64 revision = 0;
    std::vector<std::string> keys;

    bool operator==(const SettingsChanged&) const = default;
};

// The settings registry and the opaque per-shell UI state.
class ISettingsHandler {
public:
    virtual ~ISettingsHandler() = default;

    virtual ::reboot::Result<SettingsSnapshotResponse> snapshot(const CallContext& context, const SettingsSnapshotRequest& request) = 0;
    virtual ::reboot::Result<SettingsPatchResponse> patch(const CallContext& context, const SettingsPatchRequest& request) = 0;
    virtual ::reboot::Result<SettingsResetResponse> reset(const CallContext& context, const SettingsResetRequest& request) = 0;
    virtual ::reboot::Result<SettingsSearchResponse> search(const CallContext& context, const SettingsSearchRequest& request) = 0;
    virtual ::reboot::Result<SettingsFrontendStateGetResponse> frontend_state_get(const CallContext& context, const SettingsFrontendStateGetRequest& request) = 0;
    virtual ::reboot::Result<SettingsFrontendStatePutResponse> frontend_state_put(const CallContext& context, const SettingsFrontendStatePutRequest& request) = 0;
    virtual ::reboot::Result<SettingsLanguagesResponse> languages(const CallContext& context, const SettingsLanguagesRequest& request) = 0;
    virtual ::reboot::Result<SettingsDescriptorsResponse> descriptors(const CallContext& context, const SettingsDescriptorsRequest& request) = 0;
    virtual ::reboot::Result<SettingsConsoleKeysResponse> console_keys(const CallContext& context, const SettingsConsoleKeysRequest& request) = 0;
    virtual ::reboot::Result<SettingsConsoleKeyFromNativeResponse> console_key_from_native(const CallContext& context, const SettingsConsoleKeyFromNativeRequest& request) = 0;
};

}  // namespace reboot::api
