// Generated by protoc-gen-reboot-cpp from reboot/api/v1/support.proto. Do not edit.
#pragma once

#include <optional>
#include <vector>

#include "reboot/api/call_context.hpp"
#include "reboot/api/codec.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

enum class SupportTier : u32 {
    Unknown = 0,
    // A logged pass for exactly these inputs.
    Tested = 1,
    Untested = 2,
    Blocked = 3,
};

enum class SupportProvider : u32 {
    Ours = 0,
    // A custom auth DLL; always Untested.
    Custom = 1,
};

struct VersionRef {
    GameVersion version;
    std::optional<u32> changelist;

    bool operator==(const VersionRef&) const = default;
};

struct SupportQueryRequest {
    // Exactly one of the following is set; none set is a case this build does not know.
    std::optional<BuildId> build;
    std::optional<VersionRef> version;
    GameRole role{};
    // Absent: the runner this OS uses for the role.
    std::optional<RunnerKind> runner;

    bool operator==(const SupportQueryRequest&) const = default;
};

[[nodiscard]] inline std::optional<DecodeError> check_cases(const SupportQueryRequest& m) noexcept {
    if (auto error = one_case({m.build.has_value(), m.version.has_value()})) return error;
    return std::nullopt;
}

struct SupportQueryResponse {
    SupportTier tier{};
    SupportProvider provider{};
    GameVersion version;
    // Why the tier is not Tested.
    std::vector<Diagnostic> reasons;

    bool operator==(const SupportQueryResponse&) const = default;
};

// Support tiers per version, role and runner.
class ISupportHandler {
public:
    virtual ~ISupportHandler() = default;

    virtual ::rb::Result<SupportQueryResponse> query(const CallContext& context, const SupportQueryRequest& request) = 0;
};

}  // namespace rb::api
