// Generated by protoc-gen-reboot-cpp from reboot/api/v1/updates.proto. Do not edit.
#pragma once

#include <optional>
#include <string>

#include "reboot/api/call_context.hpp"
#include "reboot/api/v1/common.hpp"
#include "reboot/foundation/operation.hpp"
#include "reboot/foundation/result_fwd.hpp"
#include "reboot/foundation/types.hpp"

namespace rb::api {

enum class UpdatePhase : u32 {
    Idle = 0,
    Checking = 1,
    Available = 2,
    Downloading = 3,
    Staged = 4,
    // Staged; applies once nothing is live.
    WaitingForIdle = 5,
    Applying = 6,
    Failed = 7,
};

enum class ApplyWhen : u32 {
    Idle = 0,
    // Drains live sessions first, after ConfirmStopSessions.
    Now = 1,
};

struct UpdateInfo {
    SemVer version;
    u64 size_bytes = 0;
    std::string notes_url;
    // This build is below the manifest's min_supported, so new sessions are blocked.
    bool required = false;

    bool operator==(const UpdateInfo&) const = default;
};

struct UpdatesStatusRequest {
    bool operator==(const UpdatesStatusRequest&) const = default;
};

struct UpdatesStatusResponse {
    SemVer current;
    UpdatePhase phase{};
    std::optional<UpdateInfo> available;
    u64 last_check_unix_ms = 0;
    std::optional<Diagnostic> last_error;

    bool operator==(const UpdatesStatusResponse&) const = default;
};

struct UpdatesCheckRequest {
    bool operator==(const UpdatesCheckRequest&) const = default;
};

struct UpdatesCheckResponse {
    std::optional<UpdateInfo> available;

    bool operator==(const UpdatesCheckResponse&) const = default;
};

struct UpdatesApplyRequest {
    ApplyWhen when{};

    bool operator==(const UpdatesApplyRequest&) const = default;
};

struct UpdatesApplyResponse {
    bool operator==(const UpdatesApplyResponse&) const = default;
};

struct UpdateAvailable {
    UpdateInfo update;

    bool operator==(const UpdateAvailable&) const = default;
};

struct UpdateStaged {
    UpdateInfo update;

    bool operator==(const UpdateStaged&) const = default;
};

// The engine is about to exit to apply; clients reconnect to the new build.
struct EngineUpdating {
    SemVer version;

    bool operator==(const EngineUpdating&) const = default;
};

struct UpdateFailed {
    Diagnostic error;

    bool operator==(const UpdateFailed&) const = default;
};

// Launcher self-update.
class IUpdatesHandler {
public:
    virtual ~IUpdatesHandler() = default;

    virtual ::rb::Result<UpdatesStatusResponse> status(const CallContext& context, const UpdatesStatusRequest& request) = 0;
    // Completes with UpdatesCheckResponse.
    virtual ::rb::Result<::rb::OpHandle> start_check(const CallContext& context, const UpdatesCheckRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
    // Completes with UpdatesApplyResponse.
    virtual ::rb::Result<::rb::OpHandle> start_apply(const CallContext& context, const UpdatesApplyRequest& request, ::rb::DisconnectPolicy disconnect) = 0;
};

}  // namespace rb::api
